README.md
resolves #31
We will be able to finish with HTTP interface section, once we have all functionality implemented.
=> Adjusted README.md

lib/ae_mdw/application.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw/db/stream/object.ex, lib/ae_mdw/db/stream/scope.ex, lib/ae_mdw/db/stream/stream.ex, lib/ae_mdw/db/stream/type.ex, lib/ae_mdw/db/sync/transaction.ex, lib/ae_mdw/db/util.ex, lib/ae_mdw/error.ex, lib/ae_mdw/ets_cache.ex, lib/ae_mdw/util.ex, lib/ae_mdw/validate.ex, lib/ae_mdw_web/cont.ex, lib/ae_mdw_web/controllers/aenode_controller.ex, lib/ae_mdw_web/controllers/contract_controller.ex, lib/ae_mdw_web/controllers/generation_controller.ex, lib/ae_mdw_web/controllers/transaction_controller.ex, lib/ae_mdw_web/controllers/tx_controller.ex, lib/ae_mdw_web/data_offset_plug.ex, lib/ae_mdw_web/data_stream_plug.ex, lib/ae_mdw_web/normalize.ex, lib/ae_mdw_web/router.ex, lib/ae_mdw_web/supervisor.ex, lib/ae_mdw_web/util.ex, lib/ae_mdw_web/validate.ex
=> Ks session del

README.md, lib/ae_mdw/application.ex, lib/ae_mdw_web/cont.ex, lib/ae_mdw_web/data_stream_plug.ex, lib/ae_mdw_web/websocket/listener.ex, lib/ae_mdw_web/websocket/supervisor.ex, mix.exs, test/ae_mdw_web/controllers/page_controller_test.exs, test/ae_mdw_web/controllers/tx_controller_test.exs, test/ae_mdw_web/controllers/util_controller_test.exs, test/ae_mdw_web/websocket_test.exs, test/test_helper.exs
=> Tests for different endpoints

lib/ae_mdw_web/controllers/block_controller.ex, priv/static/swagger.json
=> Added swagger specs for block/blocki/blocks endpoints

README.md, lib/ae_mdw_web/benchmark/bench.ex, test/ae_mdw_web/controllers/util_controller_test.exs
=> Extended the performance tests with name and block endpoints

lib/ae_mdw_web/controllers/block_controller.ex, lib/ae_mdw_web/controllers/name_controller.ex, lib/ae_mdw_web/controllers/tx_controller.ex, lib/ae_mdw_web/controllers/util_controller.ex, priv/static/swagger.json
=> Described the models for the responses in the swagger spec

lib/ae_mdw_web/controllers/block_controller.ex, lib/ae_mdw_web/controllers/name_controller.ex, lib/ae_mdw_web/controllers/oracle_controller.ex, lib/ae_mdw_web/swagger_parameters.ex, priv/static/swagger.json
=> Added swagger specs for oracles and name owned by endpoints

.dockerignore, Dockerfile, Makefile, README.md, docker-compose.yml, docker/aeternity.yaml, docker/entrypoint.sh, frontend/package.json, mix.lock, priv/static/swagger.json
This PR:
1. Updates and improves user experience with docker container.
2. Updated Readme file with recent changes to the project and docker.
3. Adds various small fixes here and there.
=> Updated docker, docs and makefile

README.md, frontend/package-lock.json, lib/ae_mdw/db/format.ex, lib/ae_mdw_web/controllers/name_controller.ex, priv/static/swagger.json
This PR:
- Adds name hashes to naming endpoints
- Updates docs, examples, swagger specification
- Bumps frontend deps versions
=> Minor name extensions

lib/ae_mdw/db/util.ex
=> Fix runtime error when calling /status endpoint [#123]

lib/ae_mdw/error.ex, lib/ae_mdw/exception.ex, lib/ae_mdw_web/util.ex
=> Return correct status code when resource is not found. [#111]

lib/ae_mdw_web/controllers/aex9_controller.ex
=> Return more info about transactions in /aex9/transfers endpoints [#198]

.github/actions/tests-common/action.yml, .github/workflows/test-action.yml, .gitignore, Makefile, docker-compose.yml, mix.exs, scripts/dialyzer.sh, scripts/lint.sh, scripts/test.sh
=> ci: add ci proposal with github actions

mix.exs
Increase MW version number for release candidate.
Validate fixes in Testnet for the issues:
#167 
#194 
These integration tests fail:
1) test txi renders errors when data is not found (AeMdwWeb.TxControllerTest)
2) test pointers renders error when the name is missing (AeMdwWeb.NameControllerTest)
3) test name renders error when no such name is present (AeMdwWeb.NameControllerTest)
4) test pointers get pointers for valid given name (AeMdwWeb.NameControllerTest)
5) test blocki renders error when mickro block index is not present (AeMdwWeb.BlockControllerTest)
6) test status get middleware status (AeMdwWeb.UtilControllerTest)
Finished in 11.7 seconds
148 tests, 6 failures, 7 excluded
=> release: version number for 1.0.10-rc1

lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/format.ex, lib/ae_mdw/db/name.ex, lib/ae_mdw/db/oracle.ex, lib/ae_mdw/db/origin.ex, lib/ae_mdw/db/stream/mapper.ex, lib/ae_mdw/db/stream/scope.ex, lib/ae_mdw/db/stream/stream.ex, lib/ae_mdw/db/sync/invalidate.ex, lib/ae_mdw/db/sync/name.ex, lib/ae_mdw/db/sync/oracle.ex, lib/ae_mdw/db/sync/sync.ex, lib/ae_mdw/db/sync/transaction.ex, lib/ae_mdw/db/util.ex
The purpose of this is to get rid of warning on subsequent PRs
=> style: fix credo alias warning for most files

mix.exs
Fixes version line in mix.exs (release please will be fixed by a following PR).
=> fix: mix version comma

lib/ae_mdw/collection.ex, lib/ae_mdw/mnesia.ex, lib/ae_mdw/oracles.ex
AwMdw.Collection functions are going to be reused all over the paginated results.
=> refactor: add Collection module to deal with complex pagination

lib/ae_mdw/application.ex, lib/ae_mdw/node _helper.ex, lib/mix/tasks/migrate_db.ex, mix.exs, priv/migrations/20210826171900_reindex_remote_logs.ex, priv/migrations/20210914100800_index_inner_txs.ex
Runs migrate_db task automatically on Mdw startup.
https://p.aeternity.org/projects/core-dev-features-elixir-middleware/work_packages/4549
Sync step/phase working in Mdw startup:
=> feat: auto migrate_db on start

lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/format.ex, lib/ae_mdw/db/sync/contract.ex, lib/ae_mdw/node/db.ex, lib/ae_mdw_web/controllers/aex9_controller.ex, lib/ae_mdw_web/helpers/aex9_helper.ex, lib/ae_mdw_web/views/aex9_view.ex, lib/mix/tasks/migrate_db.ex, priv/migrations/20210921123000_index_aex9_account_presence.ex, test/ae_mdw/db/contract_test.exs, test/ae_mdw/db/planner_test.exs
Once transfer event is something manually emitted from the contract code, account presence might be updated after any transfer as a best effort to keep track of 'account-to-contract' mapping.
Fixes #186 as a best effort as the complete mapping (of all accounts with balance in the contract) depends on contract code to emit the event.
An account might appear in:
/aex9/balances/:contract_id
but not in:
/aex9/balances/account/:account_id
1. With `master` branch, this account is initially not mapped to any contract (before running the migration, which runs automatically):
http://localhost:4000/aex9/balances/account/ak_2CuCtmoExsuW7iG5BbRAoncSZAoZt8Abu21qrPUhqfFNin75iL
http://localhost:4000/aex9/balances/account/ak_eYHyfKSZiU3nzDTJBkrXAzVszoxDU4DHDw5xz6f2i5YVME234
2. Run the Mdw with …
=> feat: account presence based on aex9 balance

priv/migrations/20210921123001_index_aex9_account_presence.ex
Simplifies account aex9 presence migration by filtering directly with `:mnesia` instead of the full query (to get tx details) like the `/aex9/balances/account/:account_id` endpoint.
Migration was taking too long. There were as many contract call dispatches as contract calls indexed in database.
Now the migration performs only one contract call dispatch (full query not needed, just checks the aex9 presence once).
This prevents an error in Migration that might happen on getting tx details like the above mentioned endpoint:
```
** (Mix) Could not start application ae_mdw: bad return value: {{AeMdw.Application, :start_phase, [:migrate_db, :normal, []]}, {:EXIT, {%ArgumentError{message: "got empty list"}, [{AeMdw.Util, :one!, 1, [file: 'lib/ae_mdw/util.ex', line: 5]}, {AeMdw.Db.Contract, …
```
=> chore: simplified account aex9 presence filtering

lib/ae_mdw/db/origin.ex
=> fix: return nil when contract tries fetching non-synced tx

README.md
Thank you for the reminder @marc0olo.
=> docs: readme update for inner txs filtering

lib/ae_mdw/names.ex
Fixes rendering of names claimed with a GaMetaTx (more nested).
=> fix: ga_meta_tx claimed name rendering

lib/ae_mdw/transfers.ex, lib/ae_mdw_web/controllers/transfer_controller.ex, lib/ae_mdw_web/controllers/tx_controller.ex, lib/ae_mdw_web/plugs/paginated_plug.ex, lib/ae_mdw_web/router.ex, test/integration/ae_mdw_web/controllers/transfer_controller_test.exs
This is a preamble to implementing the ability to filter transfers by
a txis scope.
=> feat: add cursor-based pagination to transfers endpoints

lib/ae_mdw/transfers.ex, test/integration/ae_mdw_web/controllers/transfer_controller_test.exs
=> feat: allow scoping transfers by txis

lib/ae_mdw/transfers.ex, test/integration/ae_mdw_web/controllers/transfer_controller_test.exs
=> fix: allow filtering transfer by kind when backwards direction

lib/ae_mdw/sync/async_tasks/derive_aex9_presence.ex
=> fix: filtering aex9 call and recipients

README.md
=> docs: update cursor-based pagination usage on the README.md

lib/ae_mdw/contract.ex
Applies transactions to get contract events only when the micro block has a contract call tx.
Events are grouped by `tx_hash` and are read only when the tx is a `:contract_call_tx`:
https://github.com/aeternity/ae_mdw/blob/ee3465822fecf346acc564e36f9e209faf8444f8/lib/ae_mdw/db/sync/transaction.ex#L82
Contribute to #346 
Possibly `:contract_create_tx` events and those derived from channel execution should be indexed but are discussed in a separate issue in favor of incremental changes (#377)
```
defmodule CacheTxs do
alias AeMdw.Db.Model
require Model
def read_events(%Range{first: _from_height, last: _to_height} = range) do
range
|> Enum.map(fn height ->
{_key_block, micro_blocks} = AeMdw.Node.Db.get_blocks(height)
{
height, 
micro_blocks
|> Enum.with_index()
|> Enum.flat_map(fn {mblock, …
```
=> perf: events only for mbs with contract calls

config/config.exs
=> chore: include date on info.log

lib/ae_mdw/contract.ex, lib/ae_mdw/db/mutations/write_links_mutation.ex, lib/ae_mdw/db/sync/contract.ex, lib/ae_mdw/db/sync/transaction.ex, test/integration/ae_mdw_web/controllers/contract_controller_test.exs
Resolve #377 
elixir --sname aeternity@localhost -S mix test.integration test/integration/ae_mdw_web/controllers/contract_controller_test.exs
=> feat: index contract init events and internal calls

lib/ae_mdw/db/sync/name.ex
=> chore: add additional logging information for auction updates

lib/ae_mdw/db/sync/contract.ex
=> perf: cache contract creation txi

lib/ae_mdw/contract.ex
Get's contract code indirectly when its code is a reference to another contract.
Fixes #405
=> fix: get info for contract with :ref instead of :code

.github/workflows/test-action.yml, README.md, lib/ae_mdw/db/format.ex, lib/ae_mdw/db/mutations/write_links_mutation.ex, lib/ae_mdw/db/stream/query/parser.ex, lib/ae_mdw/txs.ex, mix.exs, priv/migrations/20211220163202_index_ga_attach_txs.ex, test/integration/ae_mdw_web/controllers/tx_controller_test.exs
Index `:ga_attach_tx` by contract pubkey (GA smart contract).
Resolves #397 
`elixir --sname aeternity@localhost -S mix test.integration test/integration/ae_mdw_web/controllers/contract_controller_test.exs`
=> feat: index ga_attach_tx by contract

.github/workflows/test-action.yml, lib/ae_mdw/db/contract.ex, lib/ae_mdw/sync/async_tasks/update_aex9_presence.ex, lib/ae_mdw_web/controllers/aex9_controller.ex, lib/ae_mdw_web/views/aex9_view.ex, priv/migrations/20211224162001_reindex_aex9_account_presence.ex, test/integration/ae_mdw_web/controllers/aex9_controller_test.exs
Adds token info to `/aex9/balances/account/:account` response.
Resolves #416
`elixir --sname aeternity@localhost -S mix test.integration test/integration/ae_mdw_web/controllers/aex9_controller_test.exs:203`
`elixir --sname aeternity@localhost -S mix test.integration test/integration/ae_mdw_web/controllers/aex9_controller_test.exs`
=> feat: aex9 balances for an account with token info

test/integration/ae_mdw_web/controllers/tx_controller_test.exs
The purpose of this is to be able to test pagination properly on all
tx endpoints.
=> test: restructure tx_controller integration tests

lib/ae_mdw_web/router.ex
=> chore: disable accoutnt txs legacy endpoint

.gitignore, Dockerfile, config/config.exs, config/dev.exs, lib/ae_mdw/application.ex, lib/ae_mdw/db/status.ex, test/integration/ae_mdw_web/controllers/util_controller_test.exs
Resolves #419 
- `elixir --sname aeternity@localhost -S mix test.integration test/integration/ae_mdw_web/controllers/util_controller_test.exs`
- run container with make docker-shell
- run container with docker-compose up -d
=> build: add mdw revision to status

lib/ae_mdw/contract.ex, lib/ae_mdw/db/mutations/contract_call_mutation.ex, lib/ae_mdw/db/mutations/contract_create_mutation.ex, lib/ae_mdw/db/mutations/write_links_mutation.ex, lib/ae_mdw/db/sync/contract.ex, lib/ae_mdw/db/sync/transaction.ex
#426  needs to be merged first
=> perf: create ContractCallMutation

lib/ae_mdw/db/mutations/write_field_mutation.ex, lib/ae_mdw/db/mutations/write_links_mutation.ex, lib/ae_mdw/db/sync/transaction.ex
=> refactor: extract channel_create_tx syncing to Sync.Transaction

lib/ae_mdw/db/sync/transaction.ex, lib/ae_mdw/node.ex
=> fix: execute block_rewards mutation before stats mutation

lib/ae_mdw/db/mutations/oracle_register_mutation.ex, lib/ae_mdw/db/mutations/write_field_mutation.ex, lib/ae_mdw/db/mutations/write_links_mutation.ex, lib/ae_mdw/db/sync/oracle.ex, lib/ae_mdw/db/sync/transaction.ex
=> perf: extract OracleRegister transaction into mutation

lib/ae_mdw/db/mutations/name_claim_mutation.ex, lib/ae_mdw/db/mutations/write_field_mutation.ex, lib/ae_mdw/db/mutations/write_links_mutation.ex, lib/ae_mdw/db/sync/name.ex, lib/ae_mdw/db/sync/transaction.ex, lib/ae_mdw/names.ex
Requires #430 to be merged first
=> perf: extract name claim mutation

lib/ae_mdw/contract.ex
Drop micro-block txs after contract calls for less dry-running load. The events of these txs (when produced) are not read so avoids dry-running these txs.
The ones before the contract calls are preserved/not dropped from dry run because they change the chain state trees that are an input for contract calls dry run.
Profiling the reading from generation 0 to 540,000:
loading blocks: 7h40m
loading blocks + events: 12h20m
loading blocks + events dropping unused txs: 11h20m
Loading blocks here means only reading them from the Node and events to dry run the txs of these blocks.
refs #346
=> perf: drop txs not used for events

lib/ae_mdw/db/model.ex, lib/ae_mdw/db/sync/contract.ex, lib/ae_mdw/db/sync/transaction.ex, priv/migrations/20220117033300_index_oracle_register.ex, test/ae_mdw/db/sync/contract_test.exs, test/integration/ae_mdw_web/controllers/oracle_controller_test.exs
=> fix: register oracles created through Oracle.register contract calls

test/integration/ae_mdw_web/controllers/stats_controller_test.exs
This single test unnecessarily failing was driving me nuts
=> test: fix the single stats test that is failing

lib/ae_mdw/contracts.ex, lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/format.ex, lib/ae_mdw/db/mutations/write_field_mutation.ex, lib/ae_mdw/db/origin.ex, lib/ae_mdw/db/sync/contract.ex, lib/ae_mdw/db/sync/transaction.ex, lib/ae_mdw/sync/async_tasks/derive_aex9_presence.ex, lib/ae_mdw/sync/async_tasks/update_aex9_presence.ex, mix.exs, priv/migrations/20211224162001_reindex_aex9_account_presence.ex, test/ae_mdw/db/sync/contract_test.exs, test/integration/ae_mdw/db/sync/contract_test.exs, test/integration/ae_mdw/sync/contract_call_mutation_test.exs, test/integration/ae_mdw_web/controllers/aex9_controller_test.exs, test/integration/ae_mdw_web/controllers/contract_controller_test.exs
=> fix: index the origin of contracts created via Chain.clone/create

lib/ae_mdw/contract.ex, lib/ae_mdw/contracts.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw/db/name.ex, lib/ae_mdw/node.ex
=> fix: extract pointers from internal calls

lib/ae_mdw/db/oracle.ex, lib/ae_mdw/db/sync/contract.ex, lib/ae_mdw/db/sync/transaction.ex, priv/migrations/20220124162300_oracle_respond_internal_calls.ex, test/ae_mdw/db/sync/contract_test.exs, test/integration/ae_mdw/db/sync/contract_test.exs
=> fix: index Oracle.respond internal contract calls

lib/ae_mdw/db/sync/contract.ex
not yet the fix for sync issue (#485) as there are no `AENS.claim` internal calls but this fix is needed
=> fix: name and oracle int calls filtering

lib/ae_mdw/db/sync/transaction.ex, lib/ae_mdw/mnesia.ex, priv/migrations/20211220163202_index_ga_attach_txs.ex, test/ae_mdw/db/sync/transaction_test.exs
=> fix: nested or nil mutation processing

lib/ae_mdw/contract.ex, lib/ae_mdw/db/format.ex, lib/ae_mdw/db/sync/transaction.ex, priv/migrations/20210914100800_index_inner_txs.ex
=> fix: get aex9 meta info error handling

lib/ae_mdw/db/sync/name.ex
=> fix: updates txi when internal call expiration is unchanged

lib/ae_mdw/db/contract.ex, lib/ae_mdw_web/controllers/aex9_controller.ex, lib/ae_mdw_web/router.ex, test/integration/ae_mdw_web/controllers/aex9_controller_test.exs
=> feat: /aex9/by_contract search

lib/ae_mdw/contract.ex, lib/ae_mdw/db/mutations/contract_call_mutation.ex, lib/ae_mdw/db/sync/contract.ex, lib/ae_mdw/db/sync/transaction.ex, lib/ae_mdw_web/controllers/aex9_controller.ex, test/integration/ae_mdw/sync/contract_call_mutation_test.exs
Index AEX9 contracts created by a `:contract_call_tx`
Resolves #425
1. setup testnet
2. `elixir --sname aeternity@localhost -S mix test.integration test/integration/ae_mdw/sync/contract_call_mutation_test.exs:149`
=> feat: aex9 contract created by call tx

Dockerfile, config/config.exs, docker-compose.yml
Development config for ad-hoc images.
Not necessarily a fix but might also help with #518
=> build: aecore network id

config/config.exs, docker-compose.yml
=> chore: mnesia and mdw.db under same data dir

lib/ae_mdw/db/format.ex, lib/ae_mdw/db/origin.ex
=> fix: raise exception when aex9 contract doesn't exist

README.md, lib/ae_mdw/names.ex, lib/ae_mdw_web/controllers/name_controller.ex, lib/ae_mdw_web/plugs/paginated_plug.ex, lib/ae_mdw_web/router.ex, test/ae_mdw_web/controllers/name_controller_test.exs, test/integration/ae_mdw_web/controllers/name_controller_test.exs, test/integration/ae_mdw_web/controllers/oracle_controller_test.exs
=> refactor: change name routes to be consistent with core

lib/ae_mdw/blocks.ex, lib/ae_mdw/error.ex, lib/ae_mdw_web/controllers/block_controller.ex, lib/ae_mdw_web/controllers/fallback_controller.ex
=> refactor: add fallback controller to deal with errors consistently

README.md, lib/ae_mdw_web/router.ex
=> chore: withhold non-migrated v2 routes

README.md, lib/ae_mdw/util.ex, lib/ae_mdw_web/controllers/block_controller.ex, lib/ae_mdw_web/router.ex, test/integration/ae_mdw_web/controllers/block_controller_test.exs
=> feat: add v2 blocks endpoints

lib/ae_mdw/db/model.ex, lib/ae_mdw/db/mutations/oracle_register_mutation.ex, lib/ae_mdw/db/mutations/oracles_expiration_mutation.ex, lib/ae_mdw/db/oracle.ex, lib/ae_mdw/oracles.ex, lib/ae_mdw_web/controllers/oracle_controller.ex, lib/ae_mdw_web/router.ex, test/integration/ae_mdw_web/controllers/oracle_controller_test.exs
=> feat: add v2 oracles endpoints

README.md, lib/ae_mdw_web/router.ex, test/integration/ae_mdw_web/controllers/stats_controller_test.exs
Requires #554 to be merged first
=> feat: add v2 stats endpoints

lib/ae_mdw/db/format.ex, lib/ae_mdw/stats.ex, lib/ae_mdw/util.ex, lib/ae_mdw_web/controllers/stats_controller.ex, test/integration/ae_mdw_web/controllers/stats_controller_test.exs
=> fix: /stats counters with negative values

README.md
=> docs: fully update routes v2 txs routes in README

README.md
=> docs: fix readme routes

.gitignore, check_endpoints.sh
=> chore: added check script for readme routes

lib/ae_mdw/aex9.ex, lib/ae_mdw_web/controllers/aex9_token_controller.ex, lib/ae_mdw_web/router.ex, test/integration/ae_mdw_web/controllers/aex9_token_controller_test.exs
This endpoint would return the history of any given contract/account
between a given generations timeframe.
=> feat: add AEX9 v2 endpoint to retrieve balance history

lib/ae_mdw/database.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw/db/mutations/stats_mutation.ex, lib/ae_mdw/db/rocksdb_cf.ex, lib/ae_mdw/db/sync/stats.ex, lib/ae_mdw/db/sync/transaction.ex, lib/ae_mdw/stats.ex, test/ae_mdw/db/rocksdbcf_test.exs
=> refactor: stats tables persisted with rocksdb

lib/ae_mdw/application.ex, lib/ae_mdw/db/sync/sync.ex, mix.exs
=> fix: start syncing mdw after running migrations

lib/ae_mdw/collection.ex, lib/ae_mdw/database.ex, lib/ae_mdw/db/int_transfer.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw/db/mutations/aex9_account_balance_mutation.ex, lib/ae_mdw/db/mutations/block_rewards_mutation.ex, lib/ae_mdw/db/mutations/delete_keys_mutation.ex, lib/ae_mdw/db/mutations/name_claim_mutation.ex, lib/ae_mdw/db/mutations/name_revoke_mutation.ex, lib/ae_mdw/db/mutations/name_transfer_mutation.ex, lib/ae_mdw/db/mutations/name_update_mutation.ex, lib/ae_mdw/db/mutations/names_expiration_mutation.ex, lib/ae_mdw/db/mutations/oracle_response_mutation.ex, lib/ae_mdw/db/mutations/update_ids_counts_mutation.ex, lib/ae_mdw/db/mutations/write_field_mutation.ex, lib/ae_mdw/db/mutations/write_fields_mutation.ex, lib/ae_mdw/db/name.ex, lib/ae_mdw/db/oracle.ex, lib/ae_mdw/db/origin.ex, lib/ae_mdw/db/sync/id_counter.ex, lib/ae_mdw/db/sync/invalidate.ex, lib/ae_mdw/db/sync/name.ex, lib/ae_mdw/db/sync/origin.ex, lib/ae_mdw/db/sync/transaction.ex, lib/ae_mdw/db/util.ex, lib/ae_mdw/names.ex, test/ae_mdw/db/sync/transaction_test.exs
=> refactor: chain and name tables persisted with rocksdb

config/config.exs, lib/ae_mdw/application.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw/db/setup.ex
=> chore: clean node db hooks from mdw

lib/ae_mdw/db/origin.ex
=> fix: get pubkey for child contracts

test/ae_mdw/db/rocksdbcf_test.exs
Fix for CI error on last merge to master.
=> test: fix intermittent RocksDbCF concurrent error

lib/ae_mdw/db/status.ex, lib/ae_mdw/sync/server.ex
=> fix: restart sync server after sync fails

.github/workflows/test-action.yml, docker-compose.yml
=> fix: docker include priv volume for migrations to be found

lib/ae_mdw/db/origin.ex
=> fix: include ga_attach_tx when trying to find call origins

lib/ae_mdw/aex9.ex, lib/ae_mdw/aexn_contracts.ex, lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw/db/mutations/aexn_create_contract_mutation.ex, lib/ae_mdw/db/mutations/contract_call_mutation.ex, lib/ae_mdw/db/sync/contract.ex, lib/ae_mdw/dry_run/contract.ex, lib/ae_mdw/dry_run/runner.ex, lib/ae_mdw_web/controllers/aex9_controller.ex, lib/ae_mdw_web/views/aexn_view.ex, priv/migrations/20220524150501_update_aex9_with_logs.ex, priv/migrations/20220607100103_aexn_extensions.ex, test/ae_mdw/aexn_tokens_test.exs, test/ae_mdw/db/aexn_create_contract_mutation_test.exs, test/ae_mdw/db/contract_create_mutation_test.exs, test/ae_mdw/db/contract_test.exs, test/ae_mdw/db/sync/contract_test.exs, test/ae_mdw/db/sync/transaction_test.exs, test/ae_mdw/sync/invalidate_test.exs, test/integration/ae_mdw_web/controllers/aex9_controller_test.exs
=> feat: save and display aexn extensions

lib/ae_mdw/dry_run/runner.ex
Reduce gas limit to exactly the Node base gas.
refs #721
=> chore: reduce gas limit to Node base gas

lib/ae_mdw/aexn_contracts.ex, lib/ae_mdw/aexn_tokens.ex, lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/sync/contract.ex, test/ae_mdw/db/aexn_create_contract_mutation_test.exs, test/ae_mdw/db/contract_create_mutation_test.exs, test/ae_mdw/db/contract_test.exs, test/ae_mdw/db/sync/contract_test.exs, test/ae_mdw/db/sync/transaction_test.exs, test/ae_mdw_web/controllers/aexn_token_controller_test.exs
=> feat: truncate aexn name and symbol sorting fields

lib/ae_mdw/db/contract.ex, test/integration/ae_mdw_web/controllers/aex9_controller_test.exs
=> fix: dedup aex9 presence

priv/static/swagger_v1.yaml
=> docs: chore swagger v1 on limit param and produces output

priv/static/swagger_v1.yaml
=> docs: add aex9 to swagger v1 spec

priv/static/swagger_v1.yaml, priv/static/swagger_v2.yaml
=> docs: add aex9 to swagger v2 spec

lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/mutations/aexn_create_contract_mutation.ex, lib/ae_mdw/db/mutations/contract_call_mutation.ex, lib/ae_mdw/db/state.ex, lib/ae_mdw/sync/async_tasks/consumer.ex, lib/ae_mdw/sync/async_tasks/derive_aex9_presence.ex, lib/ae_mdw/sync/async_tasks/update_aex9_presence.ex, lib/ae_mdw/sync/server.ex, test/ae_mdw/db/contract_create_mutation_test.exs, test/ae_mdw/db/contract_test.exs
These commits were mistakenly removed when rebasing the previous branch.
=> chore: add mistakenly removed async in-mem tasks

lib/ae_mdw/db/model.ex, lib/ae_mdw/db/mutations/name_claim_mutation.ex, lib/ae_mdw/db/name.ex, lib/ae_mdw/names.ex, lib/ae_mdw_web/controllers/name_controller.ex, test/ae_mdw/db/name_claim_mutation_test.exs, test/ae_mdw/db/name_revoke_mutation_test.exs, test/ae_mdw/db/name_update_mutation_test.exs, test/ae_mdw_web/controllers/name_controller_test.exs
=> feat: sort active names by activation height

lib/ae_mdw/blocks.ex, lib/ae_mdw/contracts.ex, lib/ae_mdw/db/format.ex, lib/ae_mdw/names.ex, lib/ae_mdw/oracles.ex, lib/ae_mdw/stats.ex, lib/ae_mdw/transfers.ex, lib/ae_mdw/txs.ex, test/integration/ae_mdw_web/controllers/block_controller_test.exs, test/integration/ae_mdw_web/controllers/oracle_controller_test.exs
This is a pre-amble to start adding tx_hash for every txi found. Plus, it removes some unused code that won't need to be looked into
=> refactor: move formatting to main render functions

lib/ae_mdw_web/controllers/aex9_controller.ex, test/integration/ae_mdw_web/controllers/aex9_controller_test.exs
=> chore: add aex9 validation to v1 hash endpoints

README.md, lib/ae_mdw/contracts.ex, lib/ae_mdw/db/format.ex, lib/ae_mdw/names.ex, lib/ae_mdw/oracles.ex, lib/ae_mdw/txs.ex, lib/ae_mdw_web/controllers/name_controller.ex, lib/ae_mdw_web/plugs/paginated_plug.ex, test/ae_mdw_web/controllers/oracle_controller_test.exs, test/integration/ae_mdw_web/controllers/name_controller_test.exs, test/support/test_sample.ex
=> feat: display tx hash instead of txi when tx_hash=true

lib/ae_mdw/txs.ex, lib/ae_mdw_web/controllers/tx_controller.ex, lib/ae_mdw_web/plugs/paginated_plug.ex, test/ae_mdw_web/controllers/tx_controller_test.exs
=> feat: allow filtering transactions count by scope

lib/ae_mdw/db/model.ex, lib/ae_mdw/db/mutations/update_type_count_mutation.ex, lib/ae_mdw/db/rocksdb_cf.ex, lib/ae_mdw/db/sync/transaction.ex, lib/ae_mdw/txs.ex, priv/migrations/20220721121200_add_type_count_table.ex, test/ae_mdw_web/controllers/tx_controller_test.exs
=> feat: add new type count index for /txs/count?type=x

lib/ae_mdw/db/sync/block.ex, lib/ae_mdw/sync/server.ex
=> fix: update stats caching condition to only do it once per kb

lib/ae_mdw_web/websocket/broadcaster.ex, test/integration/ae_mdw_web/websocket_test.exs
=> fix: send duplicated tx websocekt message if sources differ

lib/ae_mdw/db/model.ex, lib/ae_mdw/db/mutations/name_claim_mutation.ex, lib/ae_mdw/db/mutations/stats_mutation.ex, lib/ae_mdw/db/name.ex, lib/ae_mdw/stats.ex, priv/migrations/20220803120000_add_name_fees_to_stats.ex, test/ae_mdw/db/mutations/stats_mutation_test.exs
=> feat: expose names locked/burned fees on stats

lib/ae_mdw/db/mutations/name_claim_mutation.ex
=> fix: increase auctions started stat only once

lib/ae_mdw/aexn_contracts.ex, test/ae_mdw/aexn_contracts_test.exs, test/ae_mdw/db/state_test.exs, test/support/ae_mdw/async_task_test_util.ex
=> chore: adapt to AEX-141 standard change

lib/ae_mdw/db/hardfork_presets.ex, test/ae_mdw/db/hardfork_presets_test.exs
=> feat: complement to migrated tokens

README.md, lib/ae_mdw/db/int_transfer.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw/db/mutations/miner_rewards_mutation.ex, lib/ae_mdw/db/sync/block.ex, lib/ae_mdw/miners.ex, lib/ae_mdw/stats.ex, lib/ae_mdw_web/controllers/stats_controller.ex, lib/ae_mdw_web/router.ex, priv/migrations/20220816120000_add_miners.ex, test/ae_mdw/stats_test.exs
refs #844 
Includes a migration that takes 15-30mins to index the already processed generation miners.
=> feat: index miners count and total rewards from fees

lib/ae_mdw_web/controllers/block_controller.ex, lib/ae_mdw_web/router.ex, lib/ae_mdw_web/util.ex, test/ae_mdw/db/sync/transaction_test.exs, test/ae_mdw_web/controllers/block_controller_test.exs, test/support/blockchain_sim.ex
Add `micro_blocks` to response when `/v2/blocks` is requested not for a block but for a generation.
Closes #873
=> chore: add micro_blocks to /v2/blocks/{height}

lib/ae_mdw/db/mutations/name_update_mutation.ex, lib/ae_mdw/db/sync/contract.ex, lib/ae_mdw/db/sync/name.ex, lib/ae_mdw/db/sync/transaction.ex, priv/migrations/20220824120000_reprocess_aens_update_calls.ex, test/ae_mdw/db/name_update_mutation_test.exs
=> fix: treat AENS.update calls name_ttl as an absolute height

lib/ae_mdw/aex9.ex, lib/ae_mdw/aexn_transfers.ex, lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw/db/sync/contract.ex, lib/ae_mdw_web/controllers/aexn_transfer_controller.ex, lib/ae_mdw_web/router.ex, lib/ae_mdw_web/views/aexn_view.ex, test/ae_mdw_web/controllers/aexn_transfer_controller_test.exs
- Adds `/aex141/transfers/:contract_id`
- Add `contract_id` filter to `/aex141/transfers/from/:sender` and to `/aex141/transfers/to/:recipient`
Refs #629
=> feat: index nft transfers by collection

README.md, lib/ae_mdw/blocks.ex, lib/ae_mdw_web/controllers/block_controller.ex, lib/ae_mdw_web/router.ex, test/ae_mdw_web/controllers/block_controller_test.exs, test/support/test_sample.ex
=> feat: add /key-blocks endpoints with txs/mbs count

README.md, lib/ae_mdw/blocks.ex, lib/ae_mdw_web/controllers/block_controller.ex, lib/ae_mdw_web/router.ex, test/ae_mdw_web/controllers/block_controller_test.exs
=> feat: add /key-blocks/:hash_or_kbi endpoint with mbs/txs count

README.md, lib/ae_mdw/blocks.ex, lib/ae_mdw_web/controllers/block_controller.ex, lib/ae_mdw_web/router.ex, test/ae_mdw_web/controllers/block_controller_test.exs
refs #888 
requires #895 to be merged first
=> feat: add /key-blocks/:hash_or_kbi/micro-blocks endpoint

lib/ae_mdw/aexn_tokens.ex, lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw/db/sync/stats.ex, lib/ae_mdw/stats.ex, lib/ae_mdw_web/controllers/aex9_controller.ex, lib/ae_mdw_web/controllers/aexn_token_controller.ex, lib/ae_mdw_web/views/aexn_view.ex, priv/migrations/20220912195001_aex141_stats.ex, test/ae_mdw/aexn_tokens_test.exs, test/ae_mdw/db/contract_call_mutation_test.exs, test/ae_mdw/db/contract_create_mutation_test.exs, test/ae_mdw_web/controllers/aex141_controller_test.exs
=> feat: add nft collection stats

README.md, lib/ae_mdw/blocks.ex, lib/ae_mdw/db/util.ex, lib/ae_mdw/txs.ex, lib/ae_mdw_web/controllers/tx_controller.ex, lib/ae_mdw_web/router.ex, test/ae_mdw_web/controllers/tx_controller_test.exs, test/integration/ae_mdw_web/controllers/tx_controller_test.exs
=> feat: add /v2/micro-blocks/:hash/txs endpoint

README.md
=> docs: include new kb/mb endpoint docs on endpoint list

test/ae_mdw/db/contract_call_mutation_test.exs, test/ae_mdw/db/name_claim_mutation_test.exs, test/ae_mdw/sync/async_tasks/update_aex9_state_test.exs, test/ae_mdw_web/controllers/activities_controller_test.exs, test/ae_mdw_web/controllers/aexn_token_controller_test.exs, test/ae_mdw_web/controllers/contract_controller_test.exs, test/ae_mdw_web/controllers/oracle_controller_test.exs, test/integration/ae_mdw_web/controllers/aexn_token_controller_test.exs, test/integration/ae_mdw_web/controllers/contract_controller_test.exs, test/integration/ae_mdw_web/controllers/name_controller_test.exs, test/integration/ae_mdw_web/controllers/tx_controller_test.exs, test/integration/ae_mdw_web/websocket_test.exs
Removes warnings detected by elixir 1.11
=> chore: cleanup tests warnings

lib/ae_mdw/activities.ex, lib/ae_mdw/db/int_transfer.ex, lib/ae_mdw/db/model.ex, test/integration/ae_mdw_web/controllers/activity_controller_test.exs
=> feat: add generation-only internal transfers to activities

lib/ae_mdw/validate.ex, lib/ae_mdw_web/controllers/tx_controller.ex
Fixes error messages tests from https://github.com/aeternity/ae_mdw/blob/master/test/integration/ae_mdw_web/controllers/tx_controller_test.exs
=> fix: return original error messages on txs invalid requests

lib/ae_mdw/activities.ex, test/ae_mdw_web/controllers/activities_controller_test.exs, test/integration/ae_mdw_web/controllers/activity_controller_test.exs
=> feat: add tx internal transfers to activities

lib/ae_mdw/contract.ex, lib/ae_mdw/db/format.ex, test/ae_mdw_web/controllers/tx_controller_test.exs, test/support/ae_mdw/node/contract_call_fixtures.ex, test/support/blockchain_sim.ex
=> chore: add return_type for ga_attach_tx

lib/ae_mdw/db/model.ex, lib/ae_mdw/db/mutations/name_claim_mutation.ex, lib/ae_mdw/db/sync/name.ex, lib/ae_mdw/names.ex, priv/migrations/20221014120000_add_name_owners_expiration_index.ex, test/ae_mdw/db/name_claim_mutation_test.exs, test/ae_mdw/db/name_revoke_mutation_test.exs, test/ae_mdw_web/controllers/name_controller_test.exs
=> feat: allow filtering names by owner/state ordered by deactivation

lib/ae_mdw/application.ex, lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/sync/stats.ex, lib/ae_mdw/node.ex, test/ae_mdw/db/contract_call_mutation_test.exs
=> feat: handle burn nft

lib/ae_mdw/channels.ex, lib/ae_mdw/db/format.ex
=> feat: add response id to channel settle rendering

lib/ae_mdw/db/contract.ex, lib/ae_mdw_web/controllers/aex9_controller.ex, test/ae_mdw_web/controllers/aex9_controller_test.exs
When getting the account balances on a certain height, use the txi from last contract call (up to this height) or from contract create as the balance `txi`.
This is consistent with the fact that all contract calls trigger a dry-run that updates the balance locally.
Closes #860 
On #969, an endpoint for hash account balance shall not use any indexed contract call for this txi but a log event that changed the balance for this account.
=> fix: use last call txi for hash account balance

lib/ae_mdw/db/name.ex, test/ae_mdw_web/controllers/name_controller_test.exs, test/support/blockchain_sim.ex
=> feat: display name buyer from inner claim tx

.github/workflows/test-action.yml, README.md, docs/swagger_v2/aexn.spec.yaml, docs/swagger_v2/base.yaml, docs/swagger_v2/blocks.spec.yaml, docs/swagger_v2/contracts.spec.yaml, docs/swagger_v2/names.spec.yaml, docs/swagger_v2/oracles.spec.yaml, docs/swagger_v2/stats.spec.yaml, docs/swagger_v2/transfers.spec.yaml, docs/swagger_v2/txs.spec.yaml, priv/static/swagger/swagger_v2.yaml, scripts/swagger-docs.py
Plus, added some linting for the swagger/README as part of the CI.
The next step would be to update the swagger v2 docs.
=> chore: divide swagger v2 docs into separate resource files

lib/ae_mdw/db/contract.ex, test/ae_mdw/db/contract_test.exs
Ignores aex9 events for the purpose of event balance update on contract creation.
=> fix: avoid double aex9 event balance update

lib/ae_mdw/sync/async_tasks/producer.ex, lib/ae_mdw/sync/async_tasks/stats.ex, test/ae_mdw/sync/async_tasks/stats_test.exs
=> fix: update async tasks db count on save

README.md, docs/swagger_v2/blocks.spec.yaml, priv/static/swagger/swagger_v2.yaml
=> docs: add new block endpoints on swagger v2 docs

lib/ae_mdw/contracts.ex
=> fix: encode non-string contract log data

lib/ae_mdw/contract.ex, test/ae_mdw_web/controllers/tx_controller_test.exs
Closes #973 
Channel fields gonna be handled on #1032
=> feat: add auth function name to ga_attach

lib/ae_mdw/aexn_contracts.ex, test/ae_mdw/aexn_contracts_test.exs
Avoids extra contract call to get extensions already returned by node contract spec.
=> refactor: get immediately returned nft extensions

README.md, docs/swagger_v2/names.spec.yaml, lib/ae_mdw/db/format.ex, lib/ae_mdw/names.ex, lib/ae_mdw_web/controllers/name_controller.ex, lib/ae_mdw_web/router.ex, priv/static/swagger/swagger_v2.yaml, test/ae_mdw_web/controllers/name_controller_test.exs
=> feat: add name /transfers and /updates paginated endpoints

lib/ae_mdw/aex141.ex, lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw/node.ex, priv/migrations/20221129180001_add_nft_template_limit.ex, test/ae_mdw/db/contract_call_mutation_test.exs, test/ae_mdw_web/controllers/aex141_controller_test.exs, test/support/ae_mdw/node/aexn_event_fixtures.ex
=> feat: handle nft template edition limit

lib/ae_mdw/aex141.ex, lib/ae_mdw_web/views/aexn_view.ex, test/ae_mdw_web/controllers/aex141_controller_test.exs, test/ae_mdw_web/controllers/aex9_controller_test.exs, test/support/blockchain_sim.ex
Fix blockchain test state for https://github.com/aeternity/ae_mdw/blob/8872290de780f44299067bb86fef20663c1e4cbf/lib/ae_mdw_web/controllers/aex9_controller.ex#L353-L356
=> test: validate kbi range with blockchainsim

README.md, docs/swagger_v2/channels.spec.yaml, lib/ae_mdw/channels.ex, lib/ae_mdw/db/format.ex, lib/ae_mdw_web/controllers/channel_controller.ex, lib/ae_mdw_web/router.ex, priv/static/swagger/swagger_v2.yaml, test/ae_mdw_web/controllers/channel_controller_test.exs
=> feat: add /v2/channels/:id detail page

.github/workflows/commitlint.yml, .github/workflows/dockerhub-dev.yml, .github/workflows/dockerhub-release.yml, .github/workflows/test-action.yml
=> ci: publish docker image on release

lib/ae_mdw/aex9.ex, lib/ae_mdw/contract.ex, lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/mutations/aexn_create_contract_mutation.ex, lib/ae_mdw/db/mutations/contract_call_mutation.ex, lib/ae_mdw/db/mutations/contract_create_mutation.ex, lib/ae_mdw/db/mutations/purge_aex9_state_mutation.ex, lib/ae_mdw/db/mutations/update_aex9_state_mutation.ex, lib/ae_mdw/db/sync/transaction.ex, lib/ae_mdw/sync/async_store_server.ex, lib/ae_mdw/sync/async_tasks/consumer.ex, lib/ae_mdw/sync/async_tasks/update_aex9_state.ex, test/ae_mdw/aex9_test.exs, test/ae_mdw/contracts_test.exs, test/ae_mdw/db/contract_call_mutation_test.exs, test/ae_mdw/db/contract_create_mutation_test.exs, test/ae_mdw/db/contract_test.exs, test/ae_mdw/db/state_test.exs, test/ae_mdw/sync/async_tasks/update_aex9_state_test.exs, test/ae_mdw_web/controllers/aex9_controller_test.exs, test/ae_mdw_web/controllers/tx_controller_test.exs, test/integration/ae_mdw_web/controllers/aex9_controller_test.exs
=> chore: index only event-based aex9 balances

README.md
Complements setup instructions for Medium article link.
=> docs: add setup scenarios details

README.md, docs/swagger_v2/channels.spec.yaml, lib/ae_mdw/channels.ex, lib/ae_mdw_web/controllers/channel_controller.ex, mix.exs, priv/static/swagger/swagger_v2.yaml, test/ae_mdw_web/controllers/channel_controller_test.exs
=> feat: add node details to channel page

lib/ae_mdw/db/format.ex, test/ae_mdw_web/controllers/tx_controller_test.exs
Yet another binary pointer to be handled: https://testnet.aeternity.io/mdw/txi/6011255 
(GaMetaTx with inner :name_update_tx having a binary non-text pointer)
=> fix: handle inner name_update pointers

lib/ae_mdw/activities.ex, lib/ae_mdw/util.ex, test/ae_mdw_web/controllers/activities_controller_test.exs
=> feat: format aexn activities same as aexn transfers endpoints

lib/ae_mdw/db/format.ex, test/ae_mdw_web/controllers/tx_controller_test.exs, test/support/ae_mdw/node/contract_call_fixtures.ex, test/support/blockchain_sim.ex
=> feat: render inner tx details

lib/ae_mdw/db/format.ex, mix.exs, test/ae_mdw_web/controllers/tx_controller_test.exs
=> feat: add offchain rounds to channel transactions

lib/ae_mdw/channels.ex, lib/ae_mdw/db/format.ex, test/ae_mdw_web/controllers/tx_controller_test.exs
=> feat: add channel participants to channel txs

lib/ae_mdw/apm/telemetry.ex, lib/ae_mdw_web/router.ex, lib/ae_mdw_web/views/error_view.ex
=> feat: monitor error 500

lib/ae_mdw_web/websocket/broadcaster.ex
Fetch "Transactions" subscribers and render "Object" once.
=> refactor: fetch txs subscribers once

lib/ae_mdw/contract.ex, lib/ae_mdw/db/mutations/contract_call_mutation.ex, lib/ae_mdw/db/sync/transaction.ex
Fix for testnet sync issue at height 728459
=> fix: handle call not found

lib/ae_mdw/util/encoding.ex, lib/ae_mdw_web/websocket/broadcaster.ex, lib/ae_mdw_web/websocket/socket_handler.ex, lib/ae_mdw_web/websocket/subscriptions.ex, test/ae_mdw/websocket/broadcaster_test.exs, test/ae_mdw/websocket/socket_handler_test.exs, test/ae_mdw/websocket/subscriptions_test.exs, test/support/ws_client.ex, test/support/ws_util.ex
=> feat: specialize ws subscription by source

README.md
=> docs: clarify event_hash base32 format

README.md, docs/swagger_v2/contracts.spec.yaml, lib/ae_mdw/contracts.ex, lib/ae_mdw_web/controllers/contract_controller.ex, lib/ae_mdw_web/views/aexn_log_view.ex, priv/static/swagger/swagger_v2.yaml, test/ae_mdw/contracts_test.exs, test/ae_mdw_web/controllers/contract_controller_test.exs, test/ae_mdw_web/views/aexn_log_view_test.exs
=> feat: encode args using types for AEX-N events

lib/ae_mdw/db/status.ex, lib/ae_mdw/db/sync/block.ex, mix.exs
Additionally handles new node sync progress.
=> chore: skip dev and miners rewards for HC

docs/swagger_v2/base.yaml
=> docs: add /mdw/ prefix to swagger base route

lib/ae_mdw_web/controllers/util_controller.ex, lib/ae_mdw_web/util.ex, test/ae_mdw_web/controllers/tx_controller_test.exs
=> fix: use 404 on missing single path param

lib/ae_mdw/apm/telemetry.ex, lib/ae_mdw_web/plugs/request_span.ex, lib/ae_mdw_web/router.ex, test/ae_mdw_web/controllers/block_controller_test.exs, test/ae_mdw_web/plugs/request_span_test.exs
=> chore: aggregate request metric per route

lib/ae_mdw/db/sync/name.ex
Removes logs that cause some sync delay while syncing 10 gens.
=> chore: remove name logs

config/config.exs, config/test.exs, lib/ae_mdw_web/websocket/socket_handler.ex, lib/ae_mdw_web/websocket/subscriptions.ex, test/ae_mdw/websocket/subscriptions_test.exs
=> chore: limit ws subscriptions

lib/ae_mdw_web/controllers/tx_controller.ex, test/ae_mdw_web/controllers/tx_controller_test.exs
=> feat: count id txs by type or type group

lib/ae_mdw/db/hardfork_presets.ex, priv/migrations/20230404095010_update_total_supply.ex, test/ae_mdw/db/hardfork_presets_test.exs
=> fix: add lima contracts minted amount to supply

docs/swagger_v2/aexn.spec.yaml
=> docs: update aex9 response and contract filter

lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/sync/stats.ex, lib/ae_mdw/stats.ex, lib/ae_mdw_web/views/aexn_view.ex, test/ae_mdw/db/contract_call_mutation_test.exs, test/ae_mdw_web/controllers/aexn_token_controller_test.exs
=> feat: track aex9 token holders count per contract

lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw/node/db.ex, lib/ae_mdw_web/views/aexn_view.ex, priv/migrations/20230412085004_index_event_supply.ex, test/ae_mdw/db/contract_test.exs, test/ae_mdw/db/state_test.exs, test/ae_mdw/db/sync/async_tasks/producer_consumer_test.exs, test/ae_mdw_web/controllers/aex9_controller_test.exs
=> feat: track aex9 contract supplies

docs/swagger_v2/aexn.spec.yaml, lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/sync/stats.ex, lib/ae_mdw/stats.ex, lib/ae_mdw_web/controllers/aexn_token_controller.ex, lib/ae_mdw_web/router.ex, priv/migrations/20230413115004_index_logs_count.ex, test/ae_mdw/db/contract_test.exs, test/ae_mdw_web/controllers/aexn_token_controller_test.exs
=> feat: track aex9 logs count

docs/swagger_v2/aexn.spec.yaml, lib/ae_mdw/aex9.ex, lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw_web/controllers/aexn_token_controller.ex, lib/ae_mdw_web/views/aexn_view.ex, priv/migrations/202300428120101_aex9_balance_account.ex, test/ae_mdw/db/contract_call_mutation_test.exs, test/ae_mdw_web/controllers/aexn_token_controller_test.exs
=> feat: sort aex9 balance per amount

README.md
=> docs: add genesis accounts section

Dockerfile, lib/ae_mdw/contract.ex, lib/ae_mdw/db/sync/contract.ex
~~This is still a [DRAFT], I need to test it out first~~
Ready for review
=> chore: update node to 6.8.1

lib/ae_mdw/db/model.ex, lib/ae_mdw/db/mutations/oracle_response_mutation.ex, lib/ae_mdw/db/util.ex, lib/ae_mdw/oracles.ex, priv/migrations/20230509120001_index_oracle_queries_responses.ex
=> feat: include oracle responses on oracle queries endpoints

priv/migrations/20230515120000_fix_internal_oracle_responses_transfers.ex
=> fix: reindex reward_oracle int transfers

Dockerfile, lib/ae_mdw/contract.ex, lib/ae_mdw/db/sync/contract.ex
This reverts commit f96f56c6405917d9a662e2f2195c745bff3d3646.
=> chore: revert "chore: update node to 6.8.1 (#1223)"

config/dev.exs, config/test.exs, lib/ae_mdw/application.ex, lib/ae_mdw_web/controllers/contract_controller.ex, lib/ae_mdw_web/views/logs_view.ex, test/ae_mdw_web/views/logs_view_test.exs
Allows rendering of custom Marketplace events.
=> feat: encode custom event args

Dockerfile, README.md, lib/ae_mdw/db/rocksdb.ex, scripts/do.sh
=> chore: let docket volumes be optional

config/runtime.exs
=> chore: setup websocket inactivity timeout

lib/ae_mdw/channels.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw/db/mutations/channel_close_mutation.ex, lib/ae_mdw_web/controllers/channel_controller.ex, priv/migrations/20230519120000_add_inactive_channels_activation.ex, test/ae_mdw_web/controllers/channel_controller_test.exs
=> feat: include inactive channels on channels listing

lib/ae_mdw/application.ex, lib/ae_mdw/db/rocksdb.ex, test/test_helper.exs
=> chore: apply Node persist config

lib/ae_mdw_web/websocket/broadcaster.ex, test/ae_mdw/websocket/broadcaster_test.exs
=> feat: add target to ws object msg

Dockerfile, lib/ae_mdw/contract.ex, lib/ae_mdw/db/sync/contract.ex
~~[WIP] Syncing both networks and checking for any errors~~
=> feat: add support for node 6.8.1 back

docs/swagger_v2/status.spec.yaml
=> docs: add status endpoint to swagger

docs/swagger_v2/aexn.spec.yaml, docs/swagger_v2/txs.spec.yaml
closes #1351
closes #1352 
aditionally fixes:
closes #1349 
closes #1350
=> docs: comply to OAS3 on params and responses

docs/swagger_v2/activities.spec.yaml, docs/swagger_v2/names.spec.yaml, docs/swagger_v2/transfers.spec.yaml, docs/swagger_v2/txs.spec.yaml
=> docs: add type:string to enum types that are missing it

docs/swagger_v2/contracts.spec.yaml, lib/ae_mdw/contracts.ex
=> chore: add function parameter alias to contract logs

docs/swagger_v2/activities.spec.yaml, docs/swagger_v2/base.yaml, docs/swagger_v2/contracts.spec.yaml, docs/swagger_v2/names.spec.yaml, docs/swagger_v2/stats.spec.yaml, docs/swagger_v2/status.spec.yaml, docs/swagger_v2/txs.spec.yaml
refs #1346 
refs #1360
refs #1361
refs #1363
=> docs: add missing info and keys to swagger schemas

docs/swagger_v2/aexn.spec.yaml
=> docs: remove produces for oas3

lib/ae_mdw/application.ex, lib/ae_mdw/ets_cache.ex, lib/ae_mdw/sync/server.ex, lib/ae_mdw_web/websocket/broadcaster.ex, lib/ae_mdw_web/websocket/broadcaster_cache.ex, lib/ae_mdw_web/websocket/chain_listener.ex, test/ae_mdw/websocket/broadcaster_test.exs
=> chore: add transactions count to websocket keyblock

lib/ae_mdw/db/util.ex, lib/ae_mdw/oracles.ex, test/ae_mdw_web/controllers/oracle_controller_test.exs
=> feat: add approximate_expiration_time to oracles

lib/ae_mdw/db/mutations/oracles_expiration_mutation.ex, lib/ae_mdw/db/mutations/stats_mutation.ex, test/ae_mdw/db/mutations/stats_mutation_test.exs
=> fix: consider all oracles expirations

test/ae_mdw_web/controllers/activities_controller_test.exs, test/ae_mdw_web/controllers/aex141_controller_test.exs, test/ae_mdw_web/controllers/aex9_controller_test.exs
The intermittent issue still happens, less often, but it does
=> test: add async:false to more test modules

lib/ae_mdw/util.ex
=> fix: include aexn contracts with special chars

config/dev.tools.sample.exs
Update sample pre-push checks. Test to be included later without docker.
=> chore: include credo and leave test for dev shell

lib/ae_mdw/auction_bids.ex, test/ae_mdw_web/controllers/name_controller_test.exs
=> feat: display approximate expiration time for auctions

lib/ae_mdw/node/db.ex, lib/ae_mdw/oracles.ex, test/ae_mdw_web/controllers/oracle_controller_test.exs
=> feat: add micro block time to oracle nested resources

lib/ae_mdw_web/controllers/util_controller.ex, lib/ae_mdw_web/router.ex, scripts/swagger-docs.py
=> feat: add support for swagger using JSON format

docs/swagger_v2/status.spec.yaml
It was missed while fixing https://github.com/aeternity/ae_mdw/issues/1356
This PR is supported by the Æternity Crypto Foundation
=> docs: add missed mdw_tx_index in /status

lib/ae_mdw/activities.ex, test/ae_mdw_web/controllers/activities_controller_test.exs
=> feat: add block_time to all activities

docs/swagger_v2/aexn.spec.yaml
=> chore: update aexn parameters to OAS3

lib/ae_mdw/contracts.ex, lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw_web/views/logs_view.ex, priv/migrations/20230705224000_event_logs_hash.ex, test/ae_mdw/contracts_test.exs, test/ae_mdw/db/contract_test.exs, test/ae_mdw_web/controllers/contract_controller_test.exs, test/ae_mdw_web/views/logs_view_test.exs
=> perf: remove event hash from log index

lib/ae_mdw/application.ex, lib/ae_mdw/db/sync/block.ex, lib/ae_mdw/sync/async_tasks/consumer.ex, lib/ae_mdw/sync/server.ex, test/ae_mdw/contracts_test.exs
=> chore: log mem and db sync profiling

docs/swagger_v2/activities.spec.yaml, docs/swagger_v2/channels.spec.yaml, docs/swagger_v2/names.spec.yaml, docs/swagger_v2/oracles.spec.yaml
=> docs: add block time to newly added places

priv/migrations/20230710171001_event_logs_hash.ex
Unify migration that works for both log formats:
- w/o hash: only re-encode records values
- with hash: change the key index and also re-encode records values
=> chore: encode event logs with a single migration

lib/ae_mdw/names.ex, test/ae_mdw_web/controllers/name_controller_test.exs
=> fix: allow using hyphen on name cursors

docs/swagger_v2/aexn.spec.yaml, lib/ae_mdw/aex141.ex, lib/ae_mdw_web/controllers/aex141_controller.ex, test/ae_mdw_web/controllers/aex141_controller_test.exs
=> feat: filter owned nfts by collection

docs/swagger_v2/oracles.spec.yaml, lib/ae_mdw/oracles.ex, test/ae_mdw_web/controllers/oracle_controller_test.exs
Even though it's not on the API spec there were examples in the README (available a time ago).
=> fix: filter oracle by state param

lib/ae_mdw/aex141.ex, lib/ae_mdw/aexn_contracts.ex, lib/ae_mdw/db/sync/contract.ex, priv/migrations/20230807090501_reindex_aexn.ex, test/ae_mdw/aexn_contracts_test.exs, test/ae_mdw/db/contract_create_mutation_test.exs, test/ae_mdw/db/sync/async_tasks/consumer_test.exs, test/ae_mdw/db/sync/contract_test.exs, test/ae_mdw/db/sync/transaction_test.exs, test/ae_mdw_web/controllers/aex141_controller_test.exs, test/support/ae_mdw/aexn_fixtures.ex
=> chore: use aexn extensions from byte code

lib/ae_mdw/db/model.ex, lib/ae_mdw/db/mutations/statistics_mutation.ex, lib/ae_mdw/db/sync/block.ex, lib/ae_mdw/db/sync/stats.ex, lib/ae_mdw/stats.ex, lib/ae_mdw_web/controllers/stats_controller.ex, lib/ae_mdw_web/plugs/paginated_plug.ex, lib/ae_mdw_web/router.ex, mix.exs, test/ae_mdw/db/sync/stats_test.exs, test/ae_mdw_web/controllers/stats_controller_test.exs, test/support/blockchain_sim.ex
=> feat: add statistics and /statistics/transactions endpoint

lib/ae_mdw/db/mutations/name_claim_mutation.ex, lib/ae_mdw/db/name.ex, lib/ae_mdw/db/sync/name.ex
Cache not needed anymore after mem store refactoring.
=> refactor: remove name cache

lib/ae_mdw/db/mutations/oracle_extend_mutation.ex, lib/ae_mdw/db/mutations/oracle_register_mutation.ex, lib/ae_mdw/db/mutations/oracles_expiration_mutation.ex, lib/ae_mdw/db/oracle.ex, lib/ae_mdw/db/sync/oracle.ex
For 100 blocks:
```
iex(aeternity@localhost)6> {ts, _} = :timer.tc(fn -> Enum.map(blocks, &AeMdw.Db.Oracle.oracle_tree!/1) end); ts
303957
iex(aeternity@localhost)7> {ts, _} = :timer.tc(fn -> Enum.map(blocks, &AeMdw.Db.Oracle.oracle_tree!/1) end); ts
106522
iex(aeternity@localhost)8> {ts, _} = :timer.tc(fn -> Enum.map(blocks, &AeMdw.Db.Oracle.oracle_tree!/1) end); ts
103858
iex(aeternity@localhost)9> {ts, _} = :timer.tc(fn -> Enum.map(blocks, &AeMdw.Db.Oracle.oracle_tree!/1) end); ts
95913
iex(aeternity@localhost)10> {ts, _} = :timer.tc(fn -> Enum.map(blocks, fn block -> :aec_db.get_block_state(block) |> :aec_trees.oracles() end) end); ts
1870040
iex(aeternity@localhost)11> {ts, _} = :timer.tc(fn -> Enum.map(blocks, fn block -> :aec_db.get_block_state(block) |> :aec_trees.oracles() end) …
```
=> chore: fetch only oracles tree

lib/ae_mdw/activities.ex, test/ae_mdw_web/controllers/activities_controller_test.exs
=> fix: dedup txs activities when present on several fields

lib/ae_mdw/db/model.ex, lib/ae_mdw/db/mutations/write_field_mutation.ex, lib/ae_mdw/db/mutations/write_fields_mutation.ex, lib/ae_mdw/db/sync/id_counter.ex, lib/ae_mdw/txs.ex, priv/migrations/20230816120000_add_dup_fields_counters.ex, test/ae_mdw/db/mutations/write_fields_mutation_test.exs, test/ae_mdw_web/controllers/tx_controller_test.exs
=> fix: ignore field/transaction counts when they are duplicated

lib/ae_mdw/contracts.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw/db/mutations/name_transfer_mutation.ex, lib/ae_mdw/db/name.ex, lib/ae_mdw/db/sync/contract.ex, lib/ae_mdw/db/sync/name.ex, lib/ae_mdw/db/sync/transaction.ex, lib/ae_mdw/names.ex, lib/ae_mdw/node/db.ex, lib/ae_mdw_web/controllers/name_controller.ex, lib/ae_mdw_web/router.ex, priv/migrations/20230815140001_name_revokes.ex, priv/migrations/20230816140001_name_expire.ex, priv/migrations/20230818093001_name_transfers.ex, scripts/do.sh, test/ae_mdw/db/name_revoke_mutation_test.exs, test/ae_mdw/db/name_transfer_mutation_test.exs, test/ae_mdw/db/sync/contract_test.exs, test/ae_mdw/db/sync/name_test.exs, test/ae_mdw_web/controllers/activities_controller_test.exs, test/ae_mdw_web/controllers/aex141_controller_test.exs, test/ae_mdw_web/controllers/aexn_token_controller_test.exs, test/ae_mdw_web/controllers/contract_controller_test.exs, test/ae_mdw_web/controllers/name_controller_test.exs, test/support/ae_mdw/db/model_fixtures.ex, test/support/ae_mdw/db/mutation_case.ex, test/support/test_util.ex
=> feat: add name history endpoint

lib/ae_mdw/activities.ex, test/ae_mdw_web/controllers/activities_controller_test.exs
=> feat: include aexn meta info on aexn activties

lib/ae_mdw/contracts.ex
Fix for https://mainnet.aeternity.io/mdw/v2/contracts/ct_3YEfCoqsHfFDnC57jcJ69pKbvXvfWnD3exZ4JwRZucF91FfHw (generalized account created with `paying_for_tx`)
=> fix: use inner tx type to render contract creation

lib/ae_mdw/contract.ex, lib/ae_mdw/contracts.ex, lib/ae_mdw/db/format.ex, lib/ae_mdw/db/sync/contract.ex, test/ae_mdw/contracts_test.exs
=> chore: add contract_id to create internal calls

lib/ae_mdw/names.ex, lib/ae_mdw/node.ex, lib/ae_mdw/validate.ex, lib/ae_mdw_web/controllers/aex9_controller.ex, lib/ae_mdw_web/controllers/name_controller.ex, test/ae_mdw_web/controllers/name_controller_test.exs
=> chore: ensure suffix on name history

docs/swagger_v2/aexn.spec.yaml, lib/ae_mdw/aex9.ex, lib/ae_mdw/aexn_tokens.ex, lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw/db/mutations/aexn_create_contract_mutation.ex, lib/ae_mdw/db/mutations/contract_call_mutation.ex, lib/ae_mdw/db/sync/contract.ex, lib/ae_mdw/db/sync/transaction.ex, lib/ae_mdw_web/controllers/aex9_controller.ex, lib/ae_mdw_web/controllers/aexn_token_controller.ex, lib/ae_mdw_web/views/aexn_view.ex, priv/migrations/20230807090501_reindex_aexn.ex, priv/migrations/20230907110001_collections_by_creation.ex, test/ae_mdw/aex9_test.exs, test/ae_mdw/aexn_tokens_test.exs, test/ae_mdw/db/aexn_create_contract_mutation_test.exs, test/ae_mdw/db/contract_create_mutation_test.exs, test/ae_mdw/db/state_test.exs, test/ae_mdw/db/sync/transaction_test.exs, test/ae_mdw_web/controllers/aex141_controller_test.exs, test/ae_mdw_web/controllers/aex9_controller_test.exs, test/ae_mdw_web/controllers/aexn_token_controller_test.exs, test/ae_mdw_web/views/aexn_view_test.exs, test/integration/ae_mdw_web/controllers/block_controller_test.exs
=> feat: sort aexn contracts by creation

lib/ae_mdw/db/contract.ex, test/support/ae_mdw/node/contract_call_fixtures.ex
refs https://github.com/aeternity/aeternity/issues/4202
=> chore: reverse call logs

lib/ae_mdw/aexn_transfers.ex, lib/ae_mdw/contracts.ex, lib/ae_mdw/db/contract.ex, lib/ae_mdw/validate.ex, lib/ae_mdw_web/controllers/aexn_transfer_controller.ex, lib/ae_mdw_web/router.ex, lib/ae_mdw_web/views/aexn_view.ex, priv/migrations/20230908160001_aex9_contract_transfers.ex, test/ae_mdw_web/controllers/aexn_transfer_controller_test.exs
closes #1580
PS: migration depends on logs records from resync/staging
=> feat: index and query aex9 transfers by contract and account

lib/ae_mdw/db/util.ex, lib/ae_mdw/error.ex, lib/ae_mdw/txs.ex, lib/ae_mdw/validate.ex, lib/ae_mdw_web/controllers/tx_controller.ex, test/ae_mdw_web/controllers/tx_controller_test.exs
=> feat: filter and count microblock txs by type

lib/ae_mdw/names.ex, test/ae_mdw_web/controllers/name_controller_test.exs
=> chore: add open auction bids to name history

lib/ae_mdw/db/contract.ex, test/ae_mdw/db/contract_create_mutation_test.exs, test/ae_mdw/db/contract_test.exs
Fix for Bonding Curve contracts deployment
=> fix: check contract creation for child contracts

lib/ae_mdw/application.ex, lib/ae_mdw/db/sync/object_keys.ex, lib/ae_mdw/sync/server.ex, lib/ae_mdw/sync/supervisor.ex, lib/ae_mdw/sync/syncing_queue.ex, lib/mix/tasks/migrate_db.ex
This is a pre-amble for async migrations
=> chore: add syncing queue for async syncing requirements

config/config.exs, lib/ae_mdw/aexn_contracts.ex, lib/ae_mdw/application.ex, lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/sync/object_keys.ex, lib/ae_mdw/node.ex, lib/ae_mdw/sync/dex_cache.ex, lib/ae_mdw_web/views/logs_view.ex, mix.exs, test/ae_mdw/db/contract_test.exs, test/ae_mdw_web/views/logs_view_test.exs, test/support/ae_mdw/node/aexn_event_fixtures.ex
=> feat: track dex pair creations

lib/ae_mdw/db/mutations/block_statistics_mutation.ex, lib/ae_mdw/db/state.ex, lib/ae_mdw/db/sync/block.ex, lib/ae_mdw/db/sync/name.ex, lib/ae_mdw/db/sync/stats.ex, lib/ae_mdw/stats.ex, lib/ae_mdw_web/controllers/stats_controller.ex, lib/ae_mdw_web/router.ex, test/ae_mdw/db/mutations/block_statistics_mutation_test.exs
=> feat: add name activation statistics

lib/ae_mdw/stats.ex, test/ae_mdw_web/controllers/stats_controller_test.exs
=> feat: add last 24 hours transactions count

lib/ae_mdw/db/format.ex, lib/ae_mdw/names.ex, test/ae_mdw_web/controllers/name_controller_test.exs
=> feat: add names approximate time on expire/activation

Dockerfile
=> chore: add cache manifest building on docker build

priv/migrations/20231226120000_index_names_statistics.ex
=> chore: index name statistics using key blocks

lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw/dex.ex, lib/ae_mdw/sync/dex_cache.ex, lib/ae_mdw_web/controllers/dex_controller.ex, lib/ae_mdw_web/router.ex, lib/ae_mdw_web/views/aexn_view.ex, test/ae_mdw/db/contract_test.exs, test/ae_mdw_web/controllers/dex_controller_test.exs, test/support/conn_case.ex
=> feat: index and fetch dex swap tokens

config/config.exs, config/runtime.exs, config/test.exs, lib/ae_mdw_web/controllers/aexn_token_controller.ex, test/ae_mdw_web/controllers/aexn_token_controller_test.exs
=> fix: handle heavy endpoint timeout

lib/ae_mdw/auction_bids.ex, lib/ae_mdw/db/format.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw/db/mutations/name_claim_mutation.ex, lib/ae_mdw/db/sync/name.ex, lib/ae_mdw/names.ex, test/ae_mdw/db/name_claim_mutation_test.exs, test/ae_mdw/db/sync/name_test.exs, test/ae_mdw_web/controllers/name_controller_test.exs
=> fix: include all auction claims when closing up an auction

priv/static/swagger/swagger.json
=> chore: update swagger.json schemes value

lib/ae_mdw/stats.ex, test/ae_mdw_web/controllers/stats_controller_test.exs
=> feat: include 48hs transactions count trend on stats

lib/ae_mdw/names.ex, lib/ae_mdw_web/controllers/name_controller.ex, lib/ae_mdw_web/router.ex, test/ae_mdw_web/controllers/name_controller_test.exs
=> feat: add v3 name and auction detail endpoint

lib/ae_mdw_web.ex, lib/ae_mdw_web/controllers/aex141_controller.ex, lib/ae_mdw_web/controllers/aex9_controller.ex, lib/ae_mdw_web/controllers/aexn_token_controller.ex, lib/ae_mdw_web/controllers/aexn_transfer_controller.ex, lib/ae_mdw_web/controllers/block_controller.ex, lib/ae_mdw_web/controllers/channel_controller.ex, lib/ae_mdw_web/controllers/contract_controller.ex, lib/ae_mdw_web/controllers/name_controller.ex, lib/ae_mdw_web/controllers/oracle_controller.ex, lib/ae_mdw_web/controllers/stats_controller.ex, lib/ae_mdw_web/controllers/tx_controller.ex, lib/ae_mdw_web/controllers/util_controller.ex, lib/ae_mdw_web/controllers/wealth_controller.ex, lib/ae_mdw_web/helpers/json_helper.ex, lib/ae_mdw_web/plugs/json_formatter_plug.ex, lib/ae_mdw_web/router.ex, lib/ae_mdw_web/util.ex, test/ae_mdw_web/helpers/json_helper_test.exs
=> feat: allow encoding ints as strings via query parameter

config/runtime.exs
refs #1662, missed out the required level in the previous PR
=> feat: allow none logger level configuration

.github/actions/node-setup/action.yml, lib/ae_mdw/db/format.ex, lib/ae_mdw/names.ex, lib/ae_mdw/validate.ex, test/ae_mdw/db/name_test.exs, test/ae_mdw/db/sync/name_test.exs, test/support/ae_mdw/node/aetx_fixtures.ex, test/support/blockchain_sim.ex
This PR adds support for the new raw data pointers format, added in the Ceres protocol
=> feat: add raw data pointers support for ceres

lib/ae_mdw/contract.ex, lib/ae_mdw/db/format.ex, lib/ae_mdw/db/mutations/contract_call_mutation.ex, lib/ae_mdw/db/mutations/write_fields_mutation.ex, lib/ae_mdw/db/name.ex, lib/ae_mdw/db/sync/transaction.ex, test/ae_mdw/contract_test.exs, test/ae_mdw/db/contract_call_mutation_test.exs, test/ae_mdw/db/mutations/write_fields_mutation_test.exs, test/ae_mdw/db/sync/transaction_test.exs, test/ae_mdw_web/controllers/activities_controller_test.exs, test/ae_mdw_web/controllers/tx_controller_test.exs, test/support/blockchain_sim.ex
Depends on #1708 since it's branched out from it
=> feat: resolve aens name to contract address when calling contract

priv/static/swagger/swagger.json
=> chore: remove schemes from swagger v1 file

docs/swagger_v3/names.spec.yaml, docs/swagger_v3/oracles.spec.yaml, lib/ae_mdw/names.ex, lib/ae_mdw/oracles.ex, lib/ae_mdw_web/controllers/oracle_controller.ex, lib/ae_mdw_web/router.ex
=> fix: update names and oracles to v3

priv/migrations/20240412120000_reindex_reverted_contract_calls.ex
=> feat: add reverted calls migration to update fun/args

lib/ae_mdw/node/db.ex, lib/ae_mdw/stats.ex, test/ae_mdw_web/controllers/stats_controller_test.exs
=> feat: add average of transaction fees for last 24 hours with trend

lib/ae_mdw/names.ex, lib/ae_mdw_web/controllers/name_controller.ex, lib/ae_mdw_web/router.ex, test/ae_mdw_web/controllers/name_controller_test.exs
=> Merge name/pointers endpoint into the name endpoint

docs/swagger_v3/activities.spec.yaml, docs/swagger_v3/aexn.spec.yaml, docs/swagger_v3/blocks.spec.yaml, docs/swagger_v3/channels.spec.yaml, docs/swagger_v3/contracts.spec.yaml, docs/swagger_v3/names.spec.yaml, docs/swagger_v3/oracles.spec.yaml, docs/swagger_v3/stats.spec.yaml, docs/swagger_v3/transactions.spec.yaml, docs/swagger_v3/transfers.spec.yaml
=> docs: make all operationIds in swagger_v3 PascalCase

lib/ae_mdw/txs.ex, lib/ae_mdw_web/router.ex, test/ae_mdw_web/controllers/tx_controller_test.exs
=> fix: handle empty transactions count

README.md, docs/swagger_v3/names.spec.yaml, lib/ae_mdw/names.ex, test/ae_mdw_web/controllers/name_controller_test.exs
=> feat: allow filtering names by prefix (case-insenstive)

Dockerfile, docker-compose-dev.yml, docker-compose-test.yml
refs https://github.com/aeternity/ae_mdw/issues/1750
=> fix: arm docker incompatibility

test/ae_mdw/websocket/broadcaster_test.exs, test/ae_mdw_web/controllers/activities_controller_test.exs, test/ae_mdw_web/controllers/tx_controller_test.exs
This PR removes some warnings and hopefully fixed the randomly failing tests in `tx_controller_test.exs`
=> test: randomly failing tests and warnings

lib/ae_mdw/db/util.ex, lib/ae_mdw_web/plugs/paginated_plug.ex, test/ae_mdw_web/controllers/tx_controller_test.exs, test/ae_mdw_web/plugs/paginated_plug_test.exs
Refs: https://github.com/aeternity/ae_mdw/issues/1756
=> filter transactions by date

Dockerfile, docker-compose-dev.yml, docker-compose.yml, docker/aeternity-dev.yaml, docker/healthcheck.sh, lib/ae_mdw_web/endpoint.ex, node_sdk/index.js, node_sdk/package-lock.json, node_sdk/package.json, node_sdk/yarn.lock, scripts/run_sdk_tests.sh
=> Devmode and related fixes

config/runtime.exs
=> feat: add flag to disable ipv6

docs/swagger_v3/aexn.spec.yaml, lib/ae_mdw/aexn_tokens.ex, lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/model.ex, priv/migrations/20240712092935_add_normalized_aexn_tables.ex, priv/migrations/20240717093510_add_normalized_aexn_tables.ex, test/ae_mdw/aexn_tokens_test.exs, test/ae_mdw/db/aexn_create_contract_mutation_test.exs, test/ae_mdw_web/controllers/aex141_controller_test.exs, test/ae_mdw_web/controllers/aex9_controller_test.exs, test/ae_mdw_web/controllers/aexn_token_controller_test.exs
=> feat: make aexn prefix search case insensitive

Dockerfile, config/prod.exs, config/runtime.exs, scripts/run_sdk_tests.sh
=> chore: add MIX_ENV=prod when building for SDK usage

docs/swagger_v3/aexn.spec.yaml, lib/ae_mdw_web/router.ex
=> fix: rename aex141 token path to conform to the others

.gitignore, Dockerfile, scripts/swagger-docs.py
A PR with the same motivation in aenode https://github.com/aeternity/aeternity/pull/4330
=> Sort paths and components in OpenApi v3

README.md, docs/architecture.md, docs/swagger_v3/activities.spec.yaml, docs/swagger_v3/aexn.spec.yaml, docs/swagger_v3/base.yaml, docs/swagger_v3/dex.spec.yaml, docs/swagger_v3/names.spec.yaml, docs/swagger_v3/oracles.spec.yaml, docs/swagger_v3/stats.spec.yaml, docs/swagger_v3/status.spec.yaml, docs/swagger_v3/transactions.spec.yaml
oracle responses example: https://mainnet.aeternity.io/mdw/v3/oracles/ok_qJZPXvWPC7G9kFVEqNjj9NAmwMsQcpRu6E3SSCvCQuwfqpMtN/responses
=> Open Api fixes

lib/ae_mdw/aex9.ex, test/ae_mdw_web/controllers/aexn_token_controller_test.exs
refs: https://github.com/aeternity/ae_mdw/issues/1257
=> fix: filter aex9 balances by amount correctly

docs/swagger_v3/aexn.spec.yaml, docs/swagger_v3/blocks.spec.yaml, docs/swagger_v3/contracts.spec.yaml, docs/swagger_v3/names.spec.yaml, docs/swagger_v3/oracles.spec.yaml, docs/swagger_v3/stats.spec.yaml, docs/swagger_v3/transactions.spec.yaml
=> Open Api fixes (probably the last)

docs/swagger_v3/transactions.spec.yaml, lib/ae_mdw/txs.ex, lib/ae_mdw_web/router.ex
refs: https://github.com/aeternity/ae_mdw/issues/1854
=> feat: transfer transactions count summary to v3

docker-compose-dev-testnet.yml, docker/aeternity_testnet.yaml, scripts/do.sh
This allows for easy switching between the two networks.
=> feat: simplify setup for testnet

lib/ae_mdw/activities.ex, lib/ae_mdw/db/format.ex, test/ae_mdw_web/controllers/activities_controller_test.exs
refs: https://github.com/aeternity/ae_mdw/issues/1642
=> feat: add amount and name to activities info

docs/swagger_v3/stats.spec.yaml
refs: https://github.com/aeternity/ae_mdw/issues/1858
=> feat: add openapi missing stats route

config/runtime.exs, lib/ae_mdw/db/mem_store.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw/db/mutations/rollback_mutation.ex, lib/ae_mdw/db/rocksdb.ex, lib/ae_mdw/db/state.ex, lib/ae_mdw/sync/server.ex, lib/ae_mdw_web/controllers/util_controller.ex, lib/ae_mdw_web/router.ex, test/ae_mdw/db/model_test.exs, test/ae_mdw/db/sync/name_test.exs, test/support/ae_mdw/db/mutation_case.ex, test/support/test_util.ex
=> feat: add ability to roll back database on dev env

config/config.exs, docs/swagger_v3/dex.spec.yaml, lib/ae_mdw/dex.ex, test/ae_mdw_web/controllers/dex_controller_test.exs
refs: https://github.com/aeternity/ae_mdw/issues/1884
=> feat: add dex action field

lib/ae_mdw/oracles.ex, lib/ae_mdw_web/controllers/oracle_controller.ex, test/ae_mdw_web/controllers/oracle_controller_test.exs
=> fix: oracles v3 endpoint was returning v2 data

docs/swagger_v3/dex.spec.yaml, lib/ae_mdw/dex.ex, test/ae_mdw_web/controllers/dex_controller_test.exs
refs: https://github.com/aeternity/ae_mdw/issues/1901
=> fix: inconsistent micro time naming

docs/swagger_v3/activities.spec.yaml, lib/ae_mdw/activities.ex, lib/ae_mdw/dex.ex, lib/ae_mdw/sync/dex_cache.ex, test/ae_mdw_web/controllers/activities_controller_test.exs
refs: https://github.com/aeternity/ae_mdw/issues/1883
=> fix: activities pagination

docs/swagger_v3/blocks.spec.yaml, lib/ae_mdw/blocks.ex, test/ae_mdw/websocket/broadcaster_test.exs, test/ae_mdw_web/controllers/block_controller_test.exs
refs: https://github.com/aeternity/ae_mdw/issues/1887
=> feat: add beneficiary reward to key block response

lib/ae_mdw/db/contract.ex, priv/migrations/20240816120002_aex9_logs_count_reindex.ex
=> fix: specify right aex9 contract to count aex9 logs

.gitignore, Dockerfile, docs/swagger_v3/transactions.spec.yaml, scripts/do.sh, scripts/swagger-docs.py
=> feat: add node schemas to swagger definitions for mdw

docs/swagger_v3/names.spec.yaml, lib/ae_mdw/auction_bids.ex, lib/ae_mdw/names.ex, lib/ae_mdw_web/controllers/name_controller.ex, test/ae_mdw_web/controllers/name_controller_test.exs
=> feat: make auctions endpoints use name and hash

docs/swagger_v3/names.spec.yaml, lib/ae_mdw/auction_bids.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw/db/mutations/name_claim_mutation.ex, lib/ae_mdw/db/sync/name.ex, lib/ae_mdw/names.ex, priv/migrations/20240917120000_index_auctions_claims_count.ex, test/ae_mdw/db/name_claim_mutation_test.exs
=> feat: add claims count on names/auctions

lib/ae_mdw/stats.ex, test/ae_mdw/stats_test.exs, test/ae_mdw_web/controllers/stats_controller_test.exs
=> chore: rename minutes_per_block ot milliseconds_per_block

lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/mutations/block_statistics_mutation.ex, lib/ae_mdw/db/mutations/stats_mutation.ex, lib/ae_mdw/db/sync/stats.ex, lib/ae_mdw/db/util.ex, lib/ae_mdw/stats.ex, lib/ae_mdw_web/controllers/stats_controller.ex, lib/ae_mdw_web/router.ex, priv/migrations/20240827082222_add_aex9_transfer_statistics.ex, test/ae_mdw/db/contract_call_mutation_test.exs, test/ae_mdw/db/contract_test.exs
refs: https://github.com/aeternity/ae_mdw/issues/1896
=> feat: aex9 transfer statistics

lib/ae_mdw/accounts.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw/db/mutations/account_activity_mutation.ex, lib/ae_mdw/db/sync/stats.ex, lib/ae_mdw/stats.ex, lib/ae_mdw/sync/server.ex, lib/ae_mdw_web/controllers/stats_controller.ex, lib/ae_mdw_web/router.ex, priv/migrations/20241002115611_active_accounts_stats.ex, test/ae_mdw/db/mutations/account_activity_mutations_test.exs, test/ae_mdw_web/controllers/stats_controller_test.exs
refs: https://github.com/aeternity/ae_mdw/issues/1919
=> feat: add active accounts stats

docs/swagger_v3/base.yaml, docs/swagger_v3/transactions.spec.yaml
=> docs: update scope parameter of transactions endpoint

lib/ae_mdw_web/controllers/aexn_token_controller.ex
This fixes a bug on new chains (e.g. localnet setup for hyperchains).
=> fix: empty aexn count error

lib/ae_mdw/transfers.ex, test/integration/ae_mdw_web/controllers/transfer_controller_test.exs
=> fix: swapped fields in transfer render function

.credo.exs, lib/ae_mdw/activities.ex, lib/ae_mdw/txs.ex, lib/ae_mdw/validate.ex, lib/ae_mdw_web/plugs/paginated_plug.ex, test/ae_mdw_web/controllers/activities_controller_test.exs, test/ae_mdw_web/controllers/name_controller_test.exs, test/ae_mdw_web/controllers/oracle_controller_test.exs, test/ae_mdw_web/controllers/stats_controller_test.exs, test/ae_mdw_web/controllers/transfer_controller_test.exs, test/ae_mdw_web/plugs/paginated_plug_test.exs, test/integration/ae_mdw_web/controllers/aex9_controller_test.exs
=> feat: introduce now transaction hash range scoping

lib/ae_mdw/names.ex, test/ae_mdw_web/controllers/name_controller_test.exs
=> fix: make the claims endpoint return all claims instead of just from last auction

lib/ae_mdw/db/mutations/update_balance_accounts_mutation.ex, lib/ae_mdw/stats.ex, priv/migrations/20250320151835_add_holders_count.ex, test/ae_mdw/db/mutations/update_balance_account_mutation_test.exs, test/ae_mdw/stats_test.exs, test/ae_mdw_web/controllers/stats_controller_test.exs
=> feat: add holders count to stats endpoint
