.dockerignore, Dockerfile, Makefile, README.md, docker-compose.yml, docker/entrypoint.sh
This PR adds docker and describes how to quick-start project by using docker 
By default all of these ports are exposed:
4000 - MDW HTTP API endpoints port
4001 - MDW subscriptions websocket port
3013 - AE NODE external port
3113 - AE NODE internal port
3014 - AE NODE channel websocket port
Feedback and suggestions are always appreciated!
=> New improvements in dockerfile and docs

.gitignore, Makefile, mix.lock
This fix will make sure the version files are linked from ae_mdw directory when it's staring AE node.
So that the reply of:
```
$ curl -s "http://localhost:3013/v2/status" | jq '.'
```
has node_revision and node_version filled.
=> Link AE version files.

lib/ae_mdw_web/controllers/block_controller.ex, test/ae_mdw_web/controllers/block_controller_test.exs, test/support/conn_case.ex
Change controller of blocks endpoint to not read from cache the last 6 blocks.
The expiration of inserted blocks in the cache remains the same, based on `generations_cache_expiration_minutes` config. 
Issue [#194](https://github.com/aeternity/ae_mdw/issues/194)
https://mainnet.aeternity.art/mdw/blocks/444733-444733
https://mainnet.aeternity.io/mdw/blocks/444733-444733
count of microblocks is different
Once inserted in the cache, a block is only updated after the expiration.
The list comprehension with `reduce` was replaced with `into` as it's a little faster and saves memory (around 50% according benchee).
fixes #194
=> fix: don't read from cache the last 6 blocks

lib/ae_mdw_web/controllers/aex9_controller.ex, test/ae_mdw_web/controllers/aex9_controller_test.exs
This was found using dialyzer, and was causing the AEX9 balance endpoints to return a 500 error.
=> fix: adjust tuple structure sent on AEX9 balances endpoints

lib/mix/tasks/backup_db_table.ex, lib/mix/tasks/restore_db_table.ex, test/mix/tasks/tasks_test.exs
Mix tasks to backup and restore a single db table.
Database is too big to be backed up. 
This is a task to help with development and bugfix of issues involving one or more mnesia table states.
elixir --sname aeternity@localhost -S mix test test/mix/tasks/tasks_test.exs`
pick randomly other two tables from Model.tables() to run:
`mix backup_db_table [table_module]`
`mix restore_db_table [table_module]`
Avoids just copying the table directory to be implementation independent (state completly controlled by mnesia and mnesia backend).
=> feat: backup and restore db table

lib/ae_mdw_web/controllers/tx_controller.ex, test/ae_mdw_web/controllers/block_controller_test.exs, test/ae_mdw_web/controllers/name_controller_test.exs, test/ae_mdw_web/controllers/oracle_controller_test.exs, test/ae_mdw_web/controllers/util_controller_test.exs
Fixes some integration test cases.
Tests not passing with middleware synced:
test txi renders errors when data is not found (AeMdwWeb.TxControllerTest)
test pointers renders error when the name is missing (AeMdwWeb.NameControllerTest)
test name renders error when no such name is present (AeMdwWeb.NameControllerTest)
test pointers get pointers for valid given name (AeMdwWeb.NameControllerTest)
test blocki renders error when mickro block index is not present (AeMdwWeb.BlockControllerTest)
test status get middleware status (AeMdwWeb.UtilControllerTest)
There is 1 remaining in OracleControllerTest related to side effects. 
```
1) test active_oracles renders error when the access is random  (AeMdwWeb.OracleControllerTest)
test/ae_mdw_web/controllers/oracle_controller_test.exs:408
** …
```
=> test: small integration tests updates

.github/workflows/test-action.yml, Dockerfile, test/test_helper.exs
This avoids the core to start syncing and causing issues while simultaneously runing tests.
=> test: use specific docker image version of Elixir

.github/workflows/test-action.yml, lib/ae_mdw/db/name.ex, lib/ae_mdw/log.ex, lib/ae_mdw_web/cont.ex, lib/ae_mdw_web/controllers/tx_controller.ex, mix.exs, test/integration/ae_mdw_web/controllers/tx_controller_test.exs
Adds some details to /txs/forward and /txs/backward endpoints when using account as querystring param.
The details are account and recipient chain name.
Note: As the names have expiration and might be tranfered, the recipient account is the owner of the name at the time of the transaction.
Extra info/fixes #226 
```
elixir --sname aeternity@localhost -S mix test.integration test/integration/ae_mdw_web/controllers/tx_controller_test.exs:583
elixir --sname aeternity@localhost -S mix test.integration test/integration/ae_mdw_web/controllers/tx_controller_test.exs:661
elixir --sname aeternity@localhost -S mix test.integration test/integration/ae_mdw_web/controllers/tx_controller_test.exs 
```
=> feat: adds account and recipient name to spendtx

mix.exs, test/ae_mdw_web/controllers/block_controller_test.exs, test/support/blockchain_sim.ex
This is a temprary experimental approach to remove the synced blockchain requirement for running tests. In the near future, once the devmode is enabled, we can turn this DSL into something more imperative (a Ganache-like approach).
This is an alternative to mocking on every test (e.g. https://github.com/aeternity/ae_mdw/commit/2bd691696db3224c6f0ab0799eff5b340203a442)
Refs #220
=> test: add blockchain DSL for testing purposes

lib/ae_mdw/db/model.ex, lib/ae_mdw/db/setup.ex, lib/mix/tasks/migrate_db.ex, priv/migrations/20210826171900_reindex_remote_logs.ex
Ecto-like database migration automation.
Issue #193
Avoids running migrations twice and saves the state to follow the changes in db structure and data.
1. `make shell`
2. `mix migrate_db`
This migration is expected to be applied:
```
10:57:54.933 [info]  applying version 20210826171900 with Elixir.AeMdw.Migrations.ReindexRemoteLogs...
table size: 177072
Indexed 32142 records in 62s
10:58:56.870 [info]  applied version 20210826171900
```
3. `mix migrate_db`
Migration is already is last version:
```
11:00:05.639 [info]  current migration version: 20210826171900
11:00:05.656 [info]  migrations are up to date
```
4. Create a new migration at priv/migrations/20210826171902_new .ex with:
```
defmodule AeMdw.Migrations.New do
def run(), do: {:ok, nil}
end
```
5. `mix migrate_db`
It applies the …
=> database: automate migration

lib/ae_mdw/db/name.ex, lib/ae_mdw_web/controllers/tx_controller.ex, test/integration/ae_mdw_web/controllers/tx_controller_test.exs
Replace name transfer search with update search. 
When the recipient id is an AENS id name (`nm_...`), the recipient account is the pointee of the name (if name have one). 
Fixes #226 
The recipient of the name used might not be owner of the name, or in other words, the name might point to an account different from the owner.
```
elixir --sname aeternity@localhost -S mix test.integration test/integration/ae_mdw_web/controllers/tx_controller_test.exs:582
elixir --sname aeternity@localhost -S mix test.integration test/integration/ae_mdw_web/controllers/tx_controller_test.exs
```
=> fix: recipient account is the pointee if name have one

lib/ae_mdw/mnesia.ex, lib/ae_mdw/oracles.ex, lib/ae_mdw_web/controllers/oracle_controller.ex, lib/ae_mdw_web/plugs/paginated_plug.ex, lib/ae_mdw_web/router.ex, test/ae_mdw_web/controllers/oracle_controller_test.exs, test/integration/ae_mdw_web/controllers/oracle_controller_test.exs, test/support/test_sample.ex
Because we're having problems before with dealing with instance state by using ETS to store the remaining streams, a substantial change was necessary to both get rid of streams and to simplify the way the MDW works by using a more encapsulated and layered coding style.
Changes introduced:
1. **Refactor MDW domain logic to use a layered coding style.**
Before this change, there weren't really any layers, the `AeMdw`, `AeMdwWeb` and `AeMdwWeb.Db` modules went back and forth calling each other out.
Now, the layer model consists of the following:
1. `AeMdwWeb.<Resource>Controller` (e.g. `OracleController`) only deals with getting the request params and displaying the returned data properly.
2. `AeMdw.<Resource>` (e.g. Oracles) deals with all of the logic related to oracles, which right now …
=> feat: restructure ETS stateful DB streams implementation

test/ae_mdw_web/controllers/name_controller_test.exs
Didn't need to use `with_blockchain/2` because the NameController exclusively depends on the mdw database.
Refs #220
=> test: update NameController tests to be unit tests

lib/ae_mdw_web/util.ex
Makes the path of pagination's `next` start with "/".
Fixes #182
htp url path is like that too.
`make test-integration`
=> chore: prepend slash to pagination next

bench/ae_mdw_web/oracle_controller_bench.exs, lib/ae_mdw/mnesia.ex, lib/ae_mdw/oracles.ex, lib/ae_mdw_web/controllers/oracle_controller.ex, lib/ae_mdw_web/plugs/paginated_plug.ex, lib/ae_mdw_web/router.ex, test/ae_mdw_web/controllers/oracle_controller_test.exs, test/integration/ae_mdw_web/controllers/oracle_controller_test.exs
Output from benchmarks (pretty similar to active/inactive output):
```
Name                 ips        average  deviation         median         99th %
oracles_v2         19.89       50.27 ms     ±8.09%       49.80 ms       74.77 ms
oracles            18.40       54.35 ms     ±9.09%       53.14 ms       71.95 ms
Comparison: 
oracles_v2         19.89
oracles            18.40 - 1.08x slower +4.09 ms
Memory usage statistics:
Name               average  deviation         median         99th %
oracles_v2       672.86 KB     ±0.10%      672.62 KB      674.34 KB
oracles          767.22 KB     ±0.09%      767.46 KB      767.57 KB
Comparison: 
oracles_v2       672.62 KB
oracles          767.22 KB - 1.14x memory usage +94.36 KB
```
This is the commit that needs to be checked out to run these …
=> feat: add oracles v2 endpoint without making use of streams

lib/ae_mdw/auction_bids.ex, lib/ae_mdw/collection.ex, lib/ae_mdw/mnesia.ex, lib/ae_mdw/names.ex, lib/ae_mdw/oracles.ex, lib/ae_mdw/txs.ex, lib/ae_mdw_web/controllers/name_controller.ex, lib/ae_mdw_web/plugs/paginated_plug.ex, test/ae_mdw_web/controllers/name_controller_test.exs, test/integration/ae_mdw_web/controllers/name_controller_test.exs, test/support/test_sample.ex
This includes `/names`, `/names/active`, `/names/inactive` endpoints.
=> refactor: add paginated name endpoints without making use of streams

lib/ae_mdw/contract.ex, lib/ae_mdw/db/format.ex, test/integration/ae_mdw_web/controllers/tx_controller_test.exs
Adds `gas_used` (snake case like other fields) on tx_controller response for `:contract_create_tx`.
Fixes #197 
Create tx is referred  as `InitCall` and fetched likewise:
https://github.com/aeternity/aeternity/blob/417774bdddd9ff46a057975f3bbbb8eb8d96d8ff/apps/aecontract/test/aecontract_SUITE.erl#L1018 (used here)
https://github.com/aeternity/aeternity/blob/417774bdddd9ff46a057975f3bbbb8eb8d96d8ff/apps/aecontract/test/aecontract_SUITE.erl#L994 (with InitCallId encoded here)
https://github.com/aeternity/aeternity/blob/417774bdddd9ff46a057975f3bbbb8eb8d96d8ff/apps/aecontract/test/aecontract_SUITE.erl#L985 (from the `create_tx` for a tx that is accessed with `aect_create_tx`)
=> feat: add gas_used to create contract tx info

lib/ae_mdw/application.ex, mix.exs, mix.lock
In this new version of aecore (6.3.0) both the :app_ctrl_server process are required for aecore to start syncing and to respond to
functions such as `:asc_sync.sync_progress()`.
This is rather hack-ish, but I don't know why none of these things are started when aecore starts.
closes #275
=> fix: start :aesync and :app_ctrl_server when initializing app

lib/ae_mdw/application.ex
Without setting this mode, the :app_ctrl app won't start the aesync app which will do all the node syncing.
=> fix: set :app_ctrl mode to :normal to allow MDW to sync

lib/ae_mdw_web/controllers/tx_controller.ex, test/integration/ae_mdw_web/controllers/tx_controller_test.exs
Add recipient details also for `/txi` and `/tx` endpoints.
Fixes #316 
Case:
`elixir --sname aeternity@localhost -S mix test.integration test/integration/ae_mdw_web/controllers/tx_controller_test.exs`
Regression:
`elixir --sname aeternity@localhost -S mix test.integration test/integration/ae_mdw_web/controllers/tx_controller_test.exs`
=> feat: add recipient details for /tx and /txi

lib/ae_mdw/db/util.ex, lib/ae_mdw_web/controllers/name_controller.ex, lib/ae_mdw_web/plugs/paginated_plug.ex, test/ae_mdw_web/controllers/name_controller_test.exs, test/ae_mdw_web/controllers/oracle_controller_test.exs, test/integration/ae_mdw_web/controllers/name_controller_test.exs, test/integration/ae_mdw_web/controllers/oracle_controller_test.exs
This is a preamble to the scope handling of all newly paginated
resources. Ultimately, to get rid of the DataStreamPlug and all the
stream_plug_hook functions from the controllers.
=> refactor: add :scope, :query and :offset to Conn.assigns

priv/migrations/20210826171900_reindex_remote_logs.ex, priv/migrations/20210914100800_index_inner_txs.ex, priv/migrations/20210921123001_index_aex9_account_presence.ex
Adds 1 minute timeout to aex9 balance and saves the contract to be handled separately (in a dets/temporary table).
Migration was taking more than 10 minutes (sometimes 20 min) because of two very big contracts. 
This change avoids the Mdw (testnet and mainnet) to be out of sync for so long time.
Total time reduced:
Contracts saved:
=> feat: aex9 migration balance timeout

lib/ae_mdw/db/sync/name.ex
Validates name expiration before applying it.
Fixes #338 (as discussed, the plan is to use more the Node db if possible, otherwise the root cause will be investigated on mnesia rocksdb layer if reproduced after mutations refactor).
Protects against:
```
iex(aeternity@localhost)9> :mnesia.dirty_select(Model.InactiveNameExpiration, Ex2ms.fun do {:expiration, {height, "filestorm.chain"}, :_} -> height end)
[419848]
iex(aeternity@localhost)10> [Model.name(expire: exp)] = :mnesia.dirty_read(Model.InactiveName, "filestorm.chain"); exp
449221                        
iex(aeternity@localhost)11> {mdw_height, _mbi} = Util.last_txi() |> Util.read_tx!() |> Model.tx(:block_index)       
{422890, 9}
```
PS: The Node does not allow a double name claim and the `update` tx handling already deletes the …
=> fix: validate name expiration

.github/workflows/test-action.yml, lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/sync/contract.ex, lib/ae_mdw/sync/async_tasks/consumer.ex, lib/ae_mdw/sync/async_tasks/derive_aex9_presence.ex, lib/ae_mdw/sync/async_tasks/store.ex, lib/ae_mdw/sync/supervisor.ex
Async processing for the `Sync.Contract.aex9_derive_account_presence!/1`.
Synchronous aex9 balances makes mdw database sync slower. 
It helps with #346
=> feat: async derive_aex9_presence

.github/workflows/test-action.yml, lib/ae_mdw/contract.ex, lib/ae_mdw/db/sync/contract.ex
Handles error for contract init info when `contract_create_tx` is on chain but the contract is not in chain db because its `init` has failed.
Fix for http://localhost:4000/txs/backward?limit=100&type=contract_create
=> fix: contract might not be present

lib/ae_mdw/names.ex
Removes unexisting auction fields to render inactive names.
Fixes http://localhost:4000/names/inactive
=> fix: inactive names auction rendering

.github/workflows/test-action.yml, lib/ae_mdw/blocks.ex, lib/ae_mdw/contract.ex, lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw/db/mutation.ex, lib/ae_mdw/db/mutations/aex9_account_presence_mutation.ex, lib/ae_mdw/db/mutations/contract_events_mutation.ex, lib/ae_mdw/db/mutations/mnesia_write_mutation.ex, lib/ae_mdw/db/mutations/write_fields_mutation.ex, lib/ae_mdw/db/mutations/write_links_mutation.ex, lib/ae_mdw/db/mutations/write_tx_mutation.ex, lib/ae_mdw/db/sync/contract.ex, lib/ae_mdw/db/sync/transaction.ex, lib/ae_mdw/mnesia.ex, lib/ae_mdw/node.ex, lib/ae_mdw/txs.ex, priv/migrations/20210914100800_index_inner_txs.ex, test/ae_mdw/db/sync/transaction_test.exs
The goal of this change is to be able to isolate mnesia updates into
mutations which will all be ran in a single transaction and in the
least amount of time possible.
By making first-class mutations we can also debug easily what changes
any given block or transaction makes.
This also fixes random errors that come up inside mnesia transactions:
mnesia transactions do not work properly when exceptions are thrown
inside them, even if they are captured.
closes #331
=> feat: add mutations abstraction to deal with mnesia updates

lib/ae_mdw/db/sync/oracle.ex
Removes oracle expiration also when it's not the current one.
Fixes #351 and #352
After removing with:
```
iex(aeternity@localhost)1> oracles_exp = :mnesia.dirty_select(Model.ActiveOracle, Ex2ms.fun do record -> record end) |> Enum.map(fn Model.oracle(index: pubkey, expire: expire) -> {expire, pubkey} end)
iex(aeternity@localhost)2> Enum.all?(oracles_exp, fn m_exp -> :mnesia.dirty_read(Model.ActiveOracleExpiration, m_exp) != [] end)
true
iex(aeternity@localhost)5> old_exps = Enum.flat_map(oracles_exp, fn {expire, pubkey} -> :mnesia.dirty_select(Model.ActiveOracleExpiration, Ex2ms.fun do {:expiration, {height, ^pubkey}, :_} when height != ^expire -> {height, ^expire, ^pubkey} end) end)
[
{465432, 520448,
<<7, 114, 231, 19, 221, 34, 106, 119, 80, 6, 115, 204, 54, 130, 94, 0, 63,
242, 128, …
```
=> fix: remove old oracle expiration

lib/ae_mdw/auction_bids.ex, lib/ae_mdw/db/format.ex, lib/ae_mdw/db/name.ex, lib/ae_mdw/db/sync/name.ex, lib/ae_mdw/names.ex, lib/ae_mdw_web/controllers/transfer_controller.ex, test/ae_mdw_web/controllers/name_controller_test.exs, test/integration/ae_mdw_web/controllers/name_controller_test.exs
Adds to auction `last_bid` object the expiration height of a name that is set after its auction (future expiration when the name becomes active).
Fixes #354   
`elixir --sname aeternity@localhost -S mix test.integration test/integration/ae_mdw_web/controllers/name_controller_test.exs`
=> fix: add name ttl to last_bid tx

lib/ae_mdw_web/websocket/broadcaster.ex
Fixes encoding of binary tx fields for new and old websocket broadcasting (source = mdw or node).
Fixes #330
```
defmodule EncodeTx do
alias AeMdw.Db.Model
require Model
def exec(height) do
{_key_block, micro_blocks} = AeMdw.Node.Db.get_blocks(height)
micro_blocks
|> Enum.with_index()
|> Enum.map(fn {mblock, mbi} ->
header = :aec_blocks.to_header(mblock)
:aec_blocks.txs(mblock)
|> Enum.each(fn signed_tx ->
serialized = header |> :aetx_sign.serialize_for_client(signed_tx)
serialized
|> encode_message("Transactions", "mdw") 
|> case do 
{:ok, _} -> :noop
{:error, error} ->
IO.inspect serialized 
IO.inspect error
end
end)
end)
end
defp encode_message(payload, "Transactions", source),
do: Poison.encode(%{"payload" => encode_payload(payload), "subscription" => "Transactions", "source" => …
```
=> fix: binary encoding for websocket broadcasting

lib/ae_mdw/db/int_transfer.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw/transfers.ex, priv/migrations/20211124092400_reindex_int_transfers_acc_index.ex, test/integration/ae_mdw_web/controllers/transfer_controller_test.exs
Right now, the `TargetIntTransferTx` mnesia table is indexed by `{account_pk, gen_txi, kind, ref_txi}`. This doesn't allow to filter by both account and kind with results sorted by gen_txi.
Instead, the new index created on this migration, named `TargetKindIntTransferTx`, will have `{account_pk, kind, gen_txi, ref_txi}` as a key, which allows to filter by both account and kind on a given range.
refs #359
=> fix: reindex transfers to be able to filter by account + kind

lib/ae_mdw/db/oracle.ex
Fixing an error due to a rebase with master
=> fix: add missing aliases on the Db.Oracle module

lib/ae_mdw/db/name.ex
Removes cleanup name expiration code that slows down the sync with a full search. 
This recent validation already protects from old expirations:
https://github.com/aeternity/ae_mdw/blob/72c500109cfb15afb11a17fdaafe7ef920d5a5a5/lib/ae_mdw/db/name.ex#L68
=> chore: remove name expiration cleanup

lib/ae_mdw/blocks.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw/db/mutations/write_links_mutation.ex, lib/ae_mdw/db/sync/contract.ex, lib/ae_mdw/db/sync/transaction.ex, priv/migrations/20210914100800_index_inner_txs.ex, test/ae_mdw/db/sync/transaction_test.exs, test/support/blockchain_sim.ex
For some of the generations whose microblocks have lots of contract call transactions in them, this reduces processing time by 50%
refs #346
=> perf: avoid loading mbs when processing contract call txs

lib/ae_mdw/stats.ex
Use last synced height as last gen for `/stats` and `/totalstats`
Doing multiple requests some fail because the blocks might not be synced yet.
=> fix: use last synced gen for stats and totalstats

lib/ae_mdw/db/int_transfer.ex, lib/ae_mdw/db/mutations/stats_mutation.ex, lib/ae_mdw/db/sync/stats.ex, lib/ae_mdw/db/sync/transaction.ex
Calculates the stats using database info when sync is resumed not from the first microblock of the generation.
In this case the cache doesn't have data from the microblocks that were already synced (only in the first `AeMdw.Db.Sync.Transaction.sync_generation` call).
Base branch for #390 (transactions per microblock) requires this change to save stats properly. 
@thepiwo @sborrazas Feel free to merge this if you prefer to review this together with base branch code.
=> feat: read stats from db when resuming mb sync

lib/ae_mdw/db/name.ex, lib/ae_mdw/db/oracle.ex
Using `dirty_select` might return incorrect results, since there are
no mnesia guarantees when using `dirty_select`.
=> fix: build expiring mutation using mnesia transaction

lib/ae_mdw/db/mutations/stats_mutation.ex, lib/ae_mdw/db/sync/transaction.ex
Fixes `{:error, :chain_too_short}` race condition when syncing the first generation.
`max_height` is set to `height` (0) + 1 and when `:aec_chain.get_key_header_by_height(1)` is called the generation is not yet synced returning `{:error, :chain_too_short}`.
```
{{badmatch,{error,chain_too_short}},[{'Elixir.AeMdw.Db.Sync.BlockIndex',sync,1,[{file,"lib/ae_mdw/db/sync/block_index.ex"},{line,23}]},{'Elixir.AeMdw.Db.Sync.Transaction',sync,1,[{file,"lib/ae_mdw/db/sync/transaction.ex"},{line,42}]},{'Elixir.AeMdw.Db.Sync.ChainSubscriber',run_action,1,[{file,"lib/ae_mdw/db/sync/chain_subscriber.ex"},{line,94}]}]}
```
=> fix: chain_too_short condition when syncing height 0

lib/ae_mdw/transfers.ex
This avoids the error generated for accounts containing the `$`
character, which is used for splitting the cursor.
=> fix: base32 encode account cursor on transfers

.github/workflows/test-action.yml, lib/ae_mdw/db/int_transfer.ex, lib/ae_mdw/db/mutations/stats_mutation.ex, lib/ae_mdw/db/sync/stats.ex, lib/ae_mdw/db/sync/transaction.ex, lib/ae_mdw/sync/async_tasks/producer.ex
Commits sync changes per micro block.
Mnesia transaction log is not being fully committed.
Contribute to #387
Contribute to #396 
This paves the way to make instant syncs of AEX9 txs #211. Not sufficient but one step forward to the next step of having syncs per transaction.
=> feat: db transactions per microblock

.github/workflows/test-action.yml, test/integration/ae_mdw_web/controllers/name_controller_test.exs
The purpose of this is to test pagination properly, with the added
benefi that many of the tests would fail when there's name
inconsistencies in the DB.
=> test: refactor name controller integration tests

test/integration/ae_mdw/sync/oracle_test.exs, test/integration/ae_mdw_web/controllers/tx_controller_test.exs
@jyeshe what do you think about moving these `sync/oracle_test.exs` tests to unit tests instead?
=> test: fix oracles and tx_controller integration tests

.github/workflows/test-action.yml, test/integration/ae_mdw_web/controllers/name_controller_test.exs, test/integration/ae_mdw_web/controllers/oracle_controller_test.exs
The purpose of this is to test pagination properly, with the added
benefit that many of the tests would fail when there's name
inconsistencies.
Requires #421 to be merged first.
=> test: restructure oracles integration tests

lib/ae_mdw/contracts.ex
closes #422
This issue needs further work: right now you can't filter calls/logs of contracts that have no create transaction.
=> fix: validate existing contract when filtering calls by contract_id

lib/ae_mdw/db/int_transfer.ex, lib/ae_mdw/db/sync/stats.ex, test/integration/ae_mdw/sync/stats_test.exs, test/integration/ae_mdw_web/controllers/stats_controller_test.exs
- replace `:mnesia.table_info` with `Util.count` to get correct number of existing objects/entries.
- fix select of internal transfers rewards by kind
fix #453 
refs #450 
`elixir --sname aeternity@localhost -S mix test.integration test/integration/ae_mdw/sync/stats_test.exs`
=> fix: stats count for existing objects

lib/ae_mdw/db/format.ex, mix.exs
This is because core serialization doesn't return the query_id by
default: https://github.com/aeternity/aeternity/blob/master/apps/aeoracle/src/aeo_query_tx.erl#L254
ref #381
ref #60
=> feat: add encoded query_id on query txs

lib/ae_mdw/contract.ex, lib/ae_mdw/db/sync/invalidate.ex, lib/ae_mdw/db/sync/transaction.ex, test/integration/ae_mdw_web/controllers/tx_controller_test.exs
Adds `compiler_version` and `source_hash` to `/txs` response when the tx is a `:contract_create_tx`.
Resolves #341
`elixir --sname aeternity@localhost -S mix test.integration test/integration/ae_mdw_web/controllers/tx_controller_test.exs:79`
`elixir --sname aeternity@localhost -S mix test.integration test/integration/ae_mdw_web/controllers/tx_controller_test.exs:302`
`elixir --sname aeternity@localhost -S mix test.integration test/integration/ae_mdw_web/controllers/tx_controller_test.exs`
=> feat: contract compilation info

lib/ae_mdw/blocks.ex, lib/ae_mdw/db/format.ex, lib/ae_mdw/db/oracle.ex, lib/ae_mdw/db/sync/transaction.ex, lib/ae_mdw/oracles.ex, test/ae_mdw_web/controllers/oracle_controller_test.exs
This was causing an error when the oracle register transaction was on
the same micro block as the oracle response transaction, because the
micro block was not found until the transaction was executed.
=> fix: avoid loading block_hash for building oracle tree when syncing

lib/ae_mdw/db/contract.ex, lib/ae_mdw/sync/async_tasks/consumer.ex, lib/ae_mdw/sync/async_tasks/producer.ex, lib/ae_mdw/sync/async_tasks/store.ex, test/ae_mdw/sync/async_tasks/store_test.exs, test/integration/ae_mdw/sync/async_tasks/producer_consumer_test.exs
Indexes the async tasks by task type and `args` (these two attributes define the work to be peformed).
Currently, for lower volume of `UpdateAex9Presence` and `DeriveAex9Presence`, the task `args` (e.g `contract_pk`) is used to check if an async task already exists to avoid duplicate processing. However, the task `args` is not a key/index for async tasks.
With #437 and DEX, the volume of async tasks will increase justifying another index (in memory only).
PS: The current async task index is used for ordering to avoid task processing starvation.
`elixir --sname aeternity@localhost -S mix test.integration test/integration/ae_mdw/sync/async_tasks/producer_consumer_test.exs`
=> perf: async task type and args as a key

README.md, lib/ae_mdw/db/model.ex, lib/ae_mdw/db/name.ex, lib/ae_mdw_web/controllers/name_controller.ex, priv/migrations/20220113112001_inactive_name_owner.ex, test/ae_mdw_web/controllers/name_controller_test.exs, test/integration/ae_mdw_web/controllers/name_controller_test.exs
Add/handle `active` parameter on `/name/owned_by` to return active or inactive names (last ownership of expired or revoked names).
Resolves #157 
`elixir --sname aeternity@localhost -S mix test.integration test/integration/ae_mdw_web/controllers/name_controller_test.exs:544`
`elixir --sname aeternity@localhost -S mix test.integration test/integration/ae_mdw_web/controllers/name_controller_test.exs`
=> feat: /names/owned_by for inactive names

lib/ae_mdw/db/sync/contract.ex, test/ae_mdw/db/sync/contract_test.exs
I hadn't realized back then, but the Chain.create and Chain.clone
events don't have a valid trasaction associated to them in the event
map info.
=> fix: skip processing internal calls for Chain.* events

config/config.exs, lib/ae_mdw/log.ex, priv/migrations/20211124092400_reindex_int_transfers_acc_index.ex
- removes log/sync.log because all info is present in log/info.log
- increases Logger threshold to enter in synchronous mode (when it slows down mdw sync process)
=> perf: remove duplicate logging

lib/ae_mdw/db/mutations/name_claim_mutation.ex, lib/ae_mdw/db/mutations/name_transfer_mutation.ex, lib/ae_mdw/db/mutations/name_update_mutation.ex, lib/ae_mdw/db/mutations/write_field_mutation.ex, lib/ae_mdw/db/name.ex, lib/ae_mdw/db/sync/contract.ex, lib/ae_mdw/db/sync/name.ex, lib/ae_mdw/db/sync/origin.ex, lib/ae_mdw/db/sync/transaction.ex, lib/ae_mdw/log.ex, test/integration/ae_mdw/db/sync/contract_test.exs, test/integration/ae_mdw_web/controllers/name_controller_test.exs
Resolves #408
`elixir --sname aeternity@localhost -S mix test.integration test/integration/ae_mdw/db/sync/contract_test.exs`
Note: Please notice that name internal calls cannot be migrated because the effect of every operation depends on the state of the name at the microblock that it happened. It cannot neither be discard if old because name record tracks a history of all operations. For these reasons this feature requires a **full sync**.
=> feat: index AENS internal calls

lib/ae_mdw/db/util.ex, test/ae_mdw/sync/async_tasks/stats_test.exs
Changes table count to use the number of keys.
Solves this test timeout and the alternative of `:mnesia.table_info` returns 0 after starting the Mdw:
```
1) test new_mutation/2 with all_cached? = false and 1 block reward (Integration.AeMdw.Db.Sync.StatsTest)
test/integration/ae_mdw/sync/stats_test.exs:16
** (ExUnit.TimeoutError) test timed out after 60000ms. You can change the timeout:
```
`elixir --sname aeternity@localhost -S mix test.integration test/integration/ae_mdw/sync/stats_test.exs:16`
=> perf: mnesia table count based on keys

lib/ae_mdw/db/mutations/name_update_mutation.ex, lib/ae_mdw/db/sync/contract.ex, lib/ae_mdw/db/sync/name.ex
Don't expire a name on update with `name_ttl` = 0 after `AENS.update` internall call.
Fixes #490 
PS: The contract call with the AENS.update internal call has succeeded. 
https://mainnet.aeternity.io/mdw/txi/23198023
=> fix: name expiration after aens.update with name_ttl = 0

README.md, lib/ae_mdw_web/controllers/block_controller.ex, lib/ae_mdw_web/controllers/tx_controller.ex, lib/ae_mdw_web/router.ex, test/integration/ae_mdw_web/controllers/name_controller_test.exs, test/integration/ae_mdw_web/controllers/oracle_controller_test.exs
From now on, all new routes should be added only to the latest
version, which will be released at some point in the future.
Older routes will be announced for deprecation and deprecated
accordingly.
Refs #498
=> feat: add /v2 routes to support versioning

README.md, lib/ae_mdw/auction_bids.ex, lib/ae_mdw/names.ex, lib/ae_mdw_web/controllers/name_controller.ex, lib/ae_mdw_web/router.ex, test/integration/ae_mdw_web/controllers/name_controller_test.exs
Previously, this endpoint returned all results that matched on a
single page, potentially causing security concerns.
=> feat: add paginated /names/search/:prefix endpoint

lib/ae_mdw/db/mutation.ex, lib/ae_mdw/db/mutations/aex9_account_presence_mutation.ex, lib/ae_mdw/db/mutations/block_rewards_mutation.ex, lib/ae_mdw/db/mutations/contract_call_mutation.ex, lib/ae_mdw/db/mutations/contract_create_mutation.ex, lib/ae_mdw/db/mutations/key_blocks_mutation.ex, lib/ae_mdw/db/mutations/name_claim_mutation.ex, lib/ae_mdw/db/mutations/name_revoke_mutation.ex, lib/ae_mdw/db/mutations/name_transfer_mutation.ex, lib/ae_mdw/db/mutations/name_update_mutation.ex, lib/ae_mdw/db/mutations/names_expiration_mutation.ex, lib/ae_mdw/db/mutations/oracle_extend_mutation.ex, lib/ae_mdw/db/mutations/oracle_register_mutation.ex, lib/ae_mdw/db/mutations/oracle_response_mutation.ex, lib/ae_mdw/db/mutations/oracles_expiration_mutation.ex, lib/ae_mdw/db/mutations/stats_mutation.ex, lib/ae_mdw/db/mutations/write_field_mutation.ex, lib/ae_mdw/db/mutations/write_fields_mutation.ex, lib/ae_mdw/db/mutations/write_mutation.ex, lib/ae_mdw/db/mutations/write_txn_mutation.ex, lib/ae_mdw/db/txn_mutation.ex
Make declarative implementations for the `Mutation` and `TxnMutation` protocols to simplify the transition to transaction mutations when it's resumed.
Resync and see that these endpoints work for height 10k:
http://localhost:4000/blocks/forward
http://localhost:4000/txs/forward
http://localhost:4000/names
=> refactor: mutations derive to default impl

lib/ae_mdw/db/format.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw/db/mutations/contract_create_mutation.ex, lib/ae_mdw/db/mutations/name_claim_mutation.ex, lib/ae_mdw/db/mutations/oracle_register_mutation.ex, lib/ae_mdw/db/mutations/stats_mutation.ex, lib/ae_mdw/db/name.ex, lib/ae_mdw/db/oracle.ex, lib/ae_mdw/db/origin.ex, lib/ae_mdw/db/sync/contract.ex, lib/ae_mdw/db/sync/invalidate.ex, lib/ae_mdw/db/sync/name.ex, lib/ae_mdw/db/sync/stats.ex, lib/ae_mdw/db/sync/transaction.ex, lib/ae_mdw/stats.ex, lib/ae_mdw_web/controllers/stats_controller.ex, lib/ae_mdw_web/router.ex, priv/migrations/20211220163202_index_ga_attach_txs.ex, test/ae_mdw/db/rocksdbcf_test.exs, test/integration/ae_mdw/sync/stats_test.exs, test/integration/ae_mdw_web/controllers/stats_controller_test.exs, test/test_helper.exs
Adds `/v2/deltastats` which contains object state transition counters (as per request `names_revoked` was added to give a reason for inactivation). 
refs #557 
```
INTEGRATION_TEST=1 elixir --sname aeternity@localhost -S mix test.integration  test/integration/ae_mdw/sync/stats_test.exs
INTEGRATION_TEST=1 elixir --sname aeternity@localhost -S mix test.integration  test/integration/ae_mdw_web/controllers/stats_controller_test.exs 
```
Optionally #562 can be merged to this branch to review altogether.
=> feat: /v2/deltastats

lib/ae_mdw_web/controllers/name_controller.ex
All operations naming should be consistent with each other and should
include the name of the resource being returned by the endpoint.
Refs #179
=> chore: rename name endpoints swagger operation ids

lib/ae_mdw/aex9.ex, lib/ae_mdw/contract.ex, lib/ae_mdw/database.ex, lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw/db/mutations/aex9_account_balance_mutation.ex, lib/ae_mdw/db/mutations/contract_call_mutation.ex, lib/ae_mdw/db/rocksdb.ex, lib/ae_mdw/db/rocksdb_cf.ex, lib/ae_mdw/db/sync/transaction.ex, lib/ae_mdw/error.ex, lib/ae_mdw/sync/async_tasks/derive_aex9_presence.ex, lib/ae_mdw/sync/async_tasks/update_aex9_presence.ex, lib/ae_mdw_web/controllers/aex9_controller.ex, priv/migrations/manual/20220304114500_rocksdb_txs_blocks.ex, test/ae_mdw/db/aex9_balance_mutation_text.exs, test/ae_mdw/db/rocksdb_test.exs, test/ae_mdw/db/rocksdbcf_test.exs, test/integration/ae_mdw_web/controllers/aex9_controller_test.exs
Persists aex9 balances to improve `/aex9/balances/:contract_id` availability (and consequently general mdw availability).
Solves #295 
1. Run an async task for a big contract:
```
alias AeMdw.Sync.AsyncTasks.Producer
Producer.enqueue(:update_aex9_presence, [AeMdw.Validate.id!("ct_BwJcRRa7jTAvkpzc2D16tJzHMGCJurtJMUBtyyfGi2QjPuMVv")])
Producer.commit_enqueued()
```
2. Wait for long async task to finish (following the clear logs) and make the request to the endpoint:
http://localhost:4000/aex9/balances/ct_BwJcRRa7jTAvkpzc2D16tJzHMGCJurtJMUBtyyfGi2QjPuMVv
```
INTEGRATION_TEST=1 elixir --sname aeternity@localhost -S mix test.integration  test/integration/ae_mdw_web/controllers/aex9_controller_test.exs:222
Finished in 7.5 seconds
24 tests, 0 failures, 23 excluded
elixir --sname …
```
=> feat: cached aex9 balances

lib/ae_mdw/database.ex, lib/ae_mdw/db/model.ex, lib/mix/tasks/migrate_db.ex, priv/migrations/manual/20220304114500_rocksdb_txs_blocks.ex
Fixes #482 and references #529 
1. Start the sync in one machine and let it run for 5 minutes.
2. Stop the mdw and copy the databases to other machine:
vps1: `tar zcvf database.tgz ../aeternity/_build/local/rel/aeternity/data/{mnesia/,mdw.db/}`
vps1:`scp database.tgz user@host:~` 
vps2: `rm -rf ${NODEROOT}/_build/local/rel/aeternity/data/{mnesia/,mdw.db/}` 
vps2: `tar xvf ~/database.tgz -C ../${NODEROOT}` 
3. Start the mdw on vps2 and check the log:
`grep "migrations are up to date" log/info.log`
=> refactor: migrations with rocksdb

lib/ae_mdw/application.ex
Removes initialization of total stat on height 0 during `Application.start`
Already performed by `AeMdw.Db.Sync.Stats`
=> chore: remove unused total stat init

lib/ae_mdw/db/name.ex, lib/ae_mdw/db/sync/name.ex, test/ae_mdw/db/name_claim_mutation_test.exs, test/ae_mdw/db/name_revoke_mutation_test.exs
Single function to deactivate names so that `InactiveNameOwner` (along with `InactiveName` and `InactiveNameExpiration`) is always written on every name deactivation (expiration, update or revoke)
Missing record when revoked or updated.
Sync until 80114 on testnet
=> fix: missing InactiveNameOwner record

lib/ae_mdw/db/name.ex, lib/ae_mdw/db/sync/name.ex, test/ae_mdw/db/name_update_mutation_test.exs, test/support/ae_mdw/node/aetx_fixtures.ex
- Fixes the delete of `ActiveNameExpiration` during a name update with ttl 0
- Expires without any validation (assures that previous state transitions were correct)
Fixes sync on height [162223](https://github.com/aeternity/ae_mdw/pull/594#issuecomment-1075625216)
Sync from scratch (delete the `mdw.db` dir) until the height 164809 with:
```
$ git checkout rocksdb-contracts
$ git merge --no-commit fix-update-ttl-0
$ make shell # or docker-compose up
```
=> fix: deactivate name on update with ttl 0

lib/ae_mdw/stats.ex, lib/ae_mdw_web/router.ex, test/integration/ae_mdw_web/controllers/stats_controller_test.exs
- Fix `/totalstats` first height
- Accommodate changes from stats v1 to v2 on test cases.
=> fix: fix totalstats first height and v1/v2 stats tests

lib/ae_mdw_web/router.ex
Fix for v1 -> v2 migration:
```   5) test balances returns an error message when the balance is not available (Integration.AeMdwWeb.Aex9ControllerTest)
test/integration/ae_mdw_web/controllers/aex9_controller_test.exs:243
** (Phoenix.ActionClauseError) no function clause matching in AeMdwWeb.Aex9Controller.balance/2
...
%{"contract_id" => "ct_M9yohHgcLjhpp1Z8SaA1UTmRMQzR4FWjJHajGga8KBoZTEPwC"}
```
=> fix: fix aex9 balances route for a contract

lib/ae_mdw/db/sync/stats.ex
Avoids negative values for contracts_created delta stats when resuming sync from not the first microblock. 
Current error: `{:delta_stat, 162895, 0, 0, 0, 0, 0, 0, -2, 231660358983900000000,
28340043916100000000}`
=> fix: resume contract created stats setting min value to 0

lib/ae_mdw/db/util.ex, test/integration/ae_mdw_web/controllers/aex9_controller_test.exs
Fixes `{"error":"invalid id: mh_kkKtNk2GAgJKjar9ro6amr6AugG9eLP9RL7wUSmdRqjBZrRq9"}` 
for requests like
`/aex9/balances/hash/mh_kkKtNk2GAgJKjar9ro6amr6AugG9eLP9RL7wUSmdRqjBZrRq9/account/ak_CNcf2oywqbgmVg3FfKdbHQJfB959wrVwqfzSpdWVKZnep7nj4`
=> fix: get bi for a block hash

test/integration/ae_mdw_web/controllers/name_controller_test.exs
* Fixes test cases that considers inactive names expiration/deactivation only by expiration height.
On v1 endpoint, [at least since April 30 2021 (v1.0.8)](https://github.com/aeternity/ae_mdw/issues/396#issuecomment-1087850775), the `InactiveNameExpiration` table/record is also used for revoked height. This is needed to know which names were deactivated lately (or firstly depending on `backward` or `forward` direction) whether the name had expired or had being revoked.
On v2 endpoint the purpose of the parameter can be improved/clarified renaming it from `by=expiration` to ~~`by=height`~~ `by=deactivation`
=> test: fix integration inactive names cases by expiration/deactivation

README.md, lib/ae_mdw/names.ex, lib/ae_mdw_web/controllers/name_controller.ex, test/integration/ae_mdw_web/controllers/name_controller_test.exs
* Accept by=deactivation on /v2/names/* (by=expiration will be deprecated on /v1 deprecation)
* Change documentation to clarify the use of `by` parameter explaining that the sorting considers also the revoke height.
The v1 `/names/inactive?by=expiration` had always sorted not only by expiration but also included the revoked names. This  is needed to know which names were deactivated lately (or firstly depending on backward or forward direction) whether the name had expired or had being revoked.
=> refactor: rename /v2/names/* by=expiration to by=deactivation

.iex.exs, lib/ae_mdw/aex9.ex, lib/ae_mdw/node/db.ex, lib/ae_mdw/sync/async_tasks/derive_aex9_presence.ex, priv/migrations/20220406151722_derive_aex9_presence_and_balance.ex, test/integration/ae_mdw_web/controllers/aex9_controller_test.exs, test/integration/ae_mdw_web/controllers/aex9_token_controller_test.exs
* Safely gets the hash of next block to compute the aex9 balance during async task processing.
* Initialize aex9 balance with empty mapping to differentiate from `balance is not yet available` condition (`Aex9BalanceNotAvailable` exception)
Closes #615 
```
INTEGRATION_TEST=1 elixir --sname aeternity@localhost -S mix test.integration  test/integration/ae_mdw_web/controllers/aex9_controller_test.exs:269
INTEGRATION_TEST=1 elixir --sname aeternity@localhost -S mix test.integration  test/integration/ae_mdw_web/controllers/aex9_controller_test.exs:281
```
Other issues involving cached aex9 balance that will be handled in a following PR.
=> fix: get next block hash on async task

.github/actions/node-setup/action.yml, .github/workflows/test-action.yml, Makefile, scripts/coveralls.sh
Change static analysis tasks to run without docker.
Setting up dependencies with docker takes about 3m.
=> ci: speedup check formatted and credo

.github/actions/mdw-setup/action.yml, .github/actions/node-setup/action.yml, .github/workflows/test-action.yml, Makefile
Decrease `dialyzer` CI job time from 4m50s to 1m12s by not using docker.
=> ci: speed up dialyzer running without docker

scripts/endpoint-diff.sh
Usage: `./scripts/endpoint-diff.sh URL1 URL2`
By default it will compare `https://mainnet.aeternity.io` and `http://localhost:4000`.
=> chore: add diffing script to compare two different environments

lib/ae_mdw/contract.ex
=> fix: don't display source_hash when invalid compilation info

lib/ae_mdw_web/controllers/tx_controller.ex
=> fix: fix displaying single txis for v2

lib/ae_mdw/db/origin.ex
=> fix: allow contract call to GA contract

lib/ae_mdw/application.ex, lib/ae_mdw/sync/server.ex
This bug would cause the server not to start when syncing from
scratch, you needed to restart it manually. It caused no
inconsistencies, though.
=> fix: handle stating server when syncing from scratch

lib/ae_mdw/db/status.ex, lib/ae_mdw/sync/server.ex
Example of the status response:
```
{
"mdw_async_tasks": {
"long_tasks": 0,
"producer_buffer": 1,
"total_pending": 3
},
"mdw_gens_per_minute": 345.19,
"mdw_height": 341556,
"mdw_revision": "b9aa4a8",
"mdw_synced": false,
"mdw_syncing": true,
"mdw_tx"_index: 17680520,
"mdw_version": "1.8.1",
"node_height": 588976,
"node_progress": 100,
"node_revision": "39941357ac8491d890155c2ccbcd0571fbf3f5a0",
"node_syncing": false,
"node_version": "6.4.0"
}
```
=> feat: display mdw gens processed per min on the status page

mix.exs, test/integration/ae_mdw_web/controllers/aex9_controller_test.exs, test/test_helper.exs
Increase test coverage for AEX9 calling some endpoints with all existing aex9 contracts.
Most bugs reported were from specific contracts.
- Another PR will cover data consistency across multiple endpoints. Something like https://github.com/aeternity/ae_mdw/blob/647062bf35a55e0b23074c40f4706f020ee57b27/test/integration/ae_mdw_web/controllers/aex9_controller_test.exs#L458 that is skipped for now due to long time needed to run.
- Some endpoints does not use saved aex9 balance records yet. There will be a following PR for that.
=> test: add aex9 tests iterating throughout all contracts

lib/ae_mdw/db/mutations/derive_aex9_presence_mutation.ex, lib/ae_mdw/sync/async_tasks/derive_aex9_presence.ex, test/ae_mdw/sync/async_tasks/derive_aex9_presence_test.exs
Rebasing is sometimes cumbersome ...
- Fixes regression on aex9 balance after in-memory state.
- Adds test case to prevent similar case and to validate that both aex9 balance and presence were written.
PS: This requires a sync from scratch and a following PR will add the txi.
=> fix: write block_index to aex9 balance

lib/ae_mdw/aex9.ex
This record with <<>> account_pk and nil amount is created to display
to the user that the contract has not yet being processed for
balances.
=> fix: ignore aex9 balances only when there's a single <<>> balance

lib/ae_mdw/database.ex, lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/db_store.ex, lib/ae_mdw/db/int_transfer.ex, lib/ae_mdw/db/mutations/names_expiration_mutation.ex, lib/ae_mdw/db/rocksdb_cf.ex, lib/ae_mdw/db/state.ex, lib/ae_mdw/db/store.ex, lib/ae_mdw/db/sync/block.ex, lib/ae_mdw/db/txn_db_store.ex, lib/ae_mdw/sync/async_tasks/stats.ex, lib/ae_mdw/sync/server.ex, test/ae_mdw/db/mutations/stats_mutation_test.exs, test/ae_mdw_web/controllers/name_controller_test.exs, test/ae_mdw_web/controllers/oracle_controller_test.exs
This Store abstraction will be the basic protocol that the memory
store will need to implement later on. Wanted to add it on a separate
PR.
Additionally, update all mutation reads to make sure they are read
from data belonging to the transaction.
Next up: `MemStore` implementation
=> refactor: dirty reads + add Store abstraction

lib/ae_mdw/db/db_store.ex, test/ae_mdw_web/controllers/name_controller_test.exs, test/ae_mdw_web/controllers/oracle_controller_test.exs
This is a presentation fix only, but it was causing forward
collections to return empty results.
=> fix: handle prev/next when key_boundary is nil

lib/ae_mdw/db/contract.ex, lib/ae_mdw_web/controllers/aex9_controller.ex, test/integration/ae_mdw_web/controllers/aex9_controller_test.exs
- Skips writing `Aex9AccountPresence` for remote calls
- Aex9 balances are not yet computed for remote calls (shall be part of the scope of #308)
- Additionally this PR fixes test cases used to test the root cause of the error
=> fix: remove aex9 presence for remote calls

lib/ae_mdw_web/controllers/aex9_controller.ex, test/integration/ae_mdw_web/controllers/aex9_controller_test.exs
Add fallback to avoid stop returning the balances with matching aex9 presence.
Validated with: 
`INTEGRATION_TEST=1 elixir --sname aeternity@localhost -S mix test.integration test/integration/ae_mdw_web/controllers/aex9_controller_test.exs:493`
=> chore: add fallback for mismatched presence to balance

lib/ae_mdw_web/controllers/name_controller.ex
Since the SDK client depends on operation names to programatially
generate the client API, we're reverting the swagger v1 endpoint names
so that it doesn't introduce breaking changes.
In the future, a new swagger file will be added with all of the new
and updated operations containing v2 endpoints.
refs #179
=> chore: revert swagger name operation names

lib/ae_mdw/db/rocksdb_cf.ex, lib/ae_mdw/db/sync/invalidate.ex, test/ae_mdw/db/contract_call_mutation_test.exs, test/ae_mdw/sync/invalidate_test.exs
- Invalidates/delestes all aexn records within a txi range
- Eliminates use of RevAex9Contract
Continuation of https://github.com/aeternity/ae_mdw/pull/667#issue-1226739507
Refs https://github.com/aeternity/ae_mdw/issues/629
`elixir --sname aeternity@localhost -S mix test test/ae_mdw/sync/invalidate_test.exs`
=> refactor: invalidate aexn contract

lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/mutations/contract_create_mutation.ex, lib/ae_mdw/db/sync/transaction.ex, test/ae_mdw/db/contract_create_mutation_test.exs, test/support/ae_mdw/node/contract_call_fixtures.ex
Fix contract creation having aex9 logs.
`elixir --sname aeternity@localhost -S mix test test/ae_mdw/db/contract_create_mutation_test.exs`
=> fix: handle update aex9 state on contract create logs

lib/ae_mdw/blocks.ex, lib/ae_mdw_web/controllers/block_controller.ex, test/integration/ae_mdw_web/controllers/block_controller_test.exs
Previously the value displayed was the Elixir binary representation
(e.g. `<<210, 20, 143, ...>>`). Instead, the AE encoded hash is used
as displayed on the URL.
=> fix: display unencoded block hash when not found

lib/ae_mdw/contract.ex, lib/ae_mdw/dry_run/contract.ex, lib/ae_mdw/dry_run/runner.ex
Set dynamic low `gas limit` relative to Node base gas for aexn `meta_info` and `aex*_extensions` methods
Refs #713 
aex9 (mainnet)
```
iex(aeternity@localhost)1> pk = Validate.id! "ct_M9yohHgcLjhpp1Z8SaA1UTmRMQzR4FWjJHajGga8KBoZTEPwC"
<<45, 195, 148, 17, 5, 88, 182, 202, 65, 160, 150, 218, 33, 163, 136, 171, 149,
101, 165, 178, 212, 56, 89, 23, 172, 233, 200, 126, 138, 235, 158, 11>>
iex(aeternity@localhost)2> AeMdw.AexnContracts.call_extensions(:aex9, pk)                          
{:ok, ["allowances", "mintable", "burnable", "swappable"]}
```
aex141 (testnet)
```
iex(aeternity@localhost)3> pk = Validate.id! "ct_AC8mHZ4xucA6mjk6gtXMDbs3FtHYds3Wm1oWdKYHhPyBtm9vj"
<<20, 223, 25, 21, 30, 145, 133, 175, 231, 153, 252, 160, 158, 79, 250, 88, 43,
242, 20, 103, 189, 134, 72, 165, 194, 232, 24, …
```
=> feat: set low gas limit relative to Node base gas

README.md, lib/ae_mdw_web/router.ex
A name is only linked to a single auction
=> fix: use valid name auction route as specified in docs

lib/ae_mdw/aexn_contracts.ex, lib/ae_mdw/contract.ex, lib/ae_mdw/db/sync/transaction.ex, lib/ae_mdw/dry_run/contract.ex, lib/ae_mdw/dry_run/runner.ex, lib/ae_mdw/node.ex, lib/ae_mdw/node/db.ex, test/ae_mdw/db/sync/transaction_test.exs
- Enable credo on `AeMdw.Contract`
- Refactor `AeMdw.Contract` to single responsibility (move dry run code to its own module)
- Add spec types for dry run
Create a aex141 or aex9 contract
=> refactor: enable credo and move dry run code to specific module

lib/ae_mdw_web/controllers/name_controller.ex
=> fix: handle names search endpoint when no prefix

priv/migrations/20220622062201_truncate_aexn_metainfo.ex, priv/migrations/20220622062203_truncate_aexn_metainfo.ex
Truncates existing (already synced) AEX-N sorting field values (name or symbol)
=> chore: add truncate metainfo migration

lib/ae_mdw_web/controllers/aex9_controller.ex, test/integration/ae_mdw_web/controllers/aex9_controller_test.exs
Use height and hash params to get the balance on aex9 endpoints:
```
get "/aex9/balances/gen/:height/account/:account_id", Aex9Controller, :balances
get "/aex9/balances/hash/:blockhash/account/:account_id", Aex9Controller, :balances
```
Fixes #707 
Fixes #708 
`INTEGRATION_TEST=1 elixir --sname aeternity@localhost -S mix test --include iteration test/integration/ae_mdw_web/controllers/aex9_controller_test.exs`
=> fix: use height/hash param on aex9 legacy endpoints

lib/ae_mdw/application.ex, lib/ae_mdw/db/aex9_balances_cache.ex, lib/ae_mdw/ets_cache.ex, lib/ae_mdw/sync/async_tasks/update_aex9_state.ex, test/ae_mdw/sync/async_tasks/update_aex9_state_test.exs
Get balances for same contract and same block only once (avoid multiple costly dry-run) during in-memory sync.
Refs #211 (not in parallel yet but one step further)
Refs #749 
On next PRs:
- Use this Aex9BalanceCache on endpoints read operations (possibly with another implementation of Db.Store protocol).
- Run aex9 tasks asynchronously (restore behaviour reviewing producer-consumer)
- Use only Aex9BalanceCache for in-memory sync and as data source to persist aex9 records (don't use State/MemStore to save parallel and asynchronous aex9 results)
- Handle forks and intercept tasks belonging to invalid blocks
=> feat: dry-run balances only once per contract and block

test/ae_mdw/db/name_claim_mutation_test.exs, test/ae_mdw/db/name_update_mutation_test.exs, test/ae_mdw_web/controllers/name_controller_test.exs
Add other cases for name mutations (extra fix for intermittent endpoint error due to repeated name)
=> test: add name sync tests for more scenarios

lib/ae_mdw/db/mutations/oracles_expiration_mutation.ex, lib/ae_mdw/sync/server.ex
Reading an already deleted key on a transaction will return the deleted
record anyway, so not chunking multiple blocks into a single transaction
will reduce the chances of it happening.
=> fix: use single-block transactions to avoid duplicated deletions

config/config.exs, lib/ae_mdw/blocks.ex, lib/ae_mdw_web/supervisor.ex, test/integration/ae_mdw_web/controllers/block_controller_test.exs
This was generating invalid results, because blocks were cached too much time.
It also provides very little performance benefit (if at all)
=> fix: remove blocks cache displayed on /v2/blocks

lib/ae_mdw/db/mutations/key_block_mutation.ex, lib/ae_mdw/db/state.ex
Since the cache was never being cleared, many of the name/oracle
records started to accumulate, flooding the memory and reducing
syncing performance.
This won't affect the performance for the last generations executed
in-memory, they are in-memory and rapidly accessed anyway.
=> chore: clear state hash for every key block

lib/ae_mdw/blocks.ex, lib/ae_mdw/db/name.ex, lib/ae_mdw/db/sync/name.ex, lib/ae_mdw/db/util.ex, lib/ae_mdw/node/db.ex, test/ae_mdw/db/name_claim_mutation_test.exs, test/ae_mdw_web/controllers/name_controller_test.exs, test/integration/ae_mdw_web/controllers/block_controller_test.exs
Also, moving Node-related functions to Node.Db, and out of Db.Util
=> chore: remove unused Db.Util functions

lib/ae_mdw/aex9.ex, lib/ae_mdw/application.ex, lib/ae_mdw/db/async_store.ex, lib/ae_mdw/db/state.ex, lib/ae_mdw/ets_cache.ex, lib/ae_mdw/node/db.ex, lib/ae_mdw/sync/async_tasks/update_aex9_state.ex, test/ae_mdw/aex9_test.exs, test/ae_mdw/db/state_test.exs
* Add in-memory `Store` that can be used by (multiple) async tasks
* Change AEX9 tasks to use this `Store`
* Handles :chain_too_short condition when updating aex9 state for the last microblocks
Shared in-memory among multiple processes (tasks) in order to allow writing to the same `State`.
Refs #749
=> feat: add store to serve async tasks

lib/ae_mdw/database.ex, lib/ae_mdw/db/rocksdb_cf.ex, test/ae_mdw/database_test.exs, test/ae_mdw/db/rocksdbcf_test.exs
Check if key exists before deleting on db transaction 
Raise detailed message when key is missing.
The missing key being deleted was from a record not indexed by 1.11
=> chore: raise detailed message when deleting txn missing key

lib/ae_mdw_web/plugs/state_plug.ex, test/ae_mdw_web/controllers/oracle_controller_test.exs, test/support/conn_case.ex, test/support/test_sample.ex, test/support/test_util.ex
This not only avoids mocking every single Database function, but also
allows for declarative and functional tests by specifying the state of
the store required for the test to pass.
=> test: add helper with_state/2 function for declarative tests

lib/ae_mdw/application.ex, lib/ae_mdw/ets_cache.ex, lib/ae_mdw/sync/server.ex, lib/ae_mdw_web/websocket/broadcaster.ex, test/integration/ae_mdw_web/websocket_test.exs
This state check will avoid sending the same mb/kb multiple times, which happens when re-syncing in-memory gens.
refs #808
=> fix: broadcast in-memory blocks

lib/ae_mdw/db/origin.ex, test/ae_mdw/db/origin_test.exs, test/support/test_sample.ex
In order to update the stats we're going to need to run a full-sync, this bug has been always present, even in production.
=> fix: include ga_attach_tx when counting contracts

.iex.exs, lib/ae_mdw/application.ex, lib/ae_mdw/db/aex9_balances_cache.ex, lib/ae_mdw/db/async_store.ex, lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/mutations/async_store_mutation.ex, lib/ae_mdw/db/mutations/purge_aex9_state_mutation.ex, lib/ae_mdw/db/state.ex, lib/ae_mdw/ets_cache.ex, lib/ae_mdw/sync/async_store_server.ex, lib/ae_mdw/sync/async_tasks/consumer.ex, lib/ae_mdw/sync/async_tasks/producer.ex, lib/ae_mdw/sync/async_tasks/store.ex, lib/ae_mdw/sync/async_tasks/supervisor.ex, lib/ae_mdw/sync/async_tasks/update_aex9_state.ex, lib/ae_mdw/sync/supervisor.ex, test/ae_mdw/aex9_test.exs, test/ae_mdw/db/aexn_create_contract_mutation_test.exs, test/ae_mdw/db/async_store_test.exs, test/ae_mdw/db/contract_call_mutation_test.exs, test/ae_mdw/db/contract_create_mutation_test.exs, test/ae_mdw/db/contract_test.exs, test/ae_mdw/db/state_test.exs, test/ae_mdw/db/sync/async_tasks/producer_consumer_test.exs, test/ae_mdw/db/sync/async_tasks/producer_test.exs, test/ae_mdw/sync/async_tasks/stats_test.exs, test/ae_mdw/sync/async_tasks/store_test.exs, test/ae_mdw/sync/async_tasks/update_aex9_state_test.exs, test/ae_mdw_web/controllers/aexn_token_controller_test.exs, test/support/ae_mdw/async_task_test_util.ex
- Runs aex9 tasks asynchronously
- Purges aex9 in-memory and persisted records belonging to invalidated blocks
- Synchronizes the writing of async task result with the main sync database transaction so that if the task finishes later it writes directly to the database.
- Avoid rerunning the tasks for on-db sync (use previous in-memory task result to write to database)
Refs #749 
- test/ae_mdw/sync/async_tasks/update_aex9_state_test.exs 
- validates writing to async (in-memory) store
- test/ae_mdw/sync/async_tasks/store_test.exs
- validates not to insert a task when it had been added before (if added to on-memory doesn't do for on-db sync)
- test/ae_mdw/db/state_test.exs 
- validates the synchronization to write to memory or to disk
- validates that if task was enqueued by on-memory sync …
=> feat: synchronize async tasks write

lib/ae_mdw/sync/async_tasks/producer.ex, lib/ae_mdw/sync/async_tasks/stats.ex, test/ae_mdw/sync/async_tasks/stats_test.exs
Next PR will handle the case when db async task counting varies on range never divisible by 10.
=> fix: decrease async task producer dequeue time

lib/ae_mdw/sync/async_store_server.ex, lib/ae_mdw/sync/async_tasks/consumer.ex, lib/ae_mdw/sync/async_tasks/producer.ex, lib/ae_mdw/sync/async_tasks/stats.ex, lib/ae_mdw/sync/async_tasks/update_aex9_state.ex, lib/ae_mdw/sync/async_tasks/work.ex, test/ae_mdw/db/state_test.exs, test/ae_mdw/sync/async_tasks/stats_test.exs, test/ae_mdw/sync/async_tasks/update_aex9_state_test.exs
Decreases the number of soft real time preemption on `AsyncStoreServer` by delegating the signaling of async task done.
=> refactor: decrease consumer async server wait and sleep

lib/ae_mdw/dry_run/contract.ex, lib/ae_mdw/dry_run/runner.ex, lib/ae_mdw/node/db.ex, lib/ae_mdw/sync/async_tasks/update_aex9_state.ex, test/ae_mdw/db/contract_call_mutation_test.exs, test/ae_mdw/db/contract_test.exs, test/ae_mdw/db/state_test.exs, test/ae_mdw/dry_run/runner_test.exs, test/ae_mdw/sync/async_tasks/update_aex9_state_test.exs
- Replaces unnecessary use of banging `:aect_state_tree.get_contract(pubkey, contracts)`
- Discards the async task when dry-run fails due to `:contract_does_not_exist` or other error like insufficient funds. 
A contract may not exist anymore on a microblock referenced by block_index, which might happen syncing the last microblocks.
=> fix: handle dry-run error when contract is not present

lib/ae_mdw/db/model.ex, lib/ae_mdw/db/mutations/stats_mutation.ex, lib/ae_mdw/db/state.ex, lib/ae_mdw/db/sync/block.ex, lib/ae_mdw/stats.ex, lib/ae_mdw_web/controllers/stats_controller.ex, lib/ae_mdw_web/router.ex, test/ae_mdw/db/mutations/stats_mutation_test.exs
TPS is calculated by grabbing the microblocks from a single gen and using the total transactions from that gen
refs #821
=> feat: add txs per second stat on /stats

lib/ae_mdw/sync/async_tasks/producer.ex, lib/ae_mdw/sync/async_tasks/stats.ex, lib/ae_mdw/sync/async_tasks/store.ex, test/ae_mdw/db/contract_call_mutation_test.exs, test/ae_mdw/db/contract_create_mutation_test.exs, test/ae_mdw/db/contract_test.exs, test/ae_mdw/db/state_test.exs, test/ae_mdw/sync/async_tasks/stats_test.exs, test/ae_mdw/sync/async_tasks/store_test.exs, test/support/ae_mdw/async_task_test_util.ex
Dequeue async task by multiple consumers without waiting for the Producer
Avoids timeout or increasing it and speeds up the sync.
Synced on mainnet until 413430 and keeps going without timeout.
=> fix: dequeue async tasks non-preemptively

lib/ae_mdw/sync/async_tasks/consumer.ex, lib/ae_mdw/sync/async_tasks/producer.ex, lib/ae_mdw/sync/async_tasks/store.ex, test/ae_mdw/db/sync/async_tasks/consumer_test.exs, test/ae_mdw/sync/async_tasks/store_test.exs, test/support/ae_mdw/async_task_test_util.ex
Fix for `total_pending` stat related to consumption of task stuck on processing state.
=> fix: rerun failed task and fix processing state

lib/ae_mdw/dry_run/contract.ex
Set maximum gas using a contract with maximum number of accounts as a reference (current max).
AEX-9 balances dry-run gas consumption turned out to be linear and previous value is too high.
Refs #713 #839
=> chore: set dry run gas upper limit

lib/ae_mdw/aexn_tokens.ex, lib/ae_mdw_web/controllers/aex9_controller.ex, lib/ae_mdw_web/controllers/aexn_token_controller.ex, lib/ae_mdw_web/router.ex, test/ae_mdw/aexn_tokens_test.exs, test/ae_mdw_web/controllers/aex141_controller_test.exs
Adds missing unit tests for AEX-141 endpoints and additionally renames "token" routes to "contract" to avoid ambiguity with the token belonging to an NFT contract.
=> test: complement to missing unit tests for AEX-141

lib/ae_mdw_web/controllers/aex9_controller.ex, lib/ae_mdw_web/views/aexn_view.ex, test/ae_mdw_web/controllers/aex9_controller_test.exs
This behavior is not expected for v1 but for v2. However it's an enhancement for v1 while v2 index is refactored.
=> chore: sorts aex9 account balances from last to first (v1)

lib/ae_mdw/aex9.ex, lib/ae_mdw/error.ex, lib/ae_mdw/node/db.ex, lib/ae_mdw_web/controllers/aex9_controller.ex, lib/ae_mdw_web/views/aexn_view.ex, test/ae_mdw_web/controllers/aex9_controller_test.exs
Contracts filtering needs to be performed after the dry-run since the presence is updated with last call.
Balances are consistent with expected 10 integration entries.
=> fix: filter contracts after account balance dry-run on blockhash

README.md, lib/ae_mdw/aexn_tokens.ex, test/ae_mdw_web/controllers/aexn_token_controller_test.exs
- add query for `v2/aex9/by=name?exact=some-name` 
- add query for `v2/aex9/by=symbol?exact=SOME` 
- fix for v1 `/aex9/by_name?exact=some-name` 
- fix for v1 `/aex9/by_symbol?exact=SOME`
=> fix: query aexn by exact name or symbol on v1 and v2

.iex.exs, lib/ae_mdw/aexn_contracts.ex, priv/migrations/20220826152500_aex141_cleanup.ex, test/ae_mdw/aexn_contracts_test.exs
Adapts indexation based on sample NFT from https://github.com/aeternity/aex141-examples/pull/9
Refs #629
=> chore: update aex141 metadata signature

lib/ae_mdw/aex141.ex, test/ae_mdw_web/controllers/aex141_controller_test.exs
Handles variant `owner` NFT contract call after successful mint/transfer.
=> fix: handle variant owner return

lib/ae_mdw/db/rocksdb.ex, test/ae_mdw/db/rocksdb_test.exs
This will allow deleting records created inside the transaction and
non-existent values.
=> fix: remove rocksdb wrapping code that created DB inconsistencies

test/ae_mdw/db/rocksdb_test.exs
Tests covering similar scenario to `total_pending` issue (#869).
=> test: add cases for rocksdb multiple dirty delete calls

lib/ae_mdw/aex9.ex, lib/ae_mdw/aexn_transfers.ex, lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw_web/controllers/aex9_controller.ex, lib/ae_mdw_web/controllers/aexn_transfer_controller.ex, lib/ae_mdw_web/router.ex, lib/ae_mdw_web/views/aexn_view.ex, priv/migrations/20220830144500_aex9_to_aexn_transfers.ex, test/ae_mdw/db/contract_call_mutation_test.exs, test/ae_mdw_web/controllers/aexn_transfer_controller_test.exs, test/support/conn_case.ex
- Adds transfer history endpoints for nft contracts (AEX-141)
- Indexes and reads transfers from generic Aexn* records
Refs #629 
- Includes a migration to move aex9 transfers to generic ones.
- The aex9 transfers tables and its contents will be dropped on a following release.
=> feat: generalize transfer history for aex141

lib/ae_mdw_web/helpers/aexn_helper.ex, priv/migrations/20220826152500_aex141_cleanup.ex
Avoid deleting aex141 contract indexed by metadata covering some mainnet cases.
=> fix: handle out_of_gas_error on aex141 cleanup

lib/ae_mdw_web/controllers/aexn_transfer_controller.ex, lib/ae_mdw_web/views/aexn_view.ex
Maps nft recipient record when filtering transfer by collection as 
`/v2/aex141/transfers/to/ak_QVSUoGrJ31CVxWpvgvwQ7PUPFgnvWQouUgsDBVoGjuT7hjQYW?contract_id=ct_Fv9d66QTjr4yon9GEuMRc2B5y7Afy4to1ATaoYmpUTbN6DYiP`
=> fix: map recipient record when filtering by nft collection

lib/ae_mdw/aex141.ex, lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw_web/controllers/aex141_controller.ex, lib/ae_mdw_web/router.ex, priv/migrations/20220906173000_aex141_owners.ex, test/ae_mdw/db/contract_call_mutation_test.exs, test/ae_mdw_web/controllers/aex141_controller_test.exs
- Index owners of a collection based on nft transfers  
- Add `/aex141/:contract_id/owners` endpoint for querying
Refs #629  
- Includes handling delegated approvals
- An additional PR gonna provide docs for all aex141 endpoints
- New minting and burning gonna be handled by a separated PR (for transfer refactoring)
=> feat: index and fetch nft owners on a collection

lib/ae_mdw/aexn_transfers.ex, lib/ae_mdw/contracts.ex, lib/ae_mdw_web/controllers/aexn_transfer_controller.ex, test/ae_mdw_web/controllers/aexn_transfer_controller_test.exs
Accept `contract` param besides `contract_id` on nft transfer filter because some endpoints work or are documented with `contract` (while contract logs and calls expect `contract_id`).
Refs #629 
- Changes also `/contract/calls` and `/contract/logs` to accept `contract`
- #902 was opened to discuss unifying these params on `/v3`
=> chore: accept contract param besides contract_id

README.md, lib/ae_mdw/blocks.ex, lib/ae_mdw/node/db.ex, lib/ae_mdw_web/controllers/block_controller.ex, lib/ae_mdw_web/router.ex, test/ae_mdw_web/controllers/block_controller_test.exs
=> feat: add /v2/micro-blocks/:hash endpoint

lib/ae_mdw/aex141.ex, lib/ae_mdw/application.ex, lib/ae_mdw/blocks.ex, lib/ae_mdw/contracts.ex, lib/ae_mdw/db/format.ex, lib/ae_mdw/db/stream/name.ex, lib/ae_mdw/db/sync/stats.ex, lib/ae_mdw/transfers.ex, lib/ae_mdw/util.ex, priv/migrations/20220721121200_add_type_count_table.ex, test/ae_mdw/util_test.exs, test/ae_mdw_web/controllers/contract_controller_test.exs, test/support/test_util.ex
- Unify scope deserialization by separating key boundary from the gen or txi scope
- Remove use of `max_blob` for all `/v2/contract/calls` and `/v2/contract/logs` except for data log filtered one
- Remove use of `max_blob` for name and auction prefixing 
- Leverage Erlang term comparison to allocate less memory on query key boundaries
- Adds unit test coverage for `/v2/contract/calls` and `/v2/contract/logs`
- Allocate less memory by replacing `max_256bit_int` with `nil`
- max_blob is a 256KB
- Gladly the BEAM doesn't reallocate every time the `max_blob` 
- Analysis of NFT token id with negative values will be done in a separte PR
=> refactor: allocate smaller tuples for query streams

README.md, lib/ae_mdw/activities.ex, lib/ae_mdw/fields.ex, lib/ae_mdw/txs.ex, test/ae_mdw_web/controllers/activities_controller_test.exs
=> feat: include internal transactions as activities

mix.exs, test/ae_mdw/websocket/broadcaster_test.exs, test/support/blockchain_sim.ex, test/support/ws_client.ex
Add CI tests for only once websocket broadcasting per hash for blocks, transactions and objects.
Other kinds of transaction broadcasting will be added after extending the `BlockchainSim`.
=> test: add cases for websocket broadcasting

.github/workflows/test-action.yml, lib/ae_mdw/application.ex, lib/ae_mdw/database.ex, lib/ae_mdw/db/hardfork_presets.ex, lib/ae_mdw/db/rocksdb_cf.ex, lib/ae_mdw/ets_cache.ex, lib/ae_mdw/sync/async_tasks/stats.ex, lib/ae_mdw/sync/async_tasks/store.ex, lib/ae_mdw/sync/server.ex, lib/ae_mdw_web/controllers/aex9_controller.ex, lib/ae_mdw_web/websocket/broadcaster.ex, lib/ae_mdw_web/websocket/supervisor.ex, lib/mix/tasks/migrate_db.ex, mix.exs, priv/migrations/20220721121200_add_type_count_table.ex, priv/migrations/20220803120000_add_name_fees_to_stats.ex, priv/migrations/20220815120000_add_channels_stats.ex, priv/migrations/20220816120000_add_miners.ex, priv/migrations/20220824120000_reprocess_aens_update_calls.ex, priv/migrations/20220830144500_aex9_to_aexn_transfers.ex, priv/migrations/20220901120000_add_active_channels.ex, priv/migrations/20220908150000_aex141_owners.ex, priv/migrations/20220912195001_aex141_stats.ex, test/ae_mdw/database_test.exs, test/ae_mdw/db/aexn_create_contract_mutation_test.exs, test/ae_mdw/db/name_claim_mutation_test.exs, test/ae_mdw/db/sync/transaction_test.exs, test/ae_mdw/sync/oracle_test.exs, test/ae_mdw_web/controllers/aex9_controller_test.exs
Also fixes some minor bug regarding validating aex9 ranges on the aex9 `balance_range` endpoint which was found when enabling these warnings
=> chore: improve dialyzer warnings to catch unmatched results

lib/ae_mdw_web/controllers/aex141_controller.ex, test/ae_mdw_web/controllers/aex141_controller_test.exs
Since `Integer.parse("123abc")` returns `{123, "abc"}` it was causing owner path to return 500 error.
=> fix: return proper error when aex141 token is a partial int

lib/ae_mdw/db/mutations/oracle_extend_mutation.ex, lib/ae_mdw/db/mutations/oracle_register_mutation.ex, lib/ae_mdw/db/mutations/oracles_expiration_mutation.ex, lib/ae_mdw/db/mutations/stats_mutation.ex, lib/ae_mdw/db/oracle.ex, lib/ae_mdw/db/sync/contract.ex, lib/ae_mdw/db/sync/oracle.ex, lib/ae_mdw/db/sync/transaction.ex, test/ae_mdw/db/oracle_expire_mutation_test.exs, test/ae_mdw/db/oracle_extend_mutation_test.exs, test/ae_mdw/db/sync/contract_test.exs, test/ae_mdw/sync/oracle_test.exs, test/integration/ae_mdw_web/controllers/block_controller_test.exs, test/integration/ae_mdw_web/controllers/name_controller_test.exs, test/support/ae_mdw/db/mutation_case.ex, test/support/conn_case.ex, test/support/test_util.ex
- Add `Oracle.register_mutations` to register an oracle after internal call the same way after a `:oracle_register_tx`
- Refactors Oracle to separate methods that are used only for specific syncing purposes
- Add unit tests
- Existing oracle response handling (and test case) would need an extra review to analyse if the query exception should be raised/propagated
- This origin was saved from the beginning for oracles with `:oracle_register_tx` and can be used for listing created oracles at a certain height
- Oracle endpoint serialization fails on 1.20 (before `:jason` upgrade)
=> fix: add missing origin to oracle created by internal call

lib/ae_mdw/db/format.ex, test/ae_mdw_web/controllers/tx_controller_test.exs, test/support/blockchain_sim.ex
- Fixes json serialization for `:oracle_register_tx` format fields.
- Extends `BlockchainSim` to create on chain oracles
Fixes #928 
Reproducible with mdw 1.20 (previous `jason` lib)
=> fix: transform non encodable binary oracle fields into list

lib/ae_mdw/txs.ex, test/ae_mdw_web/controllers/tx_controller_test.exs
Handles other node tx locations besides `:not_found` like `:none` and `:mempool`.
=> fix: handle other node tx locations

lib/ae_mdw/txs.ex
Reverts a refactor on `/txs` that introduces a bug when filtering transactions by fields like `sender_id` or `oracle`.
It can be reverted because it was added by 5ab2cb2d but is not used by `/activities` endpoint.
=> revert: undo change unused by activities

lib/ae_mdw_web/endpoint.ex, priv/static/swagger/swagger.json
This swagger.json file will be ultimately deprecated.
It was generated before by `phoenix_swagger`, and it simply stayed on the test/prod instances which is why it was still visible. 
Once [we removed that file visibility](https://github.com/aeternity/ae_mdw/commit/54245ab98f9c99c454fbbeae91ca116374b9b4b7#diff-efd2ca7b5fa355b70c2abd8dbde2355b7ad5769b06302ab4f7f6e987325a2490L20) it was no longer accessible.
=> chore: allow rendering static swagger.json (temporary fix)

lib/ae_mdw/contracts.ex, lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw/txs.ex, lib/ae_mdw/util/encoding.ex, lib/ae_mdw_web/helpers/view_helper.ex, priv/migrations/20221010130100_logs_by_index.ex, test/ae_mdw/contracts_test.exs, test/ae_mdw/db/contract_create_mutation_test.exs, test/ae_mdw_web/controllers/contract_controller_test.exs, test/support/ae_mdw/node/contract_call_fixtures.ex
Displays the event logs by the order they happened (sorting by index on the `Model.idx_contract_log`).
Solves #943
=> fix: sort event logs by index

test/ae_mdw_web/controllers/aex9_controller_test.exs
Fix the flaky aex9 test for invalid range.
=> test: use always valid contract for invalid range test

lib/ae_mdw/aexn_contracts.ex, lib/ae_mdw/application.ex, lib/ae_mdw/contract.ex, lib/ae_mdw/db/sync/contract.ex, lib/ae_mdw/node.ex, test/ae_mdw/aexn_contracts_test.exs, test/ae_mdw/db/contract_create_mutation_test.exs, test/ae_mdw/db/sync/transaction_test.exs
Updates the detection of AEX-141 contracts respecting the Hackaton ones when there is a resync (by using the previous spec signatures).
Expects `total_supply` and new signatures for `transfer` and `meta_info` (without IPFS).
=> chore: update aex141 signatures

lib/ae_mdw/activities.ex, lib/ae_mdw/db/util.ex, lib/ae_mdw/txs.ex, test/integration/ae_mdw_web/controllers/activity_controller_test.exs, test/integration/ae_mdw_web/controllers/tx_controller_test.exs
Fixes https://github.com/aeternity/ae_mdw/blob/master/test/integration/ae_mdw_web/controllers/tx_controller_test.exs and https://github.com/aeternity/ae_mdw/blob/master/test/integration/ae_mdw_web/controllers/activity_controller_test.exs
=> fix: order gen-scoped txs and activities properly

lib/ae_mdw/db/format.ex, lib/ae_mdw/db/name.ex, lib/ae_mdw/node.ex, lib/ae_mdw_web/controllers/name_controller.ex, test/ae_mdw_web/controllers/contract_controller_test.exs, test/ae_mdw_web/controllers/name_controller_test.exs, test/ae_mdw_web/controllers/tx_controller_test.exs, test/support/blockchain_sim.ex, test/support/conn_case.ex
Fix for https://mainnet.aeternity.io/mdw/v2/names/:name when name is in auction. 
Adds `:name_claim_tx` to `BlockchainSim`
=> fix: render bid for names in auction

lib/ae_mdw/aexn_contracts.ex, lib/ae_mdw/db/contract.ex, test/ae_mdw/aexn_contracts_test.exs, test/ae_mdw/db/aexn_create_contract_mutation_test.exs, test/integration/ae_mdw_web/controllers/aex9_controller_test.exs
Adds defensive handling of meta info returned by a contract during AEX-N validation and indexation.
=> fix: handle any meta info value

lib/ae_mdw/contract.ex, lib/ae_mdw/db/format.ex, test/ae_mdw_web/controllers/tx_controller_test.exs, test/support/blockchain_sim.ex
As requested by @marc0olo this adds more details to the `ga_attach_tx` call: `gas_used` and decoded `args` 
Added `gas_used` for `ga_meta_tx`
=> feat: render call details for ga_attach and ga_meta

lib/ae_mdw/contract.ex
Fix for https://testnet.aeternity.io/mdw/txi/32440285 involving `:contract_create_tx` args rendering
=> fix: render list of keyword lists args

test/ae_mdw/db/oracle_register_mutation_test.exs, test/ae_mdw/db/oracle_response_mutation_test.exs, test/ae_mdw/sync/oracle_test.exs
Complement test coverage for oracles syncing to validate multiple oracle register scenarios and have a case for each mutation (like for name ones). 
Part of increasing test coverage in order to prevent regressions. Following to be done for aex9, aex141 and names (factory method) as well.
=> test: complement coverage for oracle syncing

lib/ae_mdw/contract.ex, lib/ae_mdw/db/sync/contract.ex, priv/migrations/20221027120000_reverse_internal_tx_calls.ex, test/ae_mdw/db/sync/contract_test.exs
Events are added to the tx_env in a reverse order: https://github.com/aeternity/aeternity/blob/e66a588a41d8af5f4ce8467f28258d3f2c74cd8e/apps/aetx/src/aetx_env.erl#L324
=> fix: events from the node are obtained in reverse order

lib/ae_mdw/names.ex, test/ae_mdw_web/controllers/name_controller_test.exs, test/ae_mdw_web/controllers/tx_controller_test.exs, test/support/blockchain_sim.ex
Adds all pointers besides account one to `/v2/names` response.
Closes #986
- Adds missing test cases to prevent regression
- Adds `name_update_tx` and `name_revoke_tx` to BlockchainSim
=> fix: render all pointers on names endpoint

lib/ae_mdw/txs.ex, test/ae_mdw_web/controllers/tx_controller_test.exs
This change allows filtering txs count by both `type` and `tx_type` to avoid the request being blocked by browser tracker/ad blockers.
=> chore: allow /txs/count to be filtered by tx_type

lib/ae_mdw/db/format.ex, lib/ae_mdw/db/name.ex, lib/ae_mdw/names.ex, lib/ae_mdw_web/controllers/name_controller.ex, test/ae_mdw/db/name_test.exs, test/ae_mdw_web/controllers/name_controller_test.exs, test/ae_mdw_web/controllers/tx_controller_test.exs, test/integration/ae_mdw_web/controllers/name_controller_test.exs, test/support/blockchain_sim.ex
Fixes the rendering of binary pointer keys: https://testnet.aeternity.art/mdw/v2/txs?type=name_update&limit=20&direction=forward  
where the "invalid byte 0xAE" is in the non-string binary pointer: `<<104, 65, 117, 174, 49, 251, 29, 202, 69, 174, 147, 56, 60, 150, 188, 247, 149, 85, 150, 148, 88, 102, 186, 208, 87, 101, 78, 111, 189, 5, 144, 101>>`
Sample urls fixed:
http://localhost:4000/v2/names?cursor=138231-test.test&direction=forward&limit=1
http://localhost:4000/v2/names/test.test
http://localhost:4000/name/test.test
http://localhost:4000/v2/txs?cursor=29614&limit=1
http://localhost:4000/v2/txs/29614
Closes #986 (it turns out that ce9293bf was a revert).
*binary* here in the meaning of not text (every pointer key is a `binary()`)
=> fix: render binary pointer key on name related endpoints

lib/ae_mdw/contracts.ex, test/ae_mdw_web/controllers/contract_controller_test.exs
When filtering by a function name prefix the scoping of the query was being ignored
=> fix: scope contract calls filtered by function properly

lib/ae_mdw/db/format.ex, lib/ae_mdw/db/name.ex, lib/ae_mdw/txs.ex, test/ae_mdw_web/controllers/tx_controller_test.exs, test/support/blockchain_sim.ex
Encode `SpendTx` name recipient when pointer is not formatted.
Fix for https://testnet.aeternity.art/mdw/v2/txs/th_79Lt9CPHotYmcSUoi9A4WddAdhq9vipdyXPst8TiFwcBcPnJt
`elixir --sname aeternity@localhost -S mix test test/ae_mdw_web/controllers/tx_controller_test.exs:256`
=> fix: handle account_pubkey recipient pointee

lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/mutations/aexn_create_contract_mutation.ex, lib/ae_mdw/db/mutations/update_aex9_state_mutation.ex, lib/ae_mdw/sync/async_tasks/producer.ex, lib/ae_mdw/sync/async_tasks/stats.ex, test/ae_mdw/sync/async_tasks/stats_test.exs
Handle dry run timeout (when server is busy and it doesn't respond after 250ms) by initializing aex9 event balance with async task.
Refs #969
=> chore: handle dry run timeout

config/config.exs
`--format=%h` returns an abbreviated number of digits for a given commit SHA-1. Depending on the amount of objects in the git repository the length of this identifier will change. As per git docs:
> will vary according to the number of objects in the repository with a default of 7
=> fix: adjust git revision digits to allow variable length

lib/ae_mdw/aex141.ex, lib/ae_mdw_web/views/aexn_view.ex, test/ae_mdw_web/controllers/aex141_controller_test.exs
Returns nft contract limits under `limits` object in way that if there is no limit only one field is returned.
=> chore: put nft contract limits in a map

.github/actions/mdw-setup/action.yml, .github/workflows/test-action.yml
Set os and otp according to https://github.com/erlef/setup-beam
Notes: 
- unit tests action continues to run on the mdw docker image os and otp
- for test coverage please see #1055
=> test: use strict version on otp ci

lib/ae_mdw/db/contract.ex, test/ae_mdw/db/contract_call_mutation_test.exs, test/ae_mdw_web/controllers/aex141_controller_test.exs, test/ae_mdw_web/controllers/aex9_controller_test.exs, test/ae_mdw_web/controllers/aexn_token_controller_test.exs
- Replaces the dry run with events in regards to sync (next is the endpoint)
- Improves test setup
Refs #969
Scoped as part of the latest request to replace the aex9 dry-run balance with the event ones.
=> feat: add aex9 presence after event

lib/ae_mdw/aex141.ex, lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/model.ex, test/ae_mdw/db/contract_call_mutation_test.exs, test/ae_mdw_web/controllers/aex141_controller_test.exs
Use similar object/map for template limits likewise contract limits.
Note: there will be supply info related to edition object.
=> chore: add template limit details to edition

config/dev.exs, config/test.exs
Enable setting network id for dev and test environments
Required when running locally with `make shell` to allow using `uat_backup_v1_full_latest.tar.zst`
=> chore: allow network id for local environment

README.md, config/config.exs, lib/ae_mdw/sync/server.ex, lib/ae_mdw_web/websocket/broadcaster.ex, lib/ae_mdw_web/websocket/chain_listener.ex, lib/ae_mdw_web/websocket/socket_handler.ex, lib/ae_mdw_web/websocket/subscriptions.ex, lib/ae_mdw_web/websocket_endpoint.ex, test/ae_mdw/websocket/broadcaster_test.exs, test/ae_mdw/websocket/socket_handler_test.exs, test/ae_mdw/websocket/subscriptions_test.exs, test/integration/ae_mdw_web/websocket_test.exs, test/support/ws_util.ex
To connect to the v2 websocket a param needs to be passsed when establishing the WS connection: `/websocket?version=2`
These new websocket messages will:
* Contain the additional block/tx information that the middleware already provides in the `/v2/key-blocks/:height`, `/v2/micro-blocks/:hash` and `/v2/txs/:hash` endpoints.
* Order the blocks emitted in the order from the chain: for each generation the key-block is emitted before the generation micro-blocks.
=> feat: add v2 websocket implementation

.github/workflows/test-action.yml
=> fix: remove dockerization from ci tests run

lib/ae_mdw/aex141.ex, lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw/db/sync/stats.ex, lib/ae_mdw/stats.ex, lib/ae_mdw_web/controllers/aex141_controller.ex, lib/ae_mdw_web/router.ex, test/ae_mdw/db/contract_call_mutation_test.exs, test/ae_mdw_web/controllers/aex141_controller_test.exs
- Adds endpoint `/aex141/:contract_id/templates/:template_id/tokens`
- Adds supply info to `/aex141/:contract_id/templates` edition response field
- Final request from @marc0olo to allow comparing the template edition limit to the actual supply (refs #629)
Docs to be updated on a following PR
=> feat: track nft template edition supply 

priv/static/swagger/swagger_v2.yaml
I've checked the swagger docs at
https://swagger.io/docs/specification/describing-parameters/#path-parameters
and I can't find the meaning of this `:`, also it doesn't appear in other places, so I think this is a typo.
=> fix: remove extra colon before in path parameter name

priv/static/swagger/swagger_v2.yaml
the parameter with `recipient` name is defined below
=> fix: name of sender parameter of get_aex9_pair_transfers

.github/workflows/test-action.yml, Dockerfile, docker-compose.yml
Adds visibility to what happens running the middleware in a docker container.
=> ci: enable docker image tests

lib/ae_mdw/aexn_contracts.ex, lib/ae_mdw/application.ex, lib/ae_mdw/contract.ex, lib/ae_mdw/contracts.ex, lib/ae_mdw/node.ex, test/ae_mdw_web/controllers/contract_controller_test.exs
Set `event_name` on `/contracts/logs` response if it's an AEX-N event.
=> feat: return event name when it is aexn

.github/workflows/dockerhub.yml
Use MIX_ENV=prod on version tags and MIX_ENV=dev for master
* Since master is the development branch it makes sense that is build with MIX_ENV=dev
ref: https://github.com/aeternity/ae_mdw/pull/1100
=> chore(ci): conditional dockerhub build env

docker-compose-dev.yml, docker-compose.yml, docker/gitconfig, scripts/do.sh
@venimus is the intention to use this `master` tag instead of latest? Also, I wasn't able to find the `ae_mdw_dev` image on dockerhub, do we need to name it?
=> chore: use master instead of latest to pull docker image

lib/ae_mdw/channels.ex, lib/ae_mdw/node/db.ex, lib/ae_mdw_web/controllers/channel_controller.ex, test/ae_mdw_web/controllers/channel_controller_test.exs
=> feat: query channel reserve at a hash

.github/workflows/release-please.yml
It is possible that since release-please is creating the git tags it won't trigger the dockerhub workflow that is bind to it. Similar issue with `on:release` when both workflows use the default github-token. There is now a organization-wide secret (available for all projects) for similar cases so we can use it. 
Note: as a side-effect release-please changes would appear as made from different "user" (bot) in github
=> chore(ci): use custom token instead of default

lib/ae_mdw/activities.ex, lib/ae_mdw/db/util.ex, lib/ae_mdw/fields.ex, test/ae_mdw_web/controllers/activities_controller_test.exs
We consider "owned" activities as those that are explicitly created by the account.
=> feat: allow filtering activities by ownership only

README.md, scripts/do.sh
Update to simplify setup instructions according to different envs and to remove remaining references to `make`.
=> docs: simplify setup instructions

README.md, lib/ae_mdw/application.ex, lib/ae_mdw/db/channels.ex, lib/ae_mdw/db/sync/transaction.ex, lib/ae_mdw/fields.ex, lib/ae_mdw/node.ex, test/ae_mdw_web/controllers/activities_controller_test.exs
- Removes indexation of `channel_offchain_tx` that is never present directly on chain (only via payload)
- Removes some initialization caching code that is not used
- Fixes a typo on README command
=> chore: remove unused code

.github/workflows/dockerhub.yml
Fix for yet another issue with version tags. Looks like for some reason on `push tag` the meta-extractor does not see the branch in the github context and can't resolve properly `{{is_default_branch}}`, although that case isn't documented in their docs
=> chore(ci): always enable semver tags

lib/ae_mdw/db/hardfork_presets.ex, mix.exs, test/ae_mdw/db/hardfork_presets_test.exs
=> fix: skip importing hardfork accounts for custom networks

lib/ae_mdw_web/websocket/broadcaster.ex, lib/ae_mdw_web/websocket/subscriptions.ex, test/ae_mdw/websocket/subscriptions_test.exs, test/support/ws_util.ex
- Enqueue a block or block + transactions only once to avoid filling GenServer mailbox with data to be discarded (same block that is synced multiple times is enqueued once).
- Enqueue only the microblock header (without transactions) for "MicroBlocks" subscription
- Skips fetching and serializing multiple transactions when there is no "Transactions" or "Object" subscription
- Simplify blocks serialization by reusing `Db.prev_block_type`
refs #1122 
- Faster delivery (it takes less time to get to broadcast the last blocks specially when the Mdw height lags behind Node height when recovering or on a full sync)
- Smaller websocket footprint
=> refactor: enqueue a block only once to ws broadcasting

lib/ae_mdw/sync/server.ex, lib/ae_mdw_web/websocket/broadcaster.ex, lib/ae_mdw_web/websocket/chain_listener.ex, lib/ae_mdw_web/websocket/subscriptions.ex, scripts/do.sh, test/ae_mdw/websocket/broadcaster_test.exs, test/ae_mdw/websocket/subscriptions_test.exs, test/support/ws_client.ex
- Specialize only the order of key blocks (before or after micro blocks+transactions)
- Skips enqueuing micro blocks when there is no subscription
=> refactor: remove duplicated v2 ws enqueuing

lib/ae_mdw/db/channels.ex, lib/ae_mdw/db/sync/contract.ex, lib/ae_mdw/db/sync/transaction.ex, mix.exs, test/ae_mdw/db/sync/transaction_test.exs
In addition, include support for Channel.withdraw and settle events.
NOTE: This change will require a full resync.
=> fix: use proper names for transaction types for events and transactions

Dockerfile
More often than not, the mdw docker image needs to be build with dev/unreleased node versions i.e. master (https://builds.aeternity.io/aeternity-latest-ubuntu-x86_64.tar.gz). 
This change allows that as otherwise default URL pattern (NODE_VERSION) does not.
=> Add NODE_URL docker build argument

lib/ae_mdw/blocks.ex, test/integration/ae_mdw_web/controllers/block_controller_test.exs
This is causing errors with blocks like https://mainnet.aeternity.io/mdw/v2/blocks/444851
=> fix: encode blocks on the /v2/blocks endpoint using formatter

lib/ae_mdw/db/contract.ex, test/ae_mdw/db/contract_call_mutation_test.exs
The function receives only the amount but the event has the owner address just for logging (should not be used for actual update to avoid ilegit burning)
=> fix: add address to Burn event

.dockerignore, Dockerfile, Dockerfile.dev, config/runtime.exs, docker-compose-dev.yml, docker-compose-test.yml, rel/env.sh.eex, rel/overlays/bin/server, rel/overlays/bin/server.bat
This is done using [Mix.Task.Release](https://hexdocs.pm/mix/Mix.Tasks.Release.html) together with the
[auto-generated Dockerfile](https://hexdocs.pm/phoenix/Mix.Tasks.Phx.Gen.Release.html)
This helped reduce the image size to half its size, and it might also help with BEAM code loading efficiency.
=> chore: use mix releases for prod docker images

.github/workflows/dockerhub.yml
- As discussed before `master` images are not needed;
- Uses build args for MIX_ENV as it's now considered by Dockerfile
=> ci: publish images with prod

lib/ae_mdw/db/model.ex, lib/ae_mdw/db/mutations/oracle_query_mutation.ex, lib/ae_mdw/db/mutations/oracle_response_mutation.ex, lib/ae_mdw/db/sync/contract.ex, lib/ae_mdw/db/sync/oracle.ex, lib/ae_mdw/db/sync/transaction.ex
This change will require a new sync due to oracle query IDs being invalid before 1.40
=> chore: remove oracle query response check

Dockerfile, README.md, lib/ae_mdw_web/controllers/util_controller.ex, lib/ae_mdw_web/router.ex, priv/static/swagger/swagger_v2.yaml, scripts/swagger-docs.py, test/ae_mdw_web/controllers/util_controller_test.exs, test/integration/ae_mdw_web/controllers/util_controller_test.exs
=> docs: use /api and /v2/api path for swagger spec files to match node

lib/ae_mdw/blocks.ex, test/ae_mdw/blocks_test.exs
Fix for issue found on HC tests when there is no transaction found:
```
hc_mdw_1           | 10:06:43.587 [error] CRASH REPORT Process <0.7859.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,#{'__exception__' => true,'__struct__' => 'Elixir.AeMdw.Error.Input',message => <<"not found: 0">>,reason => 'Elixir.AeMdw.Error.Input.NotFound'}}},[{'Elixir.AeMdw.Txs','fetch!',3,[{file,"lib/ae_mdw/txs.ex"},{line,425}]},{'Elixir.AeMdw.Blocks','-render_blocks/3-fun-4-',2,[{file,"lib/ae_mdw/blocks.ex"},{line,270}]},{'Elixir.Enum','-map/2-fun-0-',3,[{file,"lib/enum.ex"},{line,1597}]},{'Elixir.Enum',reduce_range,...},...]},...},...},...}
hc_mdw_1           | 10:06:43.593 [error] Cowboy stream 5 with ranch listener …
```
=> fix: add base case for txs from gen

Dockerfile
Testing:
```
docker run -it -v ae_crash_me_db:/home/aeternity/node/local/rel/aeternity/data/mdw.db aeternity/ae_mdw:local-built-image
```
=> chore: allow mounting db dir with docker

Dockerfile
Along with https://github.com/aeternity/aeternity/pull/4107, blocks requests with massive payloads on the mdw's Node.
This [approach](https://www.erlang.org/doc/man/config.html#including-files-from-sys.config-and--configfd-configurations) of including a specific config file on the Node is avoided to let it continue depending on a single config file.
=> perf: set node limit to max body

lib/ae_mdw/db/mutations/oracle_response_mutation.ex
This is due to gameta oracle query transactions having the wrong nonce when returned by the node.
=> chore: ignore oracle responses that don't have associated query

lib/ae_mdw/application.ex, lib/ae_mdw/db/mutations/int_calls_mutation.ex, lib/ae_mdw/db/mutations/write_fields_mutation.ex, lib/ae_mdw/db/sync/transaction.ex, lib/ae_mdw/fields.ex, lib/ae_mdw/node.ex, lib/ae_mdw/txs.ex, lib/ae_mdw_web/controllers/tx_controller.ex, lib/ae_mdw_web/websocket/broadcaster.ex, priv/migrations/20230329160010_index_inner_tx.ex, test/ae_mdw/db/mutations/write_fields_mutation_test.exs, test/ae_mdw/db/sync/transaction_test.exs
* Index inner transaction fields by associating to outer one (`ga_meta_tx` or `paying_for`)
* Apply mask to differentiate `ga_id` from other fields with same field position id (field position 1 is reserved for `ga_id`)
Allow filtering transaction by inner fields along with `type=ga_meta` or `type=paying_for`
=> feat: filter inner txs fields with ga_meta type

lib/ae_mdw/db/mutations/oracle_register_mutation.ex, lib/ae_mdw/db/mutations/oracles_expiration_mutation.ex, lib/ae_mdw/db/mutations/stats_mutation.ex, test/ae_mdw/db/mutations/stats_mutation_test.exs
Avoids double counting inactive oracles by checking if it was the first time the oracle was created (without previous).
Plus, decrements inactive ones that are reactivated.
=> feat: consider existing oracles on inactive ones count

lib/ae_mdw/contracts.ex, lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/model.ex, priv/migrations/20230515090000_contract_event_logs.ex, test/ae_mdw/db/contract_test.exs, test/ae_mdw_web/controllers/contract_controller_test.exs, test/ae_mdw_web/views/aexn_log_view_test.exs
- Allows filtering NFT or AEX-9 contract events
- Applicable to non-standard contracts as well
=> feat: filter logs by both contract and event

docker-compose-dev.yml
```
rogerio@annapurna2:~/Workspace/ae/ae_mdw$ ./scripts/do.sh docker-shell
WARNING: The IMAGE_NAME_SUFFIX variable is not set. Defaulting to a blank string.
Creating ae_mdw_ae_mdw_run ... done
root@0abdab469594:/app# 
exit
rogerio@annapurna2:~/Workspace/ae/ae_mdw$ ./scripts/do.sh docker-shell
Creating ae_mdw_ae_mdw_run ... done
```
=> chore: remove dev docker compose warning

docs/swagger_v2/aexn.spec.yaml, lib/ae_mdw_web/views/aexn_view.ex, test/ae_mdw/db/contract_call_mutation_test.exs, test/ae_mdw_web/views/aexn_view_test.exs
What/Why
Negative number is confusing for users: https://github.com/aeternity/ae_mdw/pull/1260#issuecomment-1591093770
Returns nil (for non-applicable) instead.
refs #1257
=> chore: return nil for invalid amount of aex9 holders

README.md, docs/swagger_v2/txs.spec.yaml, lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw/db/stream/query/parser.ex, lib/ae_mdw/fields.ex, lib/ae_mdw/txs.ex, lib/ae_mdw_web/controllers/tx_controller.ex, test/ae_mdw_web/controllers/tx_controller_test.exs
Introduce query by virtual field (which is not part of transaction record but merged into it)
Support to marketplace use cases and AEX9 based DApps with additional entrypoints as one to provide liquidity.
=> feat: filter contract calls by entrypoint

.github/workflows/test-action.yml, lib/ae_mdw/contract.ex, lib/ae_mdw/db/sync/contract.ex, lib/ae_mdw/db/sync/transaction.ex, test/ae_mdw/db/sync/contract_test.exs
To be able to render contracts we always need the contract_create_tx to be present.
Currently internal events do not include this tx (to be included in [here]( https://github.com/aeternity/aeternity/blob/master/apps/aefate/src/aefa_chain_api.erl#L494).
=> fix: create contract call event tx when Chain events

docs/swagger_v2/base.yaml
It was missed while fixing https://github.com/aeternity/ae_mdw/issues/1361
This PR is supported by the Æternity Crypto Foundation
=> docs: add missed required in PaginatedResponse

lib/ae_mdw/application.ex, lib/ae_mdw/db/sync/block.ex, lib/ae_mdw/sync/mutations_cache.ex, lib/ae_mdw/sync/server.ex, test/ae_mdw/db/sync/block_test.exs, test/ae_mdw/sync/block_test.exs, test/integration/ae_mdw_web/websocket_test.exs, test/support/blockchain_sim.ex
refs #1389 and event dry-running might take some seconds
It caches not only the events but the mutations to avoid reprocessing during mem sync.
=> feat: cache mem sync mutations

docs/swagger_v2/aexn.spec.yaml
fixes a typo introduced in https://github.com/aeternity/ae_mdw/commit/1c4275460b0a9902976969691e390220dad539dc#diff-6011f814194f5b76625486da90f88e7a6dcf0bf15519f95da185d099398172b4L748-R810
> error   | schema_violation | Schema violation: must NOT have additional properties (paths > /v2/aex9/account-balances/{account_id} > get > responses > 200 > content > application/json)
additionalProperty: allOf
This PR is supported by the Æternity Crypto Foundation
=> docs: add missed `schema` around `allOf`

lib/ae_mdw/auction_bids.ex, lib/ae_mdw/db/util.ex, lib/ae_mdw/oracles.ex, lib/ae_mdw_web/views/logs_view.ex, test/ae_mdw_web/controllers/contract_controller_test.exs, test/ae_mdw_web/controllers/name_controller_test.exs, test/ae_mdw_web/controllers/oracle_controller_test.exs, test/ae_mdw_web/views/logs_view_test.exs
=> feat: add further block times to different endpoints

lib/ae_mdw/node_helper.ex
For hyperchains it's likely we start directly with ceres so there won't be account bootstrap files for the earlier heights.
This PR was sponsored by the ACF
=> fix: only bootstrap accounts for configured hardforks

lib/ae_mdw/db/rocksdb_cf.ex, priv/migrations/20230629130000_contract_call_entrypoint.ex, priv/migrations/20230705224000_event_logs_hash.ex
Replaces use of `sext` with built in conversion since for big values as found on contract logs it's much more performatic (record value doesn't need the `sext` conversion):
```
sext: {431389,
<<16, 0, 0, 0, 4, 18, 129, 213, 33, 20, 169, 167, 218, 225, 112, 229, 90, 160,
50, 218, 31, 223, 65, 124, 178, 210, 36, 126, 223, 71, 139, 115, 254, 184,
253, 106, 186, 10, 36, 54, 197, 210, 0, 8, 17, 18, 204, 73, ...>>}
termbin: {7,
<<131, 104, 4, 109, 0, 0, 0, 32, 3, 84, 8, 74, 52, 246, 112, 112, 202, 106, 1,
45, 67, 247, 160, 124, 101, 72, 35, 237, 232, 226, 185, 254, 113, 245, 85,
160, 68, 13, 98, 210, 108, 0, 0, 0, 3, 109, 0, 0, ...>>}
sext: {434452,
<<16, 0, 0, 0, 4, 12, 183, 90, 109, 128, 8, 17, 18, 138, 217, 46, 28, 170, 44,
19, 105, 134, 134, 255, 46, 55, 142, 118, 143, 155, 40, 191, 238, …
```
=> chore: use builtin term to binary conv for values

lib/ae_mdw/db/util.ex, lib/ae_mdw/node/db.ex, test/ae_mdw_web/controllers/name_controller_test.exs, test/ae_mdw_web/controllers/oracle_controller_test.exs
For 100 blocks:
```
iex(aeternity@localhost)2> {ts, _} = :timer.tc(fn -> Enum.map(hashes, fn hash -> Validate.id!(hash) |> :aec_db.get_block() |> :aec_blocks.time_in_msecs() end) end); ts                                                                              
138999
iex(aeternity@localhost)3> {ts, _} = :timer.tc(fn -> Enum.map(hashes, fn hash -> Validate.id!(hash) |> :aec_db.get_header() |> :aec_headers.time_in_msecs() end) end); ts
13124
```
=> perf: use header block time

lib/ae_mdw/aex141.ex, lib/ae_mdw_web/controllers/aex141_controller.ex
Removes validation as the signatures were different and checking both is as expensive than dry run.
Next: Contract validation will tag contracts that are not currently complaint.
=> chore: allow nft owner call for hackaton contracts

lib/ae_mdw/aexn_contracts.ex, test/ae_mdw/aexn_contracts_test.exs
Decode `meta_info` with fields that have been rearranged by the user on the Sophia record when creating the contract.
PS: The difference between name and symbol is based on the heuristics where the symbol begins with more capital letters than the name
solves #847
=> feat: detect AEX-n meta info arrangement

lib/ae_mdw/aexn_contracts.ex, lib/ae_mdw/db/sync/contract.ex, lib/ae_mdw/db/sync/transaction.ex, test/ae_mdw/aexn_contracts_test.exs, test/ae_mdw/db/contract_create_mutation_test.exs, test/ae_mdw/db/sync/contract_test.exs, test/ae_mdw/db/sync/transaction_test.exs
Calls `meta_info` entrypoint using the contract creation block which is less likely to change than the top block. 
refs #1502 
- Still forks might be detected until 10 generations so microblocks might be invalidated and become valid again so a retry might be still needed (if the dry run fails for invalidated microblocks).
- AEX-N extensions will be retrieved from bytecode on a following PR
=> fix: call aexn metainfo on contract creation block

lib/ae_mdw/aexn_contracts.ex, lib/ae_mdw/db/sync/contract.ex, lib/ae_mdw/db/sync/transaction.ex, lib/ae_mdw/db/util.ex, lib/ae_mdw/node/db.ex, lib/ae_mdw/txs.ex, test/ae_mdw/aexn_contracts_test.exs, test/ae_mdw/db/contract_create_mutation_test.exs, test/ae_mdw/db/sync/contract_test.exs, test/ae_mdw/db/sync/transaction_test.exs, test/ae_mdw_web/controllers/block_controller_test.exs, test/ae_mdw_web/controllers/tx_controller_test.exs, test/support/blockchain_sim.ex, test/support/test_samples.ex
- Gets block height needed for calling AEX-N meta info with contract block hash instead of the top.
- Plus, uses the new function where only the header is needed.
=> chore: get block height finding the header

config/runtime.exs, lib/ae_mdw/sync/mem_store_creator.ex
Restore time based garbage collection of memory stores due to legacy/v1 heavy endpoints.
Note: Next, 500 will demand handling for heavier cases to return a timeout.
=> fix: expire memory stores based on v1 heavy endpoints

lib/ae_mdw/aex9.ex, lib/ae_mdw_web/views/aexn_view.ex, test/ae_mdw/db/contract_call_mutation_test.exs, test/ae_mdw_web/controllers/aexn_token_controller_test.exs, test/ae_mdw_web/views/aexn_view_test.exs
Until #1410 is implemented, it changes the counting to be based on events in order to avoid validating multiple times if a contract is raising the events properly.
=> chore: count holders based on events

lib/ae_mdw/application.ex, lib/ae_mdw/db/sync/object_keys.ex, lib/ae_mdw/sync/server.ex, lib/ae_mdw/sync/supervisor.ex
Improves Endpoint availability during startup by loading object keys asynchronously.
=> chore: offload startup by async keys loading

lib/ae_mdw_web/controllers/active_entity_controller.ex, lib/ae_mdw_web/controllers/activity_controller.ex, lib/ae_mdw_web/controllers/aex141_controller.ex, lib/ae_mdw_web/controllers/aexn_token_controller.ex, lib/ae_mdw_web/controllers/aexn_transfer_controller.ex, lib/ae_mdw_web/controllers/block_controller.ex, lib/ae_mdw_web/controllers/channel_controller.ex, lib/ae_mdw_web/controllers/contract_controller.ex, lib/ae_mdw_web/controllers/name_controller.ex, lib/ae_mdw_web/controllers/oracle_controller.ex, lib/ae_mdw_web/controllers/stats_controller.ex, lib/ae_mdw_web/controllers/transfer_controller.ex, lib/ae_mdw_web/controllers/tx_controller.ex, lib/ae_mdw_web/util.ex
Customize json rendering passing a View render function for the specific database key or record.
Same concept adopted for the `Collection.paginate` but applied on the View utils which decouples data fetching from rendering.
Plus renames `Util.paginate` to `Util.render` since the actual pagination is already done by `Collection.paginate` (it only renders).
=> chore: generalize json/view rendering

priv/migrations/20240203120003_dex_events.ex
Fix for calling `aec_fork_block_settings:hc_seed_contracts` on an empty db with CI aeternity.yaml:
```
** (Mix) Could not start application ae_mdw: bad return value: {{AeMdw.Application, :start_phase, [:migrate_db, :normal, []]}, {:EXIT, {{:case_clause, 5}, [{:aec_fork_block_settings, :dir, 1, [file: '/home/builder/aeternity/apps/aecore/src/aec_fork_block_settings.erl', line: 32]}, {:aec_fork_block_settings, :seed_contracts_file_name, 2, [file: '/home/builder/aeternity/apps/aecore/src/aec_fork_block_settings.erl', line: 275]}, {:aec_fork_block_settings, :hc_seed_contracts, 2, [file: '/home/builder/aeternity/apps/aecore/src/aec_fork_block_settings.erl', line: 347]}, {AeMdw.Db.Origin, :hc_contracts, 0, [file: 'lib/ae_mdw/db/origin.ex', line: 154]}, {AeMdw.Db.Origin, :hardforks_contracts, 0, …
```
=> fix: skip node call on empty db

lib/ae_mdw/aexn_tokens.ex, lib/ae_mdw_web/controllers/aexn_token_controller.ex, test/ae_mdw_web/controllers/aexn_token_controller_test.exs
This was causing 500 errors in a few endpoints when sorting by invalid fields: 
https://mainnet.aeternity.io/mdw/v2/aex9?by=pubkey
https://mainnet.aeternity.io/mdw/v2/aex141?by=amount
=> fix: use endpoint-specific ordering validation

README.md, docs/swagger_v3/aexn.spec.yaml, lib/ae_mdw/aex9.ex, lib/ae_mdw_web/controllers/aexn_token_controller.ex, test/ae_mdw_web/controllers/aexn_token_controller_test.exs
This requirements is needed by @kenodressel so that it can use v3 instead of the old v1 endpoint
=> feat: allow getting block-specific AEx9 balances

config/runtime.exs
=> feat: allow logger level configuration

lib/ae_mdw/error.ex, test/ae_mdw_web/controllers/block_controller_test.exs
Erroring route example: https://mainnet.aeternity.io/mdw/v2/key-blocks/kh_KDMuJpBxDagQ4iV7XFXBH5x3snYMEbRyXyBPpf2MrqRaRxLr
=> fix: handle invalid hashes error

lib/ae_mdw/application.ex
refs: #1635.
`AeMdw.APM.Telemetry` was issuing calls to `AeMdw.Sync.MemStoreCreator`, that is started at a later point (by `AeMdw.Sync.Supervisor`), so I switched the starting order, to prevent the error.
=> fix: telemetry error when application starts

config/runtime.exs
Added ENABLE_CONSOLE_LOG environment variable to allow logging to console. ref: #1650
=> feat: add config to allow logging to console

Dockerfile
The problem is that the logs directory is mounted with the wrong permissions. The solution is to delete the old logs and recreate the directory with the correct permissions. This fixes #1634
=> fix: docker logs mount bad permissions

lib/ae_mdw/aexn_transfers.ex
This seems to fix the two randomly failing tests in `aexn_transfer_controller_test.exs` - `gets transfers sorted by desc txi` and `gets transfers sorted by asc txi`.
The reason the tests were failing seems to be the fact that in `AeMdw.AexnTransfers.build_streamer/3` the `AexnContractToTransfer` stream is switching the receiver and sender (for unification with the other stream), which leads to nondeterministic position of the `account_pk` in the cursor when deserializing.
The tests managed to pass randomly because the data for the setup consists of 20 consecutive `AexnContractFromTransfer`, followed by 20 consecutive `AexnContractToTransfer`, so basically the first 2 pages (as required by the tests) were consisting of the same type, and unless the other PK is smaller (or larger, based on …
=> fix: randomly failing tests

docker/aeternity.yaml, lib/ae_mdw/application.ex
Removed the hardcoded log level for the node. The config from aeternity.yaml is used now
ref: #1649
=> fix: remove hardcoded node log level in favor of aeternity.yaml config

docs/swagger_v3/dex.spec.yaml, lib/ae_mdw/dex.ex, lib/ae_mdw/sync/dex_cache.ex, test/ae_mdw_web/controllers/dex_controller_test.exs
refs: https://github.com/aeternity/ae_mdw/issues/1815
=> feat: additional fields to dex endpoints

README.md, docs/swagger_v3/aexn.spec.yaml, docs/swagger_v3/dex.spec.yaml
Otherwise autorest fails with
```
error   | schema_violation | Schema violation: must be equal to one of the allowed values (paths > /v3/aex141/{contractId}/transfers > get > parameters > 3 > required)
allowedValues: true
- file:///.../middleware-openapi.yaml:2802:3
error   | schema_violation | Schema violation: must be equal to one of the allowed values (paths > /v3/aex141/{contractId}/transfers > get > parameters > 4 > required)
allowedValues: true
- file:///.../middleware-openapi.yaml:2802:3
error   | schema_violation | Schema violation: must NOT have additional properties (paths > /v3/dex/{contract_id}/swaps > get > parameters > 1)
additionalProperty: type
- file:///.../middleware-openapi.yaml:2802:3
error   | schema_violation | Schema …
```
=> OpenApi v3 fixes

lib/ae_mdw/db/mutations/name_claim_mutation.ex, test/ae_mdw/db/name_claim_mutation_test.exs
Requires a full re-sync for prior changes to work
=> fix: calculate auction expiration correctly when extension present

config/dev.exs, config/runtime.exs, config/test.exs
The config wasn't being used in the project and was overwriting the nodes config. Now the mdw will use the network that the node it's connected to is using.
ref: #1760
=> fix: remove overwrite of network_id and use values from aeternity.yaml

docs/swagger_v3/activities.spec.yaml, docs/swagger_v3/aexn.spec.yaml, docs/swagger_v3/blocks.spec.yaml, docs/swagger_v3/channels.spec.yaml, docs/swagger_v3/contracts.spec.yaml, docs/swagger_v3/dex.spec.yaml, docs/swagger_v3/names.spec.yaml, docs/swagger_v3/oracles.spec.yaml, docs/swagger_v3/stats.spec.yaml, docs/swagger_v3/transactions.spec.yaml, docs/swagger_v3/transfers.spec.yaml
As I know, only `ttl` field can be missed in tx fields provided by node, like here
https://mainnet.aeternity.io/mdw/v3/transactions/th_TGYTBqCFCrfvdfBXWwQa4KYXhDn8stwRTuJLtuu19ieqKYvjR
Without this change, TS forces me to ensure the property is present before accessing its value.
=> fix: define required fields in Open Api

lib/ae_mdw/db/mutations/name_claim_mutation.ex, test/ae_mdw/db/name_claim_mutation_test.exs
The expiration when timeout != 0 was incorrect, it should instead use the max value of these two:
https://github.com/aeternity/aeternity/blob/master/apps/aens/src/aens_auctions.erl#L84-L86
=> fix: take max expiration between extension and prev expiration

README.md, docs/swagger_v3/stats.spec.yaml, lib/ae_mdw/stats.ex, lib/ae_mdw_web/controllers/stats_controller.ex, lib/ae_mdw_web/router.ex, test/ae_mdw_web/controllers/stats_controller_test.exs
=> chore: rename statistics to stats to remain consistent

docs/swagger_v3/activities.spec.yaml, docs/swagger_v3/aexn.spec.yaml, docs/swagger_v3/base.yaml, docs/swagger_v3/blocks.spec.yaml, docs/swagger_v3/channels.spec.yaml, docs/swagger_v3/contracts.spec.yaml, docs/swagger_v3/dex.spec.yaml, docs/swagger_v3/names.spec.yaml, docs/swagger_v3/oracles.spec.yaml, docs/swagger_v3/stats.spec.yaml, docs/swagger_v3/status.spec.yaml, docs/swagger_v3/transactions.spec.yaml, docs/swagger_v3/transfers.spec.yaml, priv/static/swagger/swagger_v2.json
found issues https://github.com/aeternity/ae_mdw/issues/1910
=> docs: specify pattern for encoded strings

lib/ae_mdw/db/contract.ex, priv/migrations/20240823130804_update_createtxi_in_dex_swaps.ex
This fix should make the dex swaps findable by contract_id
=> fix: dex contract swaps

lib/ae_mdw/collection.ex, test/ae_mdw/collection_test.exs
This change is going to simplify and unify generation of key boundaries for streaming of collections (and prevent small mistakes like using the same value for beginning and end of range while typing out key boundaries).
=> chore: add generation of key boundaries

lib/ae_mdw/db/hardfork_presets.ex, lib/ae_mdw/db/origin.ex, lib/ae_mdw/node.ex
This should fix the issue of some files related to lima being required on networks without lima.
=> chore: make lima files not required

lib/ae_mdw/contracts.ex, lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/mutations/contract_call_mutation.ex, lib/ae_mdw/db/mutations/contract_create_mutation.ex, lib/ae_mdw/node.ex, priv/migrations/20240820120000_aex9_tokens_contract_mint_events_fix.ex, test/ae_mdw/db/contract_test.exs
WAE contracts mistakenly emit a `Withdraw` event instead of `Burn` and a `Deposit` instead of `Mint`. We are now interpreting these events as what they should be.
=> feat: add support for handling WAE contracts as special AEx9 ones

priv/migrations/20240904104336_fix_dex_accounts_swaps.ex
The current bug (described here: https://github.com/aeternity/ae_mdw/pull/1912#issuecomment-2328358259) is probably due to left over incorrect entries (the last few migrations related to those tables relied on existing entries). The current migration creates them from scratch with the correct `create_txi` and with the correct order for the `DexSwapToken`
=> fix: repopulate dex swaps

lib/ae_mdw/activities.ex, test/ae_mdw_web/controllers/activities_controller_test.exs
If there is a cursor, it skips over `pk`s that are `nil`. For example in here: https://mainnet.aeternity.io/mdw/v3/accounts/ak_2Xdym95f2i998W9Zoh1NgAB7pVuQ34ztEsema7u4XwSoq5VKUJ/activities?limit=1 if somebody goes to the `next` page, on it there will be no `prev` page.
=> fix: aexn transfer activities

lib/ae_mdw/stats.ex, test/ae_mdw/stats_test.exs, test/ae_mdw_web/controllers/stats_controller_test.exs
=> feat: add minutes per block in stats

lib/ae_mdw/names.ex, test/ae_mdw_web/controllers/name_controller_test.exs
Currently, accessing a name in a case any other than lowercase doesn't work, e.g.:  https://mainnet.aeternity.io/mdw/v3/names/test.chain works, but https://mainnet.aeternity.io/mdw/v3/names/tEst.chain doesn't. This PR fixes that.
=> fix: contemplate case sensitivity when looking for names

lib/ae_mdw/oracles.ex, test/ae_mdw_web/controllers/oracle_controller_test.exs
=> chore: add default padding to base64 oracles response/queries

lib/ae_mdw/db/rocksdb_cf.ex, priv/migrations/20241010134433_recalculate_aex9_holders.ex
This should fix the aexn contracts that had incorrectly counted holders (and as extension were marked as invalid).
=> fix: recalculate aex9 holders to fix some invalid aexn contracts false positives

lib/ae_mdw/db/model.ex, lib/ae_mdw/db/origin.ex, lib/ae_mdw/db/sync/contract.ex, lib/ae_mdw/db/sync/name.ex, lib/ae_mdw/db/sync/oracle.ex, lib/ae_mdw/db/sync/origin.ex, lib/ae_mdw/db/sync/transaction.ex, priv/migrations/20240930120001_restructure_origins.ex, test/ae_mdw/db/contract_create_mutation_test.exs, test/ae_mdw/db/name_claim_mutation_test.exs, test/ae_mdw/db/origin_test.exs, test/ae_mdw/db/sync/contract_test.exs, test/ae_mdw/db/sync/name_test.exs, test/ae_mdw/db/sync/oracle_test.exs, test/ae_mdw_web/controllers/activities_controller_test.exs, test/ae_mdw_web/controllers/aex9_controller_test.exs, test/ae_mdw_web/controllers/contract_controller_test.exs, test/ae_mdw_web/controllers/dex_controller_test.exs
This is going to allow us later on to identify creation txis by {txi, idx} tuple. Just txi is ambiguous.
=> chore: add contract call index to origin

Dockerfile
This should allow building the docker image with unreleased versions of the node i.e. `master`
```docker build -t aeternity/ae_mdw:local --build-arg NODE_IMAGE=aeternity/aeternity:master .```
=> Remove NODE_VERSION dependancy in Dockerfile

lib/ae_mdw/aex9.ex
Having specified specific range for block history generates invalid range, leading to an internal error, e.g.: https://mainnet.aeternity.io/mdw/v3/aex9/ct_2t7TnocFw7oCYSS7g2yGutZMpGEJta6dq2DTX38SmuqmwtN6Ch/balances/ak_psy8tRXPzGxh6975H7K6XQcMFVsdrxJMt7YkzMY8oUTevutzw/history?scope=gen:487100-487100
=> fix: adjust aex9 balance history endpoint

lib/ae_mdw/util/sorted_table.ex, test/ae_mdw/util/sorted_table_test.exs
Makes first miner to be the wrong one at https://mainnet.aeternity.io/mdw/v3/stats/miners
=> fix: get the last key from a binary keys table

lib/ae_mdw/db/mutations/name_claim_mutation.ex, lib/ae_mdw/db/sync/name.ex, priv/migrations/20241128134337_update_active_account_names.ex, test/integration/ae_mdw_web/controllers/name_controller_test.exs, test/support/integration_util.ex
resolves: https://github.com/aeternity/ae_mdw/issues/1629
Currently the number of active names in the `/names?owned_by=<x>` and `/names/count?owned_by=<x>` are different, for example here: https://mainnet.aeternity.io/mdw/v3/names?owned_by=ak_ynYCVP5HXxEHmptuapK51d7wTRPFnrAnQSewqef5urYcMSJ6s and here https://mainnet.aeternity.io/mdw/v3/names/count?owned_by=ak_ynYCVP5HXxEHmptuapK51d7wTRPFnrAnQSewqef5urYcMSJ6s. My suspicion is that is is due to the counter not increased when a name is put to an auction and the auction ends. This will happen after this PR, as the `Name.put_active` function is called at that event.
=> fix: account active name counter

lib/ae_mdw/db/contract.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw/dex.ex, lib/ae_mdw_web/controllers/dex_controller.ex, lib/ae_mdw_web/router.ex, priv/migrations/20241119120001_index_dex_swaps_by_token.ex, test/ae_mdw/db/contract_test.exs, test/integration/ae_mdw_web/controllers/dex_controller_test.exs
Temporarily adding a debug endpoint to allow us to test. Will move it to `/dex/:contract_id/swaps` once we feel confident about it.
=> feat: add debug endpoint temporarily to list swaps by txi_idx

README.md
=> docs: fix README missing and duplicated links

.github/workflows/release-please.yml
The action was tested from this branch and it created a release PR as expected -> https://github.com/aeternity/ae_mdw/pull/2063
=> chore: bump release-please version to 4

.github/workflows/release-please.yml
The relese-please action has had a breaking change from v3 to v4 where it no longer accepts most of it's arguments as inputs to it and has moved them to separate config files. I've had issues seting that up and migrating the configs, so in the interest of being able to create a hc release I've downgraded to v3 since it has the needed update (where we can fix misslabled commits without rewriting the git tree), but still respects the github action inputs. After we have a HC release for the mdw I'm planning to come back and take a look at implementing that if there is nothing more pressing
=> chore: downgrade release-please version

.github/workflows/test-action.yml, lib/ae_mdw/txs.ex, test/ae_mdw_web/controllers/tx_controller_test.exs, test/integration/ae_mdw_web/controllers/aex9_controller_test.exs, test/integration/ae_mdw_web/controllers/tx_controller_test.exs
The issue was that the transactions count was derived from the last txi, but the txis are indexed from 0, so the count should be the last txi + 1.
=> fix: return the correct number of transactions

lib/ae_mdw/sync/hyperchain.ex, mix.exs
This PR changes the way the mdw checks for a connection to the parent chain in a way that delegates the error handling to the node. The biggest difference is that now the node process responsible for the connection controlls when the code errors out. Now if the parent is reachable it checks periodically to see if the start_height is reached. Otherwise if it is unreachable the node gives a warning and checks again after a short interval.
=> fix: replace hc check to use the node functions

mix.exs, mix.lock
This must be **merged and released** before https://github.com/aeternity/ae_mdw/pull/2086 since there will be changes on the master of ae_plugin
=> chore: pin ae_plugin to the current master by ref

lib/ae_mdw/db/format.ex, lib/ae_mdw/db/model.ex, lib/ae_mdw/db/sync/transaction.ex, lib/ae_mdw/stats.ex, priv/migrations/20250203081538_add_fee_to_txs.ex, test/ae_mdw_web/controllers/oracle_controller_test.exs, test/ae_mdw_web/controllers/stats_controller_test.exs
This speeds the the function that gets the average tx fees in the stats endpoint. Before it timedout the endpoint
=> fix: move tx fees to txs table to fix stats endpoint

lib/ae_mdw_web/plugs/paginated_plug.ex, test/ae_mdw_web/plugs/paginated_plug_test.exs
=> chore: ignore query params that start with underscore

docs/swagger_v3/base.yaml, docs/swagger_v3/stats.spec.yaml, lib/ae_mdw_web/controllers/stats_controller.ex, test/ae_mdw_web/plugs/paginated_plug_test.exs
This PR increases the max_limit of the stats endpoints to 1000. 
resovles: #2041
=> feat: increase the limit of the stats endpoints to 1000

.github/actions/node-setup/action.yml, Dockerfile, README.md, config/config.exs, config/prod.exs, docker-compose-dev-testnet.yml, docker-compose-dev.yml, docker-compose-hc.yml, docker-compose-test.yml, docker-compose.yml, mix.exs, mix.lock
This PR aims to unify the config and data paths between the mdw and node images so that the mdw image is a drop in replacement for the node. 
~~This relies on a change in this PR https://github.com/aeternity/ae_plugin/pull/11 and the mdw in this branch is using a fork that has implemented it. That PR would need to be merged so that this one can be changed back to the correct repo~~
=> feat!: make docker paths the same as in the node images

docs/swagger_v3/oracles.spec.yaml
=> docs: remove dependency between `OracleQuery` and `OracleResponse` in OA

docs/swagger_v3/channels.spec.yaml, docs/swagger_v3/contracts.spec.yaml, docs/swagger_v3/names.spec.yaml, docs/swagger_v3/transactions.spec.yaml, lib/ae_mdw/db/format.ex, test/ae_mdw_web/controllers/activities_controller_test.exs
Added the missing fields in the swagger for transactions and added the ttl field to the transactions as in the docs
resolves: #2115
=> docs: add tx types to transactions_spec.yaml
